### ISSUE TITLE
Question about NestedFunctionViolation

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#1003]
`NESTED_FUNCTIONS_WHITELIST` contains only `factory` and `decorator`. But how should I name nested functions in parametrized decorator if there is no factory inside?

Code example
```python
def json_response(params):
    def decorator(func):
        @wraps(func)  # noqa: WPS430
        async def wrapper(*args, **kwargs):
            ...
        return wrapper
    return decorator
```

**Comment by sobolevn** [comment]
I use this notation: the first one is a `factory` (that creates decorators), the second one is the actual `decorator`.

Does it sound ok to you?

**Comment by sobolevn** [comment]
I count this one is solved, please reopen if that's not the case. 👍 

Thanks a lot for raising this question!
