### ISSUE TITLE
Forbid inline if-else

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1008]
# Rule request

## Thesis

https://pypi.org/project/flake8-if-expr/

Bad:

```python
r = t if c else f
```

Good:

```python
if c:
  r = t
else:
  r = f
```

## Reasoning

It's not so easy to read. Most of the languages have a condition first (`= cond ? true : false`), but Python is different (`true if cond else false`). It's confusing, and the only reasoning behind using such expression is saving lines of code that not a good goal for Python.

## Solution

It's implemented in the plugin above, but I'm quite skeptical about one-rule plugins. I propose to re-implement this simple check instead of adding one more dependency.

**Comment by sobolevn** [comment]
What about `if` inside comprehensions? They are also inlines.

**Comment by orsinium** [comment]
> What about if inside comprehensions?

If you about the condition at the end of the comprehension, it's ok. It's a nice way to do filtering. However, when it's as a value, things become even more complicated.

Good:

```python
[a for a in b if a]
```

bad:

```python
[t if a else f for a in b]
```

I'm also not sure about the rule in the issue description, but this example definitely hurts me :eyes:

**Comment by sobolevn** [comment]
Ok, let's start with forbidding `IfExp` in comprehensions.

**Comment by sobolevn** [comment]
There's no reason to copy the exact same behaviour, if a person wants to forbid this expression, there's an existing plugin for it.

We use general `IfExp` quite often without any problems.

**Comment by ruwaid4** [comment]
@sobolevn It is unclear whether this rule should be implemented or not.

**Comment by sobolevn** [comment]
Nope, we use a lot of `ifexpr` in our code. And basically I really like ternary expressions.
