### ISSUE TITLE
Unclear documentation about BracketBlankLineViolation

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#1020]
# Bug report

## What's wrong
Documentation says
```python
# Correct:
arr = [
    1,
    2
]

# Wrong:
arr = [
    1,
    2
]
```

But for me, they are the same pieces of code.

## How is that should be
Don't know, that's why I ask.

**Comment by sobolevn** [comment]
Done! https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/consistency.py#L2038-L2050
