### ISSUE TITLE
Detect getters and setters

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1054]
# Rule request

## Thesis

We can inspect class and instance methods to find these pattern: if class contains two methods like `get_X` and `set_X` we should raise `UnpythonicGetterSetterViolation`

We should also detect cases like:

- class has instance or class level attribute `x` or `_x` or `__x`
- class has method called `get_x` or `set_x`

It is `oop` violation.

## Reasoning

Because python does not need this abstraction:
- Either use `@property`
- Or just make the property public and change it

**Comment by Gwin73** [comment]
Hi, can I take the issue?

**Comment by sobolevn** [comment]
Sure! @Gwin73 thanks a lot!

Feel free to ask any questions.

**Comment by sobolevn** [comment]
@Gwin73 I have updated the task description. Please, take a look 🙂

**Comment by ruwaid4** [comment]
Hello, i am part of the same group as @Gwin73 who is working on this issue. Just to clarify some things, should it be: class has instance or class level attribute `x` or `_x` or `__x` AND class has method called `get_x` or `set_x`?

**Comment by sobolevn** [comment]
When either case is satisfied 🙂  (logical `or`)

**Comment by ruwaid4** [comment]
Thanks for the quick answer! So this would mean no instance or class level attributes are allowed since `x` matches anythin?

**Comment by sobolevn** [comment]
I mean `x` is an abstract field name. It can be anything. Any name.

**Comment by Gwin73** [comment]
I think there must be some misunderstanding here. Instance or class level attributes x or _x or __x must be allowed right, as long as they are "public" and have no corresponding get_x or set_x methods.

**Comment by Gwin73** [comment]
Only allowing properties and NO attributes seems a bit weird.

**Comment by sobolevn** [comment]
Sorry, that I am not able to express myself clear enough 🙂 

This rule only checks method names. We need to detect patterns like `get_${existing_attribute_name}` and `set_${existing_attribute_name}` and raise violations when any of these methods are found.

Where `${existing_attribute_name}` can be public, protected, or private.

**Comment by ruwaid4** [comment]
So it should be:
* class has instance or class level attribute `x` or `_x` or `__x`
AND
* class has method called `get_x` or `set_x`

**Comment by sobolevn** [comment]
Yes 👍
