### ISSUE TITLE
Linter does not work offline

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1060]
Currently I had a problem that I was not able to run `flake8` with `nitpick` while offline.

That's not how it should be. We need to add `--offline` boolean flag to skip `nitpick` check.

**Comment by sobolevn** [comment]
As a workaround you can `pip uninstall nitpick` while offline.

**Comment by skarzi** [comment]
Shouldn't such option be added to `nitpick` instead of `wemake-python-styleguide`?
`nitpick` is, after all, a flake plugin.

**Comment by skarzi** [comment]
Ohh, I have checked `nitpick` PRs and feature is in progress - https://github.com/andreoliwa/nitpick/pull/129

**Comment by orsinium** [comment]
The linked PR is merged. Can the issue be closed?
