### ISSUE TITLE
Add a link to TooLongTryBodyViolation

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1076]
We need to add:

```python
"""
    See also:
         https://adamj.eu/tech/2019/10/02/limit-your-try-clauses-in-python/
"""
```

Exact location: https://github.com/wemake-services/wemake-python-styleguide/blob/e86a12cf396cd537409ec0b46e9a88fda2aa95c4/wemake_python_styleguide/violations/complexity.py#L901-L903
Link to add: https://adamj.eu/tech/2019/10/02/limit-your-try-clauses-in-python/
This article explains our idea pretty well.

Our docs: https://wemake-python-stylegui.de/en/latest/pages/usage/violations/complexity.html#wemake_python_styleguide.violations.complexity.TooLongTryBodyViolation

P.S. 1000 commits milestone!
<img width="213" alt="Снимок экрана 2019-12-17 в 16 20 23" src="https://user-images.githubusercontent.com/4660275/70998806-2f39b000-20e9-11ea-9013-12d55645f3d6.png">

**Comment by pvldruzhinin** [comment]
I’d take this issue!

**Comment by sobolevn** [comment]
Assigned, thanks a lot!
