### ISSUE TITLE
Missing @sobolevn on RPBM-4

### ISSUE THREAD

**Issue by kxepal** [wemake-services/wemake-python-styleguide#1079]
# Bug report

## What's wrong

During [RPBM-4](https://www.meetup.com/Moscow-Python-Beer-Meetup/events/267247907) preparation we found that @sobolevn is not on the attendees list and is going to miss everything. Literally, everything! 

## How is that should be

@sobolevn should manage to get there. The best plan is at first to arrive to Moscow and join us to travel together by the ~green python train~ sapsan train. We're going to reserve big part of it to improve your trip experience. Alternative, you can always join us later on the venue - we'll catch you up there.

P.S. Awesome project! Love it! But this bug ruins a lot of experience. Let's fix that!

**Comment by sobolevn** [comment]
@kxepal thanks a lot for reaching out! I love our community for these moments!

Sadly, I don't have the resources (both time and money) to make this possible. I have on-going a construction work in my new apartment. It is not going to end soon enough 🙁 

I wish you, guys, a happy trip. Thanks again for inviting me! 👍

**Comment by zzzsochi** [comment]
:-(  Ochen' zhal'.
