### ISSUE TITLE
Reserve names on PyPI

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1088]
Names `wps` and `wemake` are free on PyPI. Probably, it's a good idea to reserve them by dummy packages that does nothing except printing "probably, you mean wemake-python-styleguide" when you tries to install them.

## Motivation

Users are often referer to wemake-python-styleguide as `wemake` or just `wps` (because now it's the official error code). So, squatting of those names by someone else can be dangerous.

**Comment by sobolevn** [comment]
Done!

1. https://pypi.org/project/wps/
2. https://pypi.org/project/wemake/
