### ISSUE TITLE
Add `--local-partial-types` to the set of required mypy settings

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1096]
We need to add it here:
1. https://github.com/wemake-services/wemake-python-styleguide/blob/master/setup.cfg#L108
2. https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/mypy.toml#L2

Related: https://github.com/python/mypy/pull/8201/files

**Comment by theLastOfCats** [comment]
I'll take it
