### ISSUE TITLE
FlakeHell is not only for legacy

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1097]
# Documentation improvement

Some users come to the conclusion that flakehell is a wrapper to make baseline for flake8:

https://github.com/life4/flakehell/issues/34#issuecomment-569723359

However, that's not totally true. It has a different way to configure plugins that makes it not totally compatible with flake8. Wemake docs confuse people that want only one particular feature from it without adjusting anything else.

## Possible solution

We can point on [config](https://flakehell.readthedocs.io/config.html) section in FlakeHell to draw users attention to some differences between Flake8 and FlakeHell.

**Comment by sobolevn** [comment]
Thanks, I agree!

Also related:
- https://gitlab.com/pycqa/flake8/issues/602
- https://gitlab.com/pycqa/flake8/issues/601

**Comment by sobolevn** [comment]
Related #1095

**Comment by sobolevn** [comment]
Let's unify it with https://github.com/wemake-services/wemake-python-styleguide/issues/1095
