### ISSUE TITLE
move some constants to optional configuration options

### ISSUE THREAD

**Issue by skarzi** [wemake-services/wemake-python-styleguide#1103]
hi :wave: 

I am using `wemake-python-styleguide` in several types of python's projects and some of them are built using framework e.g scrapy. Such frameworks and sometimes also domain language force developers to use some names that are forbidden by few `wemake-python-styleguide` violations, e.g [WPS110](https://wemake-python-stylegui.de/en/latest/pages/usage/violations/naming.html#wemake_python_styleguide.violations.naming.WrongVariableNameViolation). 
It would be really great to make `setup.cfg`'s options from some constants, for instance `VARIABLE_NAMES_BLACKLIST` to easily support above mentioned cases.
Please, let me know what is your opinion about this. 

Thanks for such great project!
Kind Regards,
Lukasz

**Comment by sobolevn** [comment]
Hi, @skarzi! Thanks a lot for your feedback.

I currently do not want to make this configurable, because it will allow to mostly disable this check. And I have spent years on figuring out on what to put there.

Can you please be more specific? What names are conflicting with scrapy?

**Comment by skarzi** [comment]
that's true, however I think we can assume that developers know what they are doing.
This option will be used really rarely, but can be useful in some cases.

In `scrapy` it's popular to use name `item` (for instances of [`scrapy.item.Item`](https://docs.scrapy.org/en/latest/topics/items.html#scrapy.item.Item) class)  and few methods that developers sometimes override take parameter with such name.

**Comment by sobolevn** [comment]
How about `allowed-domain-names=['item', 'handle']`? This will remove several names from the list. The name will show that it should only be changed when the domain tells you so.

And in contrast we can add `forbidden-domain-names` that will be added to the list. Like sometimes you cannot name your variable as `index`, you have to use `zip` or something like this. I am not sure about this part, though.

**Comment by skarzi** [comment]
sounds great!
Can I prepare PR with this features?

**Comment by sobolevn** [comment]
Sure! Thanks!
