### ISSUE TITLE
WPS245 on single argument functions

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1104]
It would be a good addition to WPS245 if it was able to ignore functions which take only one argument. If you are able to inspect the actual function, then only ignore when the argument is mandatory.

In many cases these arguments are self-explanatory, for example: `set_sensitive(False)`
This looks a bit silly to me when it's rewritten as: `set_sensitive(sensitive=False)`

**Comment by sobolevn** [comment]
I agree, let's do it. Are you interested in providing a fix?

**Comment by skarzi** [comment]
Can I prepare PR for this issue?

**Comment by sobolevn** [comment]
Sure, @skarzi! Thanks a lot!
