### ISSUE TITLE
WPS412: Flask App Factory Pattern Incompatibility

### ISSUE THREAD

**Issue by ElPapi42** [wemake-services/wemake-python-styleguide#1108]
# Rule request

## Thesis

Change WPS412 to accept logic inside __init__.py files.

## Reasoning

Flask App Factory Pattern depend on the main package __init_.py for define the create_app() function, this is the natural location for this type of logic. Check [this](https://github.com/ElPapi42/WeMakeServices-Test/blob/master/application/__init__.py) example Flask project's __init__.py

Maybe this can be a problem too for when a subpackage if defined, and is natural to expose its internals in the __init__.py for avoid boiler plate, for example:

Change
```python
from deepbay.denseblock import DenseBlock
```
To
```python
from deepbay import DenseBlock
```
If my reasoning is not good enough, feedback will be appreciated, thanks!

**Comment by ElPapi42** [comment]
If my reasoning is not good enough, feedback will be appreciated, thanks!

**Comment by ElPapi42** [comment]
I can can metion [this](https://hackersandslackers.com/flask-application-factory/) Flask Mega-Tutorial as reference and backup for my suggestion.

**Comment by sobolevn** [comment]
Why not `application/app.py`?

**Comment by ElPapi42** [comment]
@sobolevn that sounds legit, but dont cover the other case, reduce boilerplate when importing libraries

> Change
> 
> ```python
> from deepbay.denseblock import DenseBlock
> ```
> 
> To
> 
> ```python
> from deepbay import DenseBlock
> ```

**Comment by sobolevn** [comment]
In our rules `__init__.py` only solves the compatibility issues. That's why it is configured via `--i-dont-control-code` setting.

And namespaces are always a great idea! We need more of those!

**Comment by ElPapi42** [comment]
Got it @sobolevn. can you give me some insights or recommendations about how i can refactor my code?

Go for the application.<blueprint-name>.bluepirnt.py for init the blueprint related stuff? 

In other python applications, should i keep the __init__.py for expose the subpackage internals more directly to the namespace?

Just looking for a clear path to resolve this, thanks in advance!

**Comment by sobolevn** [comment]
Just rename your `__init__.py` to `blueprint.py` (or whatever suits you best) and create a new empty `__init__.py`

Does this solve your problem?

**Comment by ElPapi42** [comment]
just one last question: What i must do with the imports in the __init__.py:

1) get rid of them and let the imports be:
```python
from deepbay.denseblock import DenseBlock
```
2) Keep the imports and do:
```python
from deepbay import DenseBlock
```
In the last case, WPS will still mark unused imports warning.

What approach you recommend to me?

Thanks for your time, sorry for pick it up a bit.

**Comment by sobolevn** [comment]
I always keeps imports out of `__init__.py` - it allows to match files and modules as 1-to-1 entities.
Helpful and readable!

**Comment by sobolevn** [comment]
I am going to close this as solved, if you have any other questions - please, feel free to ask!
You can reopen this one or create new issues if you have other questions.
