### ISSUE TITLE
Multiple excepts raising 440/441

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1115]
Not sure these violations seem correct to me. With code such as:

```
try:
  ...
except OneException as e:
  do_something(e)
except AnotherException as e:
  do_something_else(e)
```

This throws WPS440 and WPS441.

Not sure why this is considered a block variables overlap, when only one of these blocks will be run, and the variable is referencing the local block variable.

WPS441 also looks wrong as the variable is not used after the block as it claims, but only within the block that defined it.

**Comment by sobolevn** [comment]
Can you please post the exact messages?

**Comment by Dreamsorcerer** [comment]
```
./src/tesla.py:84:9: WPS440 Found block variables overlap: e
./src/tesla.py:86:92: WPS441 Found control variable used after block: e
```

**Comment by Dreamsorcerer** [comment]
Lines 79-86:
```
        try:
            vehicles = await self.client.list_vehicles()
        except tesla_api.AuthenticationError as e:
            await self.client.close()
            raise GUIError(_("Login details are incorrect.")) from e
        except tesla_api.aiohttp.client_exceptions.ClientConnectorError as e:
            await self.client.close()
            raise GUIError(_("Network error. Please check your network connection.")) from e
```

**Comment by sobolevn** [comment]
Related #1154

**Comment by sobolevn** [comment]
Ok, here's what I have done: 
1. I have removed `WPS441` for `except`, because it is covered by `F821` from `flake8`
2. I have fixed `WPS440` for `except` in same `try` blocks
