### ISSUE TITLE
WPS331 doesn't make sense if additional work needs to be done

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1116]
I get a WPS331 error with code like this:

```
        try:
            vehicles = await self.client.list_vehicles()
        except tesla_api.AuthenticationError as e:
            return error

        save_api_details()
        return vehicles
```

Until the assignment is completed successfully, I don't know if the API details are correct. Therefore, they need to be saved after the assignment, but before the return.

I'd propose to avoid this rule if there are additional statements between the assignment and the return.

**Comment by sobolevn** [comment]
Yes, you are correct. This is a bug. Thanks!

**Comment by sobolevn** [comment]
Related https://github.com/wemake-services/wemake-python-styleguide/issues/598
