### ISSUE TITLE
Make abstract classes abstract

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1121]
There are several classes that are not marked as `abstract`. But, they should be!

Like:
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/base.py
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/base.py

We need to import `abc` and use `metaclass=ABCMeta` for all of them.

**Comment by skarzi** [comment]
I can take it.

We just need to establish how mark class attribute as an abstract:

+ leave it as it is, so:

   ```python
   error_template: ClassVar[str]
   ```

+ use `abc.abstractmethod` and `property` decorators:

   ```python
   @property
   @abc.abstractmethod
   def error_template(self) -> str:
       ""Message that will be shown to user after formatting"""
   ```

   however then exceptions can be misleading: `TypeError: Can't instantiate abstract class 
   TestViolation with abstract methods error_template`

+ prepare some custom metaclass or `__init_subclass__` implementation to check if certain class attributes are present

What's your thoughts?

**Comment by sobolevn** [comment]
I think that just making classes abstract is good enough. Thanks a lot for your help!
