### ISSUE TITLE
Add `__call__` to list of methods that should be on top

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1125]
I guess that the order should be the following:

- `__new__`
- `__init__`
- `__call__`

Things to edit:
1. https://github.com/wemake-services/wemake-python-styleguide/blob/06e94265bc27263b87d58a640a08435bae96d47c/wemake_python_styleguide/violations/consistency.py#L1516
2. https://github.com/wemake-services/wemake-python-styleguide/blob/e84e7671aad08a5acc87646f1c86f20cd65ce400/wemake_python_styleguide/visitors/ast/classes.py#L410
3. https://github.com/wemake-services/wemake-python-styleguide/blob/f5447577113bd4c7c397a0e7970a62908bd11f73/tests/test_visitors/test_ast/test_classes/test_method_order.py

**Comment by gillesigot** [comment]
May I take it?

**Comment by sobolevn** [comment]
Sure! Thanks a lot!

**Comment by sobolevn** [comment]
Closed by https://github.com/wemake-services/wemake-python-styleguide/pull/1129
