### ISSUE TITLE
cache all things dependent on configuration options

### ISSUE THREAD

**Issue by skarzi** [wemake-services/wemake-python-styleguide#1130]
Hi,

in #1129 domain's names options that allow developers to modify variable names' blacklist were introduced. Construction of this blacklist can be performed only once, because it depends only on some constants and configuration options, that are also static (loaded from CLI flags or ini config), so there is no need to compute them for every file being checked.
We already have discussed using `lru_cache` decorator on `variable_names_blacklist_from` function, but because of my misunderstanding of flake8 and `Checker` lifecycle I haven't used it.
I have `grep`ped `logic` module to check if there is any other usage of configuration options that can be cached, but I haven't found anything else.
Can I add `lru_cache` decorator this time? Well, better late than never :smile:  

Regards,
Łukasz

**Comment by sobolevn** [comment]
Thanks a lot for the issue! Yes, indeed: we can boost things here.

**Comment by skarzi** [comment]
I will prepare PR on the weekend

**Comment by sobolevn** [comment]
@skarzi thanks a lot for your **massive** help!
