### ISSUE TITLE
Knowing the violation code it is quite hard to find the violation description

### ISSUE THREAD

**Issue by anatoly-scherbakov** [wemake-services/wemake-python-styleguide#1145]
**Use Case.** I am testing wemake-python-styleguide on my project.

```
...
  22:5     WPS337 Found multiline conditions
  if (
  ^

Full list of violations and explanations:
https://wemake-python-stylegui.de/en/0.13.4/pages/usage/violations/
make: *** [infra/make/lint.mk:3: lint] Error 1
```

To get more information on what `WPS337` is for, I have to do several steps:

* Open https://wemake-python-stylegui.de/en/0.13.4/pages/usage/violations/
* Realize that WPS337 is probably behind the link titled `WPS300 - WPS399`
* And now I am stuck; I can `Ctrl + F` → `337`, but that won't help; so I try to find the word `multiline`
* and finally I reach the description I wanted: https://wemake-python-stylegui.de/en/0.13.4/pages/usage/violations/consistency.html#wemake_python_styleguide.violations.consistency.MultilineConditionsViolation

This takes time, especially when the title of the violation on this page does not exactly correspond to the name the tool prints on command line.

**Ideally,** I would see a link to the violation description right in the console, like this:

```
...
  22:5     WPS337 Found multiline conditions https://wps.it/0.13.4/WPS337/
  if (
  ^
...
```

Regrettably, wps.to domain is registered already, but wps.it is there.

**If that is not possible,** it would help if the docs pages at least included the violation codes, to make the page searchable via `Ctrl + F`.

**Comment by skarzi** [comment]
That's good idea, my teammates also complain on the lack of some website, where all codes can be easily discovered and investigated, so this will really useful

**Comment by sobolevn** [comment]
I had this idea too. But, it is kind of useless without all codes that come from other plugins and `flake8`. AFAIK there's no way of getting the violation docs from the code.

So, we would have to maintain docs for ALL violations we use in this project. 
Do this sound scary enough 😄 ?

**Comment by skarzi** [comment]
[`flakehell`](https://github.com/life4/flakehell) has nice cli option - `flakehell codes <plugin_name>`.
I haven't investigated the implementation of codes' extractors, but it is somehow possible, probably they have to handle several cases, because unfortunately `flake8` doesn't enforce plugin's developers to provide some standardized documentation of all codes used by their plugins :(
So, yeap, it sounds scary :D

**Comment by sobolevn** [comment]
@orsinium do you have any ideas how can we implement this?

**Comment by orsinium** [comment]
> do you have any ideas how can we implement this?

Yes, I do. We can provide our own CLI.

```bash
python3 -m wemake_python_styleguide code WPS337
```

Also, you can even implement your own runner as a minimal alternative to flake8 ([like deal does](https://deal.readthedocs.io/linter.html)) and show a bit more information on it like URL, short description etc.

What about third-party plugins, it's non-trivial. As @skarzi said, FlakeHell does it. However, it's mostly about ad-hoc solutions, so it's better to not pollute WPS with such logic and leave it to FlakeHell.

**Comment by jnoortheen** [comment]
It can be added at the end next to each errors when the combined error count is shown, much like eslint. Each of the major plugin has a documentation page for error codes. Even if pointing to the exact code is not possible, it could give the link to documentation.
