### ISSUE TITLE
Support nameless arguments convention

### ISSUE THREAD

**Issue by cbows** [wemake-services/wemake-python-styleguide#1146]
# Bug report

Nameless arguments convention used in type annotations of callables causes WPS112

## What's wrong

Taken from [mypy documentation](https://mypy.readthedocs.io/en/latest/additional_features.html#extended-callable-types):

```python
from typing import Callable
from mypy_extensions import (Arg, DefaultArg, NamedArg,
                             DefaultNamedArg, VarArg, KwArg)

def func(__a: int,  # This convention is for nameless arguments
         b: int,
         c: int = 0,
         *args: int,
         d: int,
         e: int = 0,
         **kwargs: int) -> int:
    ...

F = Callable[[int,  # Or Arg(int)
              Arg(int, 'b'),
              DefaultArg(int, 'c'),
              VarArg(int),
              NamedArg(int, 'd'),
              DefaultNamedArg(int, 'e'),
              KwArg(int)],
             int]

f: F = func
```

The same goes for callback protocols (also taken from [mypy documentation](https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols)):

```python
from typing import Callable, TypeVar
from typing_extensions import Protocol

T = TypeVar('T')

class Copy(Protocol):
    def __call__(self, __origin: T) -> T: ...

copy_a: Callable[[T], T]
copy_b: Copy

copy_a = copy_b  # OK
copy_b = copy_a  # Also OK
```

As seen here, double-underscore variable names are used to specify nameless function arguments when annotating callables. This causes WPS112 (Found private name pattern).

## How it should be

While I agree with WPS112, I think this is a special case where it should be allowed, especially in the latter case of callback protocols, where the dunder name is only used to define the protocol.

**Comment by sobolevn** [comment]
Yes, `__` arguments should be allowed. Thanks!

**Comment by sobolevn** [comment]
Ok, here's the deal. This is only really valid for `Protocol` 
Other use-cases are obviously invalid.

But, we cannot detect that this is used inside a `Protocol`. Because there are subclasses, different naming, etc.

So, this is not going to be resolved. Sorry.
