### ISSUE TITLE
Annotation complexity should be tested with `ast.Attribute`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1187]
Currently code like `x: typing.List[typing.List[typing.List[typing.List[int]]]]` is not tested.
Inside `tests/test_visitors/test_ast/test_complexity/test_annotation_complexity/test_annotation_complexity_nesting.py` we don't have any attributes at all.

We need to add several tests for attributes.

**Comment by leksuss** [comment]
Please, assign this issue to me.
