### ISSUE TITLE
Refactor some class-level constants to be real constants

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1188]
We need to move several class-level constants to `wemake_python_styleguide/constants.py`

Here's the list (can be found by `baseline=self._`):

- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/complexity/counts.py#L178-L182
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/complexity/counts.py#L250
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/complexity/counts.py#L308

We also need to document these constants in violation docs, like so:

```python
@final
class SomeViolation(...):
    """
    ...

    We use :str:`wemake_python_styleguide.constants.OUR_CONSTANT`
    as a default value.
    """
```

**Comment by JazabC** [comment]
@sobolevn Can I be assigned to this issue? If not is there an issue you recommend I should try to tackle? thanks

**Comment by sobolevn** [comment]
Sure! Thanks for your help!

**Comment by sobolevn** [comment]
Here's the guide that might be helpful to you: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md

**Comment by JazabC** [comment]
@sobolevn I made a pull request but I am unsure where to document these constants in violation docs
