### ISSUE TITLE
Forbid to use `lI` names

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1191]
# Rule request

## Thesis

Currently one can name your classes like so: `ControlIn`
And it is unreadable! Inside it is just `L` and `i`, but we cannot tell it from the word.

We need to forbid lowercase `l` followed by uppercase `I`

## Reasoning

Readability matters!

**Comment by sobolevn** [comment]
Are there any other letters that behave like that?

**Comment by NickVolynkin** [comment]
`Fill1List.`

**Comment by NickVolynkin** [comment]
Also there are letters (Unicode codepoints) which are different but look just the same.
For example, there's Latin `A`, Greek `Α`, Cyrillic `А`.

But actually, let's just ban any letters outside the standard ASCII set. Anything which requires using non-English keyboard layout, anything which has modifiers. And emoji.

**Comment by sobolevn** [comment]
Thanks! 

- `I` (`i` uppercase) and `l` (`L` lowercase) should be banned too!
- We have already banned all unicode chars in variable names.
- Can you please tell more about `1`? It does not look similar to `l` or `L`
- What  about `o` and `0` and `O`?

**Comment by NickVolynkin** [comment]
`l1I` and `0O` are distinguishable, but still risky. Probably, a warning?

**Comment by sobolevn** [comment]
We don't have warnings. Errors are better!

**Comment by kennycontreras** [comment]
Anyone is working on this?

**Comment by sobolevn** [comment]
No, @kennycontreras feel free to take this one! Ask any questions you have.

**Comment by Kvm99** [comment]
Hi. Could I take the issue?

**Comment by kennycontreras** [comment]
@Kvm99 Yes please, I don't have much time at the moment so I'll leave it for now.

**Comment by sobolevn** [comment]
@kennycontreras no worries, come back when you will have the time! 👍 

@Kvm99 thanks a lot! Assigned!
