### ISSUE TITLE
Replace pkg_resources with importlib

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1196]
`python3.8` shipped builtin tool to work with versions: https://docs.python.org/3/library/importlib.metadata.html

We can use it instead of `pkg_resources`: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/version.py

And we can also use `importlib_metadata` package for Python versions prior to `3.8`

**Comment by sobolevn** [comment]
Related: https://hynek.me/articles/packaging-metadata/

**Comment by skarzi** [comment]
Can I take it?

**Comment by sobolevn** [comment]
Sure! @skarzi, thank you!
