### ISSUE TITLE
Allow the pass keyword inside a class that inherits from other classes

### ISSUE THREAD

**Issue by vergeev** [wemake-services/wemake-python-styleguide#12]
For example, the following is the only way in Django to inherit the `Meta` class:
```
class Meta(BaseModel.Meta):
    pass
```
But unfortunately it triggers `WPS100 Found wrong keyword "pass"`.

More generally, the following should be allowed as it's a common thing to do:
```
class Foo(BarMixin, FooBase):
    pass
```

Right now the `# noqa` comment helps to avoid the warning.

**Comment by sobolevn** [comment]
Nope, the correct way to do is:

```python
class Foo(BarMixin, FooBase):
    """This class is used a representation of ..."""
```

This way we encourage best practice (writing docs) over the meaningless keyword.
