### ISSUE TITLE
Ensure that `FalsyConstantCompareViolation` counts `NamedExpr`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1201]
Currently we don't handle `NamedExpr` in this violation.

One can write this code:

```python
if (x := []) == other:
    ...
```

And it won't be handled properly. Here's how direct values are compared:

```python
  1:4      WPS520 Found compare with falsy constant
  if [] == other:
     ^
```

File to fix: https://github.com/wemake-services/wemake-python-styleguide/blob/ea20c44bbbb8dcf70b3541b073cee25ae91a8354/wemake_python_styleguide/visitors/ast/compares.py#L151

We also need to test this violation. Make sure that you use `pytest.skipif(PY38, ...)` because this syntax is only valid starting from `python3.8+`

Related #1137

**Comment by edytagarbarz** [comment]
Let me fix this one

**Comment by sobolevn** [comment]
Sure! Thank you, @edytagarbarz! Make sure to read [our contributing guides](https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md)

I am here to help: ask anything you need.

**Comment by sobolevn** [comment]
@edytagarbarz friendly ping to make sure you don't have any problems with the task. But, if there's something I can help you with - feel free to ask! 👍

**Comment by sobolevn** [comment]
By the way, this commit does pretty much the same thing as you need: https://github.com/wemake-services/wemake-python-styleguide/commit/4fa9f411fbe5c24477f4b7d975ed84845b405e64 Check it out!

**Comment by edytagarbarz** [comment]
Thank you @sobolevn! Configuration took me a while but now no problems at all :)
