### ISSUE TITLE
Ensure that `WrongInCompareTypeViolation` counts `NamedExpr`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1209]
Currently we don't handle `NamedExpr` in this violation.

One can write this code:

```python
if 'a' in (x := [1, 2, 'a', 3]):
    ...
```

And it won't be handled properly. 

File to fix: https://github.com/wemake-services/wemake-python-styleguide/blob/ea20c44bbbb8dcf70b3541b073cee25ae91a8354/wemake_python_styleguide/visitors/ast/compares.py#L454

We also need to test this violation. Make sure that you use `pytest.skipif(PY38, ...)` because this syntax is only valid starting from `python3.8+`

Related #1137

**Comment by gillesigot** [comment]
Looks interesting, may I take this one?

**Comment by sobolevn** [comment]
Thank you! @gillesigot assigned! 👍 

I was thinking about this one and all #1137 tasks in general. I guess that we should use somekind of `get_assigned_expr` logic function that returns the assigned part and can be reused for all these tasks. I am open for any feedback here.

**Comment by gillesigot** [comment]
> I was thinking about this one and all #1137 tasks in general. I guess that we should use somekind of `get_assigned_expr` logic function that returns the assigned part and can be reused for all these tasks. I am open for any feedback here.

Ok, I was thinking of doing something like this:
```
def _get_assigned_expr(node: ast.Compare) -> ast.Compare:
    """Helper function to retrieve assigned value in ``NamedExpr`` comparator."""
    for idx, comparator in enumerate(node.comparators):
        if isinstance(comparator, ast.NamedExpr):
            node.comparators[idx] = comparator.value
    return node
```
If you agree, I guess I can take all the related tasks (cf. #1137) since this function will be helping for those...

**Comment by sobolevn** [comment]
I would prefer a function without a mutation. Because with mutation we can break things really badly. 

Let's better `return` the correct node from it.
