### ISSUE TITLE
Add `NamedExpr` template to name testing 

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1212]
We should test that `NamedExpr` follows all the same rules that other ways to assign values.

We should modify `tests/test_visitors/test_ast/test_naming/conftest.py` to add a new template there. I think, that it should be enough. All other tests will work from there.

Here's what this template should look like:

```python
if {0} := other_call(): 
    ...
```

We should only add this template for `python3.8+`

Related #1137

**Comment by jigi-33** [comment]
Hello, can I take this issue?

**Comment by sobolevn** [comment]
Sure! Thank you!

**Comment by sobolevn** [comment]
And one more case: `lambda {0}, /: ...`

**Comment by Hiyorimi** [comment]
On it
