### ISSUE TITLE
Forbid `__reduce__` and `__reduce_ex__` magic methods

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1220]
# Rule request

## Thesis

These two methods work with `pickle` module.
And we consider `pickle` unsafe. And discourage its usage.

Instead one should use `json` serialisation. 

So, these two magic methods should be forbidden.

## Reasoning

Related:
1. https://pycharm-security.readthedocs.io/en/latest/checks/PIC100.html
2. https://stackoverflow.com/questions/150284/what-is-the-difference-between-reduce-and-reduce-ex

This is a best practice rule. One can copy these links to the violation docs.

**Comment by JazabC** [comment]
Hi, I would like to work on this but am a beginner and would appreciate some assistance :)

**Comment by sobolevn** [comment]
Hi, @JazabC!

This is one of the easiest tasks. Here's what you need to do: Add these two methods to the blacklist here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/constants.py#L224

You can even use Github UI for this 🙂 

So, can I assign you on this one?

**Comment by JazabC** [comment]
@sobolevn Yes i'd like to be assigned to this one. Thank you for the information!

**Comment by sobolevn** [comment]
Closed by #1229
