### ISSUE TITLE
Add `pyflakes` to the list of forbidden libraries

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1233]
We need to add `pyflakes` to `forbidden_modules =` here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/.importlinter#L65

**Comment by sergeycrisp** [comment]
Hello, i can try to do it!)

**Comment by sobolevn** [comment]
Done! Thanks a lot!

**Comment by sobolevn** [comment]
Closed by #1237
