### ISSUE TITLE
Check for ssh/amazon keys, diffs and other patterns in string variables

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1236]
# Rule request

## Thesis

There are several tools from which we can copy several checks to enforce better security:

1. https://github.com/landscapeio/dodgy/blob/master/dodgy/checks.py
2. https://github.com/Yelp/detect-secrets/tree/master/detect_secrets/plugins

There are several simple regexes to copy. And then we can add this check to our tool.

Plan:
1. A single violation for all of these checks
2. A collection of regexes that check string / bytes / formatted strings definitions
3. Lots of tests!

## Reasoning

Storing any secrets in strings is a bad idea. Use proper secrets management tool like https://github.com/sobolevn/git-secret

**Comment by PrVrSs** [comment]
I'll add this rule

**Comment by sobolevn** [comment]
Thanks a lot!

**Comment by sobolevn** [comment]
Out of scope, there are special linters for that.
