### ISSUE TITLE
Possibly forbid names with too low Levenshtein distance

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1247]
This is not a request at the moment. Just an idea. I invite everyone to discuss it.

Naming is hard. Sometimes people make bad decisions when giving names to their variables / functions / classes / etc.

Levenshtein distance: https://en.wikipedia.org/wiki/Levenshtein_distance

Here are some examples that I have seen in real code (luckily not in ours):
- `res_e` and `res_r` for `response_error` and `response_result`. It should be an error!
- `xx` and `xy`. Can be an error, I am not sure (maybe we can add minimal length parameter, to ignore short names)
- `user1` and `user2`. Should not be an error. I use this in tests all the time. And I cannot think of any better names for lots of cases. (maybe we can ignore numbers)
- `response` and `responce`. The second one contains a typo. Should probably be an error
- `regular` and `other`. Is not an error, obviously
- `request` and `Request`. Is not an error
- `_user` and `user`. Is not an error (maybe we can ignore starting `_`)
- But! `user` and `user_` is an error (why would anyone do that?) Notice, that `x_` is an error on its own: `WPS120 Found regular name with trailing underscore: x_`

What do other people think about it?

**Comment by sobolevn** [comment]
@AlwxSin @kxepal @orsinium what do you guys think?

**Comment by orsinium** [comment]
> res_e and res_r for response_error and response_result. It should be an error!

This one isn't about the similarity of vars names but that they aren't descriptive enough. If only `res_e` is represented in the code, it's still the same error. A possible solution is to do an error not only on one-char var names but also on a one-char word inside snake_case variable (`res_e` is an error, `res_err` isn't).

> xx and xy. Can be an error, I am not sure 

Let's not do what we're not sure about. For example, `pi` is the best name for the famous math constant, right?

> response and responce. The second one contains a typo.

It's a hard topic, let's live it to separate solutions like [flake8-spellcheck](https://github.com/MichaelAquilina/flake8-spellcheck).

> user and user_ is an error (why would anyone do that?) Notice, that x_ is an error on its own: WPS120 Found regular name with trailing underscore: x_

No reason to duplicate errors for the same case.

A check for homoglyphs (#1191) is a good thing. A check for low text distance is too hard and fragile. It can fail on the top of the file on adding a new variable at the bottom, it can conflict with business logic, it can panic on cases when a human can easily distinguish the difference, and so on.

**Comment by AlwxSin** [comment]
As @orsinium said, there are a lot of corner cases. I doubt that it's possible to cover most of them.

**Comment by sobolevn** [comment]
Ok, I agree. Let's close it for now.
