### ISSUE TITLE
Disallow to ignore some violations on line level

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1248]
# Rule request

## Thesis

Sometimes developers inline ignore violations that should not be ignored. Like complexity violations, best practices, or any others that are important for this specific project.

So, we need to give users an option to provide a configuration hook with violations names (both short like `WPS` and full ones like `WPS102`) that cannot be ignored.

And when we find inline ignore of this violations - we should raise a new one on `0` line.

We do not check `per-file-ignores` and `ignored` with this check.

Related: https://github.com/wemake-services/wemake-python-styleguide/pull/1246/files#diff-2c42a0740c36d757ff4d489010b3138eR4

This is a best practices violation.

**Comment by edytagarbarz** [comment]
Hi, let me work on this!

**Comment by sobolevn** [comment]
@edytagarbarz you are welcome!
