### ISSUE TITLE
Add flake8-spellcheck to docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1249]
Let's add this awesome plugin to the list of external plugin in the docs!
Docs: https://github.com/wemake-services/wemake-python-styleguide/blob/master/docs/pages/usage/integrations/plugins.rst

Link: https://github.com/MichaelAquilina/flake8-spellcheck

**Comment by charleshayes** [comment]
@sobolevn May I take over this issue? I am looking to make my first open source contribution, and this would be a great entry point for me.

**Comment by sobolevn** [comment]
@charleshayes absolutely! Thanks a lot!

**Comment by sobolevn** [comment]
@charleshayes friendly ping 🙂 Do you need any help from my side?

Just for to be helpful: you can use github website to do this task, no need to fork / clone it manually. See https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by sobolevn** [comment]
@charleshayes feel free to send a PR in any case, but I will leave this issue for some other new-comer 🙂

**Comment by leksuss** [comment]
Hello, let me take it :)

**Comment by sobolevn** [comment]
@leksuss thanks!

**Comment by leksuss** [comment]
@sobolevn should I add so minor changes to the `CHANGELOG.md` ?

**Comment by sobolevn** [comment]
No, this is not required 🙂
