### ISSUE TITLE
Bump `flake-isort` to 2.9

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1260]
New version of `flake8-isort` is released: `2.9.0`

We need to update our dependency here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L71
Here's how to do it: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md#dependencies

**Comment by altvec** [comment]
May I take over this issue?

**Comment by sobolevn** [comment]
Sure, thanks a lot!
