### ISSUE TITLE
Add flake8-coding to the docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1262]
Let's add this awesome plugin to the list of external plugin in the docs!
Docs: https://github.com/wemake-services/wemake-python-styleguide/blob/master/docs/pages/usage/integrations/plugins.rst

Link: https://github.com/tk0miya/flake8-coding

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1249

**Comment by Andrka** [comment]
May I take over this issue?

**Comment by sobolevn** [comment]
@Andrka you are welcome! Thanks!
