### ISSUE TITLE
Enforce consistent comprehension structure

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1266]
# Rule request

## Thesis

Currently we can write comprehensions any way we want. I suggest to leave just two options:

1. Single-line comprehensions like `[some(number) for number in numbers]`
2. Properly structured one (action, for loops, and condition are all on different lines):

```python
[
   some(number)
   for numbers in matrix
   for number in numbers 
   if number > 0
]
```

Wrong cases:

```python
[
   some(number) for number in numbers 
   if number > 0
]
```

```python
[
   some(number)
   for numbers in matrix for number in numbers 
   if number > 0
]
```

```python
[
   some(number)
   for numbers in matrix if number > 0
]
```

## Reasoning

This a consistency rule.

**Comment by skarzi** [comment]
Sometimes I also see code using following formatting:

```python
[
    some: something_else
    for some, something_else, *_
    in some_data
]
```

but I think it also should be restricted

**Comment by sobolevn** [comment]
I agree 👍

**Comment by jdrober9** [comment]
Hello again! @sobolevn we would like to assign ourselves this issue as well. We will be taking on these three issues over the course of the next two weeks. We have already started reading the documentation and will reach out if we have any questions! Thank you again.

**Comment by sobolevn** [comment]
@jdrober9 done! Thank you!

**Comment by portablesounds** [comment]
Could myself as well as a few peers take a shot at this issue?

**Comment by sobolevn** [comment]
@portablesounds you are more than welcome! 👍
