### ISSUE TITLE
Enforce consistency with tuple brackets

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1279]
# Rule request

## Thesis

There are several cases when brackets for a tuple can be really important:

1. Single element tuples: `x,` vs `(x,)` the second one is easier to read and looks like tuple, the first one is tuple-ish enough.
2. Multiple elements in tuple: `x = 1, 2, 3` vs `x = (1, 2, 3)` I still prefer explicit brackets
3. Unpacking: `x, y = t()` vs `(x, y) = t()` I like the first one more, because it looks more like a variable assignment. The same applies to `for`, `with`, etc
4. Returing and yielding: `return x, y` vs `return (x, y)` I like the first one more. But, is it consistent with other our rules?

## Reasoning

This is consistency rule. It will be checked with `libcst`.
Related #1068 https://github.com/wemake-services/wemake-python-styleguide/pull/1147

**Comment by orsinium** [comment]
The first one: https://github.com/PyCQA/flake8-commas

I think I've seen remaining as well but can't recall. Should be checked.

**Comment by sobolevn** [comment]
Related: `(original, )` vs `(original,)`

**Comment by sobolevn** [comment]
Covered by ruff now
