### ISSUE TITLE
False positives for 'WPS323' on logging calls

### ISSUE THREAD

**Issue by noxxious** [wemake-services/wemake-python-styleguide#1304]
# Bug report
The WPS323 checks for "%" in the strings instead of the % operator classifies the python logging framework calls, which rely on the % pattern as positives. There's no easy migration path to fix these in as described in https://docs.python.org/3/howto/logging-cookbook.html#using-particular-formatting-styles-throughout-your-application

## What's wrong

The python logging calls are flagged positively by WPS323 and there's no easy workaround.

## How is that should be
Resort to older method by checking for % operator instead.

## System information

wemake-python-styleguide==0.14.0

**Comment by sobolevn** [comment]
Yes, this is working as intended. There are several things to do:

1. https://sobolevn.me/2020/03/do-not-log
2. https://stackoverflow.com/questions/13131400/logging-variable-data-with-new-format-string/36294984
3. Disable this check and use `flake8-pep3101` instead

Thanks a lot for your submission.

Maybe we can improve the docs?

**Comment by noxxious** [comment]
Thanks for the pointers. I do think your comments would be a good additional documentation/knowledge base on the case. Linter errors should be a learning opportunity as much as automated check.

**Comment by sobolevn** [comment]
@noxxious are you willing to submit a doc fix? 🙂 🙏

**Comment by orsinium** [comment]
Decision:

1. Do not touch the rule. It checks exactly what it supposed to check. "Migration is hard" is applicable to the old formatting style as well (there are a few autoformatters for it but so).
1. Update the docs to provide more recommendations on how to fix the issue.
