### ISSUE TITLE
Lint Python distribution files

### ISSUE THREAD

**Issue by kxepal** [wemake-services/wemake-python-styleguide#1307]
# Rule request

There is an idea to add rules set upon project distribution files validation.

## Thesis

This project does great job on checking Python code. But code just remains in VCS, people uses it via distribution artifacts, like wheels or sdist. And even with ideal code style it can be broken for users because:

- You forgot include static files into dist;
- Your sdist includes README with Makefile targets instructions, but Makefile is missed;
- Your wheel ships tests with giant fixture files;
- You forgot to fill all the required metadata fields, so your project description is now UNKNOWN;
- ...and more;

See https://github.com/jwodder/check-wheel-contents for an example.

## Reasoning

While this feature request make sounds like a bit alien for the rest project, I think that project style is not only how your write the code, but also how you ship the code. Python provides two standard ways to do that: wheels for binary or universal distribution and sdist for building out of the sources.
Both may contains flaws and issues and even break user experience. And I may be repeat myself again, there is no point to have good code style if you can't properly ship your code.

What do you think?

**Comment by sobolevn** [comment]
Thanks a lot for the idea! I will take some time to research this topic.

**Comment by sobolevn** [comment]
Related https://github.com/jwodder/check-wheel-contents

**Comment by sobolevn** [comment]
Related https://github.com/regebro/pyroma

**Comment by sobolevn** [comment]
However, this task is out of scope of this project. We can create a new one! 
Possibly under https://github.com/moscow-python-beer
