### ISSUE TITLE
pylint like duplicate code detection

### ISSUE THREAD

**Issue by jnoortheen** [wemake-services/wemake-python-styleguide#1317]
# Rule request

Pylint has a feature to detect similar lines and report duplicate code. Is it possible to add such rule to flake8?

## Reasoning

lesser the code, lesser the bugs and lesser code to maintain

**Comment by sobolevn** [comment]
Sorry, I don't think so. At least it won't be easy. Why?

`flake8` operates with one file at a time. `pylint` does know about other modules.
So, we cannot get the contents of another file with `flake8` and AFAIK there's no way in saving the intermediate results.

But:
1. You can use https://github.com/kucherenko/jscpd or pylint with just this check
2. I will dig into it and possibly find some ways to hack it
