### ISSUE TITLE
Add a link to `python-linters-and-code-analysis` repo in the docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#132]
https://github.com/vintasoftware/python-linters-and-code-analysis

What needs to be done:
1. Find the best place in the docs, where this line fits best
2. Add the link there!

**Comment by AlexArcPy** [comment]
@sobolevn , yep, this one is great. Found one more flake8 plugin that is not added to the wemake python linter yet - https://github.com/stephenfin/flake8-asserts

**Comment by sobolevn** [comment]
@AlexArcPy thanks for your suggestion! 

But, we are using `pytest` with function style tests.
Example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_violations.py

And we are already linting our code with `flake8-pytest` not to use `unittest`.
Reference: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L71

P.S. Have you tried this linter on your project? How did you like it? Do you have any feedback?
Cheers!

**Comment by AlexArcPy** [comment]
Ah, OK then! I just went through the list of plugins you pulled in (from the list https://wemake-python-styleguide.readthedocs.io/en/latest/_pages/violations/index.html) and thought you may want to add this one, too. Now I see that this would be redundant.

I am planning to start playing around with your linter, can't wait actually. I have a couple of large codebases and would love to see what the linter would find. It has been a cumbersome experience having multiple linters (flake8, pylint, sonarcube and some more) that I had to run from multiple IDEs and using different cmd. Having everything collected in a single place is very neat. I will let you know how it works. What would be the easiest way to provide feedback?
Also, while reading the docs yesterday night, found a couple of typos here and there. Mind if I fix it in a cloned repo and then submit the pull request? Would love to contribute to such a great effort! :)

**Comment by sobolevn** [comment]
@AlexArcPy waiting to hear from you! 

You could provide a feedback via github issues or email. Choose what suits you best.
And contributions are always welcome! 🎉

**Comment by sobolevn** [comment]
Done: https://github.com/vintasoftware/python-linters-and-code-analysis/pull/8

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/commit/454d49a0a7ff1e155eeea12641ef95da868aebaf
