### ISSUE TITLE
Wrong copy paste in docs

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#1328]
# Bug report

## What's wrong
```
class TooManyPublicAttributesViolation(node, text=None, baseline=None)[source]
Bases: wemake_python_styleguide.violations.base.ASTViolation

Forbids to have try blocks with too long bodies.

We only check static definitions in a form of self.public = .... We do not count parent attributes. We do not count properties. We do not count annotations. We do not count class attributes. We do not count duplicates.
```

## How is that should be
`Forbids to have try blocks with too long bodies.` should be deleted from `TooManyPublicAttributesViolation`

**Comment by sobolevn** [comment]
Whoops, sorry!

**Comment by priyanshu20** [comment]
Hello,
Will updating the "complexity.py" file's comment update the documentation as well?
I am not very intimated with documenting a project.

**Comment by sobolevn** [comment]
Hi, @priyanshu20!

1. Yes
2. You have to replace it with something more meaningful

Thanks a lot for your interest in this project! 👍
