### ISSUE TITLE
Forbid compare with float

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1344]
# Rule request

## Thesis

This code might not work as one would think:

```python
x == 3.0
```

Because `x` can be `0.3 / 0.1` which is:

```
>>> 0.3 / 0.1
2.9999999999999996
```

## Reasoning

This is a best practice rule.

**Comment by raghul-rajasekar** [comment]
Hi, I'd like to work on this issue.

**Comment by sobolevn** [comment]
Thanks a lot, @raghul-rajasekar!

**Comment by raghul-rajasekar** [comment]
Hi, I have a couple of queries.

1. Which comparisons should be forbidden exactly? Initially I felt it would be sufficient to forbid equality and inequality alone as mentioned in issue #1357, but the ``<=`` and ``>=`` operators could be forbidden as well, as they can be replaced with suitable usage of ``<``, ``>`` and ``isclose`` from ``math``.
2. As the same issue occurs for ``complex`` as well, perhaps ``==`` and ``!=`` comparisons could be forbidden for them as well. Usage of ``isclose`` from the ``cmath`` module would be the suggested alternative.

**Comment by sobolevn** [comment]
@raghul-rajasekar Great questions!

1. I would say we need to ban all. At first sight seems like we only care about `==` and `!=`, but on the second thought we can face this:

```python
>>> 0.1 + 0.2
0.30000000000000004
>>> 0.1 + 0.2 <= 0.3
False
```

So, I would say all compares are harmful. 

2. Yes, I agree.

```python
>>> 0.1j + 0.2j
0.30000000000000004j
```

**Comment by raghul-rajasekar** [comment]
Just clarifying, only the ``==``, ``!=``, ``<=`` and ``>=`` compares would have to be banned, right? While ``<`` and ``>`` are harmful too, banning them as well would leave no solution to compare two floats (unlike equality/inequality, for which ``isclose`` exists). So it's better to allow ``<`` and ``>`` alone and trust that the programmer uses these operators prudently.

**Comment by sobolevn** [comment]
The only correct way to compare floats are fuzzy operators. Like `isclose`. Other ways can (and will) lead to bugs. 

> and trust that the programmer uses these operators prudently

I know that may sound strange, but we tend not to trust programmers here 🙂 
When building a quality tool, it is important to assume the worst case scenario. 

What can be used?

1. `abs(f1 - f2) <= allowed_error`
2. `isclose` from `math`
3. Custom logic, but not operators!

**Comment by vnmabus** [comment]
I would say that order comparisons should be allowed. How do you tell that one of the operand does not already correspond to an absolute value or a distance, and that small epsilons are not important?

At the very least, they should be independent checks, so that one could disable comparisons and still have warnings for equality checks.
