### ISSUE TITLE
Add `__await__` to the list of priority magic methods

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1362]
It should come right after `__call__` in priority.

Logic: https://github.com/wemake-services/wemake-python-styleguide/blob/0f50854b2c2ed335f8e86a6da2f9d6e0df369619/wemake_python_styleguide/visitors/ast/classes.py#L396
Violation docs: https://github.com/wemake-services/wemake-python-styleguide/blob/e12aa891b97062075eb1c2c1fe111d06172717b4/wemake_python_styleguide/violations/consistency.py#L1530
Tests: https://github.com/wemake-services/wemake-python-styleguide/blob/58b96219a39390c35353aa9a29d483d5ed3f1cf7/tests/test_visitors/test_ast/test_classes/test_method_order.py

**Comment by Slyfoxy** [comment]
Hi, @sobolevn !
I made pr with this functionality. Could you take a look?

**Comment by sobolevn** [comment]
Sure, thanks!
