### ISSUE TITLE
Allow installing without dependencies

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1371]
Is there a way to install this without the dependencies?

I've seen syntax for extra dependencies in pip like: `pip install aiohttp_security[session]`

Could there be something similar to make the dependencies of this project optional?

I would prefer to choose which of those projects to install. For example, flake8-isort seems to be broken for me, and I've replaced it with flake8-import-order.

**Comment by sobolevn** [comment]
No, sorry. This is a completely out of scope. 

This package is the collection of things that work together perfectly. And might not make any sense without each other. So, we cannot make dependencies optional. However, we work on several things to port things we can into the core package.

To solve your problem you can ignore `I` code for the files that you wish not to cover with `isort`.
If it is broken completely, then you can open an issue and we will fix that.

But thanks a lot for raising this question!

**Comment by Dreamsorcerer** [comment]
Regarding isort, the line_length config doesn't seem to work, bug at: https://github.com/gforcada/flake8-isort/issues/87

It also gives the most useless output, just saying that an import is in the wrong place. It took me 20 minutes of trial and error to figure out it was complaining about line wrapping. Compare that to flake8-import-order which tells you exactly what is wrong and what it should look like.

Regarding dependencies, I've not encountered any issues running it after uninstalling a few of the dependencies (other than the obvious issue that they get reinstalled on upgrade).
