### ISSUE TITLE
WPS421 doesn't catch pprint.pprint()

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1373]
WPS421 has pprint in the blacklist, however does not catch a call to `pprint.pprint()`.

**Comment by sobolevn** [comment]
@Dreamsorcerer are you willing to fix this?

**Comment by Dreamsorcerer** [comment]
Would adding `"pprint.pprint"` to the blacklist be enough to cover it, or does it need something more complex?

**Comment by sobolevn** [comment]
No, it would be a bit harder. Currently we only watch for attr name, without `pprint.` part.

**Comment by jaydesl** [comment]
Out of curiosity I had a look at this. Because of the way `astor` resolves the parsed code to a string, adding `pprint.pprint` to the blacklist does work to resolve this issue.

Want a PR with the fix and an explicit test?

**Comment by sobolevn** [comment]
@jaydesl yes, please!
