### ISSUE TITLE
Wemake can break pyflakes

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1375]
This is a bit of a weird one, but it seems that wemake can sometimes mess things up for pyflakes resulting in flake8 throwing exceptions. No idea how to reproduce it, but it seems I'm not the only one to have encountered it.

Context and error messages at: https://github.com/PyCQA/pyflakes/issues/537

**Comment by Dreamsorcerer** [comment]
Fix is to uninstall and reinstall, but no idea how to reproduce it in the first place.

**Comment by sobolevn** [comment]
Please, report back if this continues to happen!
