### ISSUE TITLE
WPS226 ignore indexing

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1376]
Would it make sense to exclude strings used to index an object from WPS226? Or an option to do so.

I find this rule is occasionally useful to remind me that I'm overusing a string. However, it creates too much noise where strings are used to index, and are therefore being used similarly to variable names.

As an example, I'm writing an aiohttp web application. Therefore, some things are stored in the dict-like application object in order to be accessible throughout the application.

This means frequent code such as:
`app["db"]`
keeps resulting in complaints that I'm overusing the string "db".

**Comment by AlwxSin** [comment]
Just a tip. If one will use `app` not like dict but like an object, there are no problems. And typing works. For example
```python
class AioApp(web.Application):
    """Class for attribute type checking."""

    api_client: ClientSession
    redis: Redis
    db: Pool


class AioRequest(web.Request):
    """Class for attribute type checking."""

    @property
    def app(self) -> AioApp:
        """Typed application instance."""
        app = super().app
        return tp.cast(AioApp, app)


async def setup_app(app: AioApp) -> None:
    app.api_client = web.ClientSession()
    app.db = await get_db()
    app.redis = await aioredis.create_redis_pool(redis_connection, db=settings.REDIS_DB)


def get_app() -> AioApp:
    """Create aiohttp app with services (redis, session, etc)."""
    app = web.Application(client_max_size=client_max_size)
    app = tp.cast(AioApp, app)

    app.on_startup.extend(on_startup)
    
    return app

async def handler(request: AioRequest):
    await request.app.db.fetchone(...)
    await request.app.redis.set(...)
    return web.Response()
```

**Comment by sobolevn** [comment]
I agree with @AlwxSin on this one. If you are using `app['db']` too often it means, that:
- You can probably use a variable instead
- Maybe it is not the best data structure for the job and object might fit better

And this use-case is still valid. Do not overuse string keys! 

P.S. Offtopic, @AlwxSin can you please check out our new feature in `returns`? https://github.com/dry-python/returns/issues/274

**Comment by Dreamsorcerer** [comment]
Perhaps, but that is not an approach mentioned or recommended in the aiohttp docs: https://docs.aiohttp.org/en/stable/web_advanced.html#data-sharing-aka-no-singletons-please

**Comment by sobolevn** [comment]
100% it, I would say that `aiohttp` has very serious design issues. This is one of them.

**Comment by Dreamsorcerer** [comment]
@AlwxSin Out of curiosity, why do a type cast, as opposed to creating an instance of AioApp directly (I've not actually encountered this cast before)?

**Comment by AlwxSin** [comment]
@Dreamsorcerer in `AioRequest.app` property because instance already exists. In `get_app` function just for clarity. We create the aiohttp app, not our `AioApp`. `AioApp` is a fake subclass, just for typing, it is not a subclass in OOP way. So, create an app as always and cast it.

**Comment by Dreamsorcerer** [comment]
Now, what about subapps? For these, you would use `Request.config_dict`, which will look for keys in the app and all of it's parents.

**Comment by AlwxSin** [comment]
@Dreamsorcerer can't say. We don' use subapps. But I found this issue https://github.com/aio-libs/aiohttp/issues/2689

**Comment by Dreamsorcerer** [comment]
The other time I often encounter this is getting tables from the SQLAlchemy MetaData object: `app.db_meta.tables["users"]`.
