### ISSUE TITLE
Create strict ordering inside a class

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#139]
Skeleton:
1. magic methods
2. protected class methods
3. public class methods
4. protected methods
5. public methods
6. all other things

**Comment by sobolevn** [comment]
Or it is possible to list public API first:

1. public constants
2. public functions
3. public classes
4. protected constants
5. protected functions
6. protected classes
7. all other things

**Comment by sobolevn** [comment]
Or it is possible to declare public interface first, then declare the protected members.

**Comment by AlexArcPy** [comment]
@sobolevn , may I ask how you have come up with this order? There are two great discussions on this at https://softwareengineering.stackexchange.com/questions/199311/most-human-friendly-way-to-order-class-method-definitions and https://stackoverflow.com/questions/10289461/what-is-a-good-way-to-order-methods-in-a-python-class. I believe there is no PEP for this, so did you come up with this order based on previous experience or you have seen some Python specific guidelines on this?

**Comment by AlexArcPy** [comment]
An interesting parser we could perhaps take advantage of? https://github.com/SergeySatskiy/cdm-pythonparser. It claims to have more features and perform way faster than the built-in https://docs.python.org/3.6/library/pyclbr.html

**Comment by sobolevn** [comment]
@AlexArcPy thanks! looks promising.

**Comment by sobolevn** [comment]
I am currently thinking about this ordering:

1. public class attributes
2. protected class attributes
3. any other class attributes

4. `__new__`
5. `__init__`
6. any other magic methods
7. any public methods
8. any protected methods
9. everything else

This should work for mostly all cases.

**Comment by sobolevn** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md

**Comment by sobolevn** [comment]
https://twitter.com/PurpleDiane88/status/1094638194899902464

**Comment by sobolevn** [comment]
Too complex and too restrictive. Unusable.
