### ISSUE TITLE
WPS202 shouldn't fail in modules with test

### ISSUE THREAD

**Issue by webknjaz** [wemake-services/wemake-python-styleguide#1409]
# Bug report

## What's wrong

I have a test module with a bunch of fixtures and test functions and the linter already
tells me that it has too many members. I don't think it's reasonable for test modules.
This specific one has like 62 lines (including spacing between the functions and docstrings, and comments). It's definitely not bit, two test functions are one-liners
and the fixtures are split into multiple for simplicity (making it easier to read the
code, not harder).

## What's wrong / How is that should be

This check should be clever enough to detect this and maybe apply different metrics
whenever it encounters the test modules. If you see a chain of fixtures that are used
in a few test methods making them simple, that should set a positive score.
Also, the number of test functions is not a good metric (although I'd say that too
little testing would be a sign that there's not enough testing in place).

## System information

N/A

**Comment by sobolevn** [comment]
This is going to be ignored by default after https://github.com/wemake-services/wemake-python-styleguide/issues/1120 will be merged. Let's track it there.
