### ISSUE TITLE
disable module for run?

### ISSUE THREAD

**Issue by jpmorris** [wemake-services/wemake-python-styleguide#1412]
Is it possible (or at least I don't see it in the docs) to disable this module entirely?  My use case: my team checks on default flake8, but I want to run this module against my changes.  I believe the later can be accomplished via diff.  But how would I run default flake8 without these strict rules just to see what the rest of the team is seeing?

**Comment by sobolevn** [comment]
For all code: `--ignore=WPS, DAR, RST` 
And for your diff you can remove this line.

**Comment by jpmorris** [comment]
unfortunately this is not sufficient.  I ran stock flake8 and it pulled back one error. After installing this package, I get lots of errors D100, I 003, E126, Q000, N803, S403. 

Now my team has put 'noqa' flags in places I think, if that matters.  But maybe this is the result of one of the many other flake8-* modules that were installed?

**Comment by sobolevn** [comment]
Yes, probably. We also install `flake8-isort`, `flake8-broken-line` and many-many others.
You should probably wait for #1276

**Comment by jpmorris** [comment]
so the magic line is:

`--ignore=WPS,DAR,RST,B,C,D,E,I,N,P,Q,S,T,W`

since the external-plugins page mentions that base flake8 are F*** codes, I assume the above should be correct (as it appears to be for me).  If I'm wrong, let me know.
