### ISSUE TITLE
WPS425 on single argument to functools.partial

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1421]
Related to #1104, where it was changed to allow boolean positional arguments, if it is the only argument.

As a small additional exception, it should do the same thing with functools.partial. i.e.
`functools.partial(set_sensitive, False)`
should not trigger WPS425.

**Comment by sobolevn** [comment]
Is `set_sensitive` you own function?

**Comment by Dreamsorcerer** [comment]
No, I was just using the example from the previous ticket, they are Gtk methods.

The actual case I'm encountering is another Gtk method though, when trying to use it as a callback:
`functools.partial(self._revealer.set_reveal_child, False)`

**Comment by sobolevn** [comment]
Can you used named arguments with `Gtk`?

**Comment by Dreamsorcerer** [comment]
Yes, but as per #1104, it just seems weird using something like `set_sensitive(sensitive=True)`. I think that's still weird when used as a partial `partial(set_sensitive, sensitive=True)`.

**Comment by sobolevn** [comment]
@Dreamsorcerer it is not weird. Moreover, `partial(set_sensitive, sensitive=True)` and `functools.partial(set_sensitive, False)` is not the same thing.

**Comment by sobolevn** [comment]
I recommend to use `partial(set_sensitive, sensitive=True)` whenever possible. And to use `noqa` for cases when it is not possible for some reason (posonly, C, etc).

**Comment by Dreamsorcerer** [comment]
I guess the only problem I can is if there are multiple arguments, and you're just using partial to specify the first one:
```
func = partial(set_things, False)
...
func(True, 5)
```

But, when used as a complete callback (where the original function only takes 1 argument), I don't see how it's any different to `set_sensitive(True)`/`set_sensitive(sensitive=True)`.

**Comment by sobolevn** [comment]
I am going to close this one, because this is too specific. Let's use `noqa` for it 👍
