### ISSUE TITLE
Forbid to use `0.0`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1422]
# Rule request

## Thesis

One can use `0.0.` instead of `0`.
It might result in very strange but hard to find typing bugs, example:

```python
x = 0.0

y: int = 13 - 10 + x
# y is now float!
```

One should use `0`. Always! 

I have seen some people is using it to cast `int` to `float`.
When you need a float, then cast it to float explicitly. And not with `0.0` magic.

**Comment by arudzinska** [comment]
Hi, I'd like to take this issue.

**Comment by sobolevn** [comment]
Thanks a lot!
