### ISSUE TITLE
Lint code blocks in docstrings

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1436]
Docstrings can have code blocks and [doctest](https://docs.python.org/3/library/doctest.html)s. Let's lint them as well!

I'd name it "recursive linting" but no need to lint docstrings from code examples in docstrings :upside_down_face: 

## Reference implementation

There is a wrapper that runs flake8 against docstrings: https://github.com/kataev/flake8-rst

However, native support from the plugin is at least faster (because the implementation above creates a temporary file per code block) and can be more precise about line number and column of the violation. This is why I am skeptical about adding it into [flakehell](https://github.com/life4/flakehell/) since it would significantly affect performance.

## Things to care

There are few things to be careful about:

1. `ipython` code blocks with junk like `In [1]: `
1. `pycon` code blocks with a copy-pasted interactive shell session.
1. Non-python code-blocks.
1. Not wrapped doctests (like in all [doctest documentation](https://docs.python.org/3/library/doctest.html) examples)
1. Output from `pycon` and `doctest` blocks must be removed.
1. Markdown docstrings.
1. Correct line numbers and column numbers.

So, it is challenging but "something is better than nothing". Hence I'd propose to validate only fare `python` RST blocks and silently suppress invalid syntax.

**Comment by sobolevn** [comment]
It would be super hard. I am going to say that it is out of scope of this project.
But, I love the idea ❤️
