### ISSUE TITLE
False positive UselessContinueViolation

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#1438]
# Bug report

## What's wrong

```python
def func(obj_iterable) -> Optional[str]:
    for some_obj in obj_iterable:
        try:
            return do_smth(some_obj)
        except Exception:
            continue
    return None

WPS327 Found useless `continue` at the end of the loop [wemake-python-styleguide]
  for some_obj in obj_iterable:
  ^
```

## How is that should be

Not sure is it a bug or on purpose?

For me, it's valid function if I don't care about intermediate results of `do_smth(some_obj)`

**Comment by sobolevn** [comment]
`with suppress(Exception):`

**Comment by AlwxSin** [comment]
@sobolevn It's a great solution. And I'm pretty sure, that I saw it somewhere in other violations. ow about add this case to WPS327 documentation?

**Comment by sobolevn** [comment]
Sure!
