### ISSUE TITLE
WPS436 for current project's module

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1441]
I'm getting `WPS436 Found protected module import: _localdev` when importing a module in my own project.

I'm not sure if I'm just missing a config option that wemake uses, or if this is something that should be added. e.g. flake8-import-order uses the `application-import-names` option to specify import names for the current project.
    So, I'd expect this violation to be ignored for any imports under any of those names. If there's no option already existing in wemake, then perhaps it should just reuse that option.

**Comment by sobolevn** [comment]
Can you please specify how your file tree looks like? I don't quite get what structure do you have.

**Comment by Dreamsorcerer** [comment]
So, it looks like my_application/*.py, then files are imported with `from my_application._localdev import something` or similar.

**Comment by sobolevn** [comment]
Oh, I see. I have the same problem in `returns`: https://github.com/dry-python/returns/tree/master/returns/_generated

Currently, I don't have any ideas on how to fix it. Config option might do the trick.

**Comment by Dreamsorcerer** [comment]
Yep, as I mentioned flake8-import-order uses that config option to specify import names for the project. i.e. `application-import-names = my_application`.
https://github.com/PyCQA/flake8-import-order#configuration

**Comment by sobolevn** [comment]
We will use `pylint` + `ruff` for that.
