### ISSUE TITLE
WPS229 exception for CancelledError

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1459]
What do you think about ignoring WPS229 when only catching `asyncio.CancelledError`?

The point of this rule is to minimise the amount of code being tested that might raise an exception. However, in this case the exception is not coming from the code inside the try block, but being injected from outside the coroutine. Therefore the exception needs to be caught over a more general area.

**Comment by sobolevn** [comment]
Then yes, you can use `noqa` there. Great use-case for it! 👍

**Comment by sobolevn** [comment]
One can also use `with supress(CancelledError):`

**Comment by Dreamsorcerer** [comment]
Not if you need to handle the event. It just feels to me like this exception could be whitelisted for this rule.
