### ISSUE TITLE
Accessing my own protected modules

### ISSUE THREAD

**Issue by cbows** [wemake-services/wemake-python-styleguide#1481]
# Bug report

## What's wrong

I am developing a package and have some protected modules I don't want to expose in the public API, but only use them internally. However, when I import my own protected modules, I get WPS436 (protected module import).

## How is that should be

It should be fine to work with your own protected modules.

## System info
I am using wemake-python-styleguide 0.14.0

**Comment by Dreamsorcerer** [comment]
Duplicate of #1441
