### ISSUE TITLE
Annotations complexity exception on Literal['']

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1483]
I think you've used the flake8-annotations-complexity code in this project. I didn't realise that, and had it installed additionally.

I found an error with flake8-annotations-complexity when using Literal with an empty string. After getting that fixed, I found I had the same error again in wemake.

Fix (and test) is at: https://github.com/best-doctor/flake8-annotations-complexity/commit/7c1b0af4b479ccf4a83d9e3baebc78e792f92359

**Comment by sobolevn** [comment]
@Dreamsorcerer pr is welcome!
