### ISSUE TITLE
Bump flake8-isort min version to 3.0.1

### ISSUE THREAD

**Issue by webknjaz** [wemake-services/wemake-python-styleguide#1500]
After the release of isort==5.0.0, flake8-isort stopped working: https://github.com/gforcada/flake8-isort/issues/88.

The flake8-isort==3.0.1 patches this by limiting the isort version to lower than 5 in its dependencies: https://github.com/gforcada//pull/89. I think, this dist should set `flake8-isort >=3.0.1, <4` in the install requirements.

**Comment by Dreamsorcerer** [comment]
You added the help wanted tag without any explanation. Is there something more complicated than just changing the version number?

Opened a PR that just bumps the version number.

**Comment by Dreamsorcerer** [comment]
Though, I am a little confused why that file is already `<4`, yet the pip package installs `<3`.

**Comment by sobolevn** [comment]
> You added the help wanted tag without any explanation. Is there something more complicated than just changing the version number?

Nope, there's nothing more than a version bump. I just don't have the time right now to work on this.
(All my spare time goes into https://github.com/dry-python/returns/pull/446)

**Comment by Dreamsorcerer** [comment]
OK, cool. This needs a new release on pyPI though. The current package is completely broken if you just install or upgrade currently (without manually pinning isort).

**Comment by sobolevn** [comment]
I will release `0.15.1` tomorrow. Thanks a lot, @Dreamsorcerer! 👍

**Comment by CodingKanin** [comment]
@sobolevn was 0.15.1 released?

**Comment by sobolevn** [comment]
Nope, sorry! I forgot about it.

**Comment by CodingKanin** [comment]
Would it be possible to get that released? My GitHub action checks have been failing haha.

**Comment by sobolevn** [comment]
10 minutes 🕐

**Comment by webknjaz** [comment]
:alarm_clock:

**Comment by sobolevn** [comment]
Oh shii, today is not my `git` day. I have placed the commit in the wrong place. https://github.com/wemake-services/wemake-python-styleguide/commit/8513bcef5585debe8d97c473dfc53961c25cc154

I will try to insert it right after `0.14.0` tag now.

**Comment by sobolevn** [comment]
So, I have released a new version with just one this fix: https://pypi.org/project/wemake-python-styleguide/0.14.1/

```diff
» git diff
──────────────────────────────────────────────────────────────────────────────────────
modified: pyproject.toml
──────────────────────────────────────────────────────────────────────────────────────
@ pyproject.toml:12 @ style = "styles/nitpick-style-wemake.toml"

[tool.poetry]
name = "wemake-python-styleguide"
version = "0.14.0"
version = "0.14.1"
description = "The strictest and most opinionated python linter ever"

license = "MIT"
@ pyproject.toml:70 @ flake8-docstrings = "^1.3.1"
flake8-string-format = "^0.2"
flake8-bugbear = "^19.3"
flake8-debugger = "^3.1"
flake8-isort = "^2.9.0"
flake8-isort = ">=3.0.1,<4"
flake8-eradicate = "^0.3"
flake8-bandit = "^2.1"
flake8-broken-line = "^0.2"
```

I will now have to think about possiblities of moving this commit into the right place. 

Thanks a lot for the reminder! 👍

**Comment by CodingKanin** [comment]
So I would access this under `- uses: wemake-services/wemake-python-styleguide@0.14.1`?

**Comment by sobolevn** [comment]
`docker` image is on its way, it needs a tag to be in-place.

**Comment by sobolevn** [comment]
I have deleted all the mess, let's try one more time. Any suggestions?
1. I don't want to do 114 manual rebase `rm poetry.lock && poetry lock && git add poetry.lock && git rebase --continue`
2. Other methods don't seem to work (at least with my set of skills)

**Comment by sobolevn** [comment]
I had to rewrite the whole hostory to get this merged: https://github.com/wemake-services/wemake-python-styleguide/commit/8068e6634aaacf1eecba3f27a529213df3bd6284

The process is clearly broken, we need to follow some other process next time. I cannot waste 2 hours of my time on releasing a bug fix. Sad that this happened! Sorry! 
<img width="1230" alt="Снимок экрана 2020-07-29 в 19 46 41" src="https://user-images.githubusercontent.com/4660275/88828684-42ab0e80-d1d4-11ea-8181-8475978117ca.png">

**Comment by CodingKanin** [comment]
Thank you for taking the time to do it! Hope you get it solved soon

**Comment by sobolevn** [comment]
Github Action is also published: https://github.com/wemake-services/wemake-python-styleguide/releases/tag/0.14.1

**Comment by owodunni** [comment]
Great job @sobolevn, thank you for taking the time to fix this!

**Comment by webartifex** [comment]
Is this really solved?

I have wemake-python-styleguide 0.14.1 installed and according to poetry it blocks me from adding isort ^5.0.0

**Comment by sobolevn** [comment]
@webartifex yes, that's how `flake-isort` solves this issue for now. Because `isort@5` has different public API. 
You can track this issue: https://github.com/gforcada/flake8-isort/issues/88
