### ISSUE TITLE
WPS510 allow generator expressions

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1516]
WPS510 appears on generator expressions, but converting these to sets would make the code less efficient.
e.g.
`x in (calc(y) for y in something)`
is more efficient than the equivalent set:
`x in {calc(y) for y in something}`
As the set approach will require iterating through everything and creating the set object.

**Comment by orsinium** [comment]
Try `any(calc(y) == x for y in something)` instead.

**Comment by Dreamsorcerer** [comment]
Good idea. Not sure if that invalidates this bug or not, I'll let someone else make that call.

**Comment by webknjaz** [comment]
I think that the use of `any()` and `all()` makes the intent of the code more explicit.

**Comment by orsinium** [comment]
Thank you all! I think the case is solved. Let's close the issue :)

![image](https://user-images.githubusercontent.com/9638362/89659689-81c21980-d8d0-11ea-8331-c625f3f540b8.png)
