### ISSUE TITLE
Use windows CI as well

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#152]
@lk-geimfari can you please help me with this one?

I have never tried to enable windows CI and I am pretty sure it will have issues.
But, you somehow managed to get this working with `mimesis`.

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/pull/154

**Comment by sobolevn** [comment]
@lk-geimfari it should be working now. I have several questions:

1. can you see this page? https://ci.appveyor.com/project/sobolevn/wemake-python-styleguide
2. can you please trigger a new build with any pr? it should be working, I guess

**Comment by sobolevn** [comment]
Now I have two projects somehow: https://ci.appveyor.com/project/wemake-services/wemake-python-styleguid

I am not sure about which one is the correct one.

**Comment by lk-geimfari** [comment]
1. Nope, unfortunately I've missed it in my notifications. I will check it.
2. Done!
