### ISSUE TITLE
Forbid `raise Exception`

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1523]
# Rule request

## Thesis

Forbid to raise `Exception` or `BaseException`

```python
# bad
raise Exception
raise Exception("user not found")
raise BaseException
raise BaseException("user not found")

# good
raise UserNotFoundError
raise UserNotFoundError("cannot find user with the given id")
```

## Reasoning

Bare exception hard to catch and when you catch them you can suppress something else.

On [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html#bltin-exceptions):

> The built-in exceptions listed below can be generated by the interpreter or built-in functions...

> User code can raise built-in exceptions. This can be used to test an exception handler or to report an error condition “just like” the situation in which the interpreter raises the same exception; but beware that there is nothing to prevent user code from raising an inappropriate error.

On [User-defined Exceptions](https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions):

> When creating a module that can raise several distinct errors, a common practice is to create a base class for exceptions defined by that module, and subclass that to create specific exception classes for different error conditions.

**Comment by orsinium** [comment]
Also, raising any built-in exceptions, like `ValueError`, isn't a good idea. However, I think forbidding it would be too strict.

**Comment by sobolevn** [comment]
Yes, I agree.

**Comment by hhsdev** [comment]
Hey, can I take this one?

**Comment by sobolevn** [comment]
Sure! Thank you! 👍

**Comment by hhsdev** [comment]
Digging through the code, I found that there's already a [rule in place](https://github.com/wemake-services/wemake-python-styleguide/blob/c19bc17a12b1adfe8b32ed050c77385edf228d57/wemake_python_styleguide/violations/best_practices.py#L988) forbidding `raise BaseException`. I guess I'll just extend that to forbid `raise Exception` as well.

**Comment by sobolevn** [comment]
The rule you've mention is about catching. This one is about raising.

**Comment by hhsdev** [comment]
@orsinium @sobolevn Shouldn't this be closed since the PR is merged?
