### ISSUE TITLE
Custom exceptions must end with `Error`

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1524]
# Rule request

## Thesis

Custom exception class name must end with `Error`:

```
# bad
class UserNotFound(Exception):
    pass

# good
class UserNotFoundError(Exception):
    pass

class UserNotFoundError(ValueError):
    pass
```

## Reasoning

This is a convention which stdlib follows and documentation recommends to follow for custom exceptions as well:

> Most exceptions are defined with names that end in “Error”, similar to the naming of the standard exceptions.
> - https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions

**Comment by sobolevn** [comment]
We would have problems here.


```python
class First(Exception): ...  # detected

class SecondException(First): ...  # ignored
```

Let's leave it for `typed-linter`.

**Comment by orsinium** [comment]
I think "cover only some cases" is ok. We want to be at least good, not necessarily perfect.
