### ISSUE TITLE
Add Exceptions for String Constant Overuse

### ISSUE THREAD

**Issue by webartifex** [wemake-services/wemake-python-styleguide#1534]
# Rule request

I feel it would be good to be able to declare exceptions for WPS226

## Thesis / Reasoning

In a file on a current project, I tend to use `" ".join(iterable)` a lot.
It feels unnatural to declare a CONSTANT for that.
Also, I don't think it is good in this case to disable WPS226 for the entire file as there could be other common string constants.

Alternative: Excluse `" "`, `""`, "`\n"` & friends from this by default.

**Comment by orsinium** [comment]
I'm for the last proposed solution 👍 No harm in using these strings in-place. They can be excluded onthe wps level by default.

**Comment by theoden-dd** [comment]
+1. Had a similar case with `dict.get(field, '')` used for several fields.

Looks like exclusions to the magic numbers (WPS432), which are reasonable, too.

**Comment by sumeshpradhan** [comment]
Hi, I would like to help.

**Comment by sobolevn** [comment]
Hi, @sumeshpradhan! Thanks a lot!

**Comment by lensvol** [comment]
Can I take this over?
