### ISSUE TITLE
Bump flake8-isort max version to 5

### ISSUE THREAD

**Issue by webknjaz** [wemake-services/wemake-python-styleguide#1543]
This is basically a follow-up for https://github.com/wemake-services/wemake-python-styleguide/issues/1500.

According to https://github.com/gforcada/flake8-isort/pull/92#issuecomment-670480643, `flake8-isort==4.0.0a0` is the first version to implement the compatibility with `isort>=5`.

They encourage everyone to battle-test the pre-release and a few folks have already reported it working well.

It's time to relax the upper bound of the dependency in this project so that it's possible to pull-in the fixed version of the library. (while in alpha, folks will still have to opt-in to install a pre-release explicitly in their deps)

**Comment by Dreamsorcerer** [comment]
Looks like this has already been done on master: https://github.com/wemake-services/wemake-python-styleguide/commit/451c8d1545fdee90527ed51d4dea66a0d08e4627

**Comment by sobolevn** [comment]
Yes! 👍
