### ISSUE TITLE
WPS350 issue with PEP465 @ operator

### ISSUE THREAD

**Issue by braniii** [wemake-services/wemake-python-styleguide#1572]
In [PEP465](https://www.python.org/dev/peps/pep-0465/) the @ operator was introduced for matrix multiplication. Using it as followed raises a WPS350 warning, e.g.,
```
import numpy as np

a = np.arange(9).reshape(3, 3)
a = a @ a
```
Even though, the recommended short notation `a @= a` is not defined in numpy, see
```
>>> a @= a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: In-place matrix multiplication is not (yet) supported. Use 'a = a @ b' instead of 'a @= b'.
```

Hence, I guess a WPS350 should exclude the @ operator?
Thank you for your package. It is definitely one of the most helpful ones.

**Comment by orsinium** [comment]
Related: https://github.com/numpy/numpy/pull/6000

**Comment by sobolevn** [comment]
It is a issue of `numpy`, not `wps`.
This also looks like a perfectly valid use-case to switch off this rule or use `noqa`.
