### ISSUE TITLE
Set some dependencies as "extras"

### ISSUE THREAD

**Issue by pawamoy** [wemake-services/wemake-python-styleguide#1581]
I'm using Black to autoformat code in my project. I'm also writing docstrings in Markdown.

The following flake8 plugins are therefore useless (or even incompatible) for my use-case.

- flake8-brokenline
- flake8-commas
- flake8-quotes
- flake8-rst-docstrings

Would you consider setting these as `extras` so I can choose not to install them when installing `wemake-python-styleguide`?

Thanks for the great project 🙂

**Comment by sobolevn** [comment]
Nope, this is clearly out of scope of our project. 

Thanks a lot for the idea though!

**Comment by pawamoy** [comment]
Fair enough, thank you for the quick answer :smile:

**Comment by pawamoy** [comment]
I've forked the project here: https://github.com/pawamoy/wps-light
It's the same thing (and will always stay the same), but without the extra flake8 plugins :slightly_smiling_face:

**Comment by sobolevn** [comment]
@pawamoy awesome! Can you please send a PR to the docs with the link?

**Comment by pawamoy** [comment]
Sure! Note that I will only publish it when you release 0.15.2 :slightly_smiling_face:

**Comment by pawamoy** [comment]
Where would you like to see that link? "Extras" does not seem like the right place:

> There are some tools that are out of scope of this linter

The home page would be a bit pretentious :sweat_smile:

**Comment by sobolevn** [comment]
Maybe https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/plugins.html ?
