### ISSUE TITLE
Accept flake8-isort version up to 4.x

### ISSUE THREAD

**Issue by pawamoy** [wemake-services/wemake-python-styleguide#1584]
Version 4.0.0 was released about a month ago: https://github.com/gforcada/flake8-isort/releases

Could you increase the range of accepted versions for flake8-isort? Thanks! I can send a PR if needed.

**Comment by pawamoy** [comment]
Oh, my bad, I see you already accept version <5. Maybe you just need to release a new version?

**Comment by sobolevn** [comment]
> Maybe you just need to release a new version?

😆 

That's something I am going to work on! Soon!

**Comment by sobolevn** [comment]
> I'm not sure how you took it, it was not my intention to be offensive or anything 

No, no! Everything is cool! No worries! 👍

**Comment by barbossa** [comment]
> That's something I am going to work on! Soon!

Thank you for your hard work on the new release.

I am excited waiting for the new release, including the new version of isort and flake8-isort. Since I've tried to update isort to 5.6.4 and I cannot due to unresolved dependencies in wemake-python-styleguide relates to old flake8-isort

**Comment by ahobsonsayers** [comment]
Im also excited for the new release. Is there a blocker to release @sobolevn that possible i can aid with. Id love to be able to use isort 5 as it is a huge improvement over 4

**Comment by sobolevn** [comment]
I will make a new release soon 🙂 

I need to rebase all PRs from opened and merge them.
See https://github.com/wemake-services/wemake-python-styleguide/issues?q=is%3Apr+is%3Aopen+label%3A%22on+hold%22

After that - I will make a release!
