### ISSUE TITLE
WPS515 has a wrong description

### ISSUE THREAD

**Issue by Jrryy** [wemake-services/wemake-python-styleguide#1595]
# Bug report

## What's wrong

The description of WPS515 says:

>  Forbids to use `open()` with a context manager.

But the violation was made for the opposite reason.

## How is that should be

It should say:

> Forbids to use `open()` **without** a context manager.

**Comment by sobolevn** [comment]
@Jrryy whoops! Can you please send a PR with the fix? 🙂
