### ISSUE TITLE
WPS453 has wrong line (row) number

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1621]
# Bug report

## What's wrong

WPS453 ("Found executable mismatch: shebang is present but the file is not executable") points to `0:1`.

Can be reproduced running against the following file:
https://github.com/life4/flakehell/blob/master/example.py

Or online on https://flakehell.orsinium.dev/

## How is that should be

1. The row number cannot be less than 1.
1. The row number should point to the incorrect shebang.

## System information

Not relevant

**Comment by sobolevn** [comment]
Yes, this is correct. Because I don't want people to use `noqa` for this rule.

**Comment by orsinium** [comment]
> Yes, this is correct.

I think this can lead to unforeseen bugs.

1. It can be ignored by some IDEs since it points to no line.
1. It is documented as starting counting from 1: https://github.com/PyCQA/flake8/blob/master/src/flake8/style_guide.py#L408-L410
1. It breaks indentation in the built-in flake8 formatter: https://github.com/PyCQA/flake8/blob/master/src/flake8/formatting/base.py#L176-L179

> I don't want people to use noqa for this rule.

1. You already have a check for noqa count over a file.
1. Any violation always can be ignored in the config, via CLI, or as [module-level noqa](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#ignoring-entire-files).
1. Linter should guide, not force. And even when this is a way to enforce rules in a team, every `noqa` should be checked on the review. This point is opinionated but I'm not sure if we should intentionally take from users the way to ignore violations when they find it sufficient.
