### ISSUE TITLE
Forbid assigning to a slice

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1629]
# Rule request

## Thesis

There might be some crazy examples of mutation, when assigning to a slice:

```python
my_list = [1, 2, 3]
my_list[0:3] = [0, 0, 0]
```

So, let's ban this.

However, we still allow regular index assignments:

```python
my_list = [1, 2, 3]
my_list[0] = [0, 0, 0]
```

Is ok.

**Comment by parzuko** [comment]
hey, can i take this issue ?

**Comment by sobolevn** [comment]
Yes, thanks a lot!

**Comment by sudo-k-runner** [comment]
@parzuko are you working on this? if not would like to take this up.

**Comment by sobolevn** [comment]
@sudo-k-runner feel free to take it 🙂

**Comment by sudo-k-runner** [comment]
@sobolevn cool! kinda new to this, so would be great if I can get some pointers. Thanks!

**Comment by sobolevn** [comment]
I recommed to start with our `CONTRIBUTING.md` and then ask any specific questions you have 👍

**Comment by sudo-k-runner** [comment]
sure thing! Thanks 👍
