### ISSUE TITLE
Return the boolean condition directly without using `if`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1638]
# Rule request

## Thesis

We need to track:

```python
    if cond:
        return True  # or False
    else:
        return False  # or True
```

and:

```python
    if cond:
        return True  # or False
    return False  # or True
```

Instead one should use:

```python
    return cond
```

Inspiration: https://github.com/MartinThoma/flake8-simplify/blob/master/flake8_simplify.py#L487

## Reasoning

We don't need extra conditions to this simple thing.

**Comment by iamlordutkarsh** [comment]
I want to work on this Can you assign me ??

**Comment by sobolevn** [comment]
Yes, sure! Thanks a lot!

**Comment by iamlordutkarsh** [comment]
Thanks Sir , I have one Question I have to change This in whole Repo ?

**Comment by sakshi-negi123** [comment]
please assign me

**Comment by sobolevn** [comment]
@iamlordutkarsh you have to write a linting rule for this 🙂 
We use `ast` module in python to achieve this.

Please, read our contributing guide: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md

**Comment by iamlordutkarsh** [comment]
Thanks @sobolevn

**Comment by iamlordutkarsh** [comment]
Can You assign it to someone else

**Comment by sobolevn** [comment]
Sure! @sakshi-negi123 you also wanted to work on it? Please, feel free.

**Comment by Jrryy** [comment]
I will be taking a look at this issue meanwhile. If it takes them too long to answer I offer myself to work on it.

**Comment by sobolevn** [comment]
Thanks a lot, @Jrryy!

**Comment by Jrryy** [comment]
I'd like to ask, should this go into the Best practices section, or the Refactoring section? It looks better in Refactoring to me but I'd like to know your opinion

**Comment by sobolevn** [comment]
Refactoring looks like a better fit 🤔

> I've just noticed that there's already something similar (SimplifiableIfViolation)

Sure!
