### ISSUE TITLE
User should not configure anything other than the complexity options

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#164]
We should provide default options for `isort` and `flake8`.

Related:
1. https://github.com/gforcada/flake8-isort/issues/63

**Comment by sobolevn** [comment]
See `--append-config` option that we can monkey-patch.

**Comment by sobolevn** [comment]
Closed by a misclick.

**Comment by AlwxSin** [comment]
That's will force me to not use `wps`.

This linter is good, very good in comparison with naked flake8 or even with flake8 with plugins. But several rules are very opinionated. And it's good I can disable them, just a few.

**Comment by sobolevn** [comment]
This is not the point of this issue, I am only talking about configuration options like `quotes`, `max-line-length`, `isort` config and so on.

It is not related to `ignore`, `per-file-ignores` or complexity rules.
We also use these settings on literally every project: https://github.com/wemake-services/wemake-python-styleguide/blob/master/setup.cfg#L31-L41

**Comment by AlwxSin** [comment]
Ah, that's ok =)

**Comment by sobolevn** [comment]
For `isort` to work we can patch defaults: https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L76

It is safe, since any custom defined options will take priority over these values.

**Comment by sobolevn** [comment]
Related: https://gitlab.com/pycqa/flake8/issues/555

**Comment by sobolevn** [comment]
The obvious problem with patching `isort` config this way is that it won't work for autoformatter part. `isort filename.py` won't produce the same results.

I will look into plugin system of `isort`. Or ugly hacks 🙂

**Comment by sobolevn** [comment]
I guess we have found a solution: https://github.com/andreoliwa/nitpick

**Comment by andreoliwa** [comment]
> I guess we have found a solution: https://github.com/andreoliwa/nitpick

I'm glad `nitpick` has a practical use outside my own projects. 🙂
It's still beta and with rough edges though.
Let me know if you find more bugs.
