### ISSUE TITLE
WPS426 triggers on safe lambdas

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1689]
# Bug report

## What's wrong

```python
def _show_titles(number_of_posts: int) -> Sequence[FutureResultE[str]]:
    return [
        # Notice how easily we compose async and sync functions:
        _fetch_post(post_id).map(lambda post: post['title'])
        # TODO: try `for post_id in (2, 1, 0):` to see how async errors work
        for post_id in range(1, number_of_posts + 1)
    ]
```

Raises:

```
  32:9     WPS426 Found `lambda` in loop's body
  _fetch_post(post_id).map(lambda post: post['title'])
  ^
```

But it should not!

## How is that should be

Why? Because this `lambda` does not use `post_id` in its body. It is safe to be used.
So, if `lambda` uses only its args - we can allow it.

### flake8 information

Contents of `flake8 --bug-report`:

### pip information

Contents of `pip freeze`:

**Comment by HeroicHitesh** [comment]
@sobolevn I would love to work on it, I but would need some guidance. Currently going through this [guide](https://wemake-python-stylegui.de/en/latest/pages/api/contributing.html#tutorials). If there is something else I need to know beforehand, do let me know.

**Comment by sobolevn** [comment]
@HeroicHitesh you are more than welcome! You would need to implement a fix to our `ast` visitor. 
It should not be hard. 

I would probaly start with a failing test.

**Comment by jaydesl** [comment]
I'd like to pick this up, but I think some of the tests are in contradiction to this.

> if lambda uses only its args - we can allow it.

**These lambda functions use only their args but are considered wrong:**
https://github.com/wemake-services/wemake-python-styleguide/blob/ece40b94d7649cc30a3e8a896513719d28099aed/tests/test_visitors/test_ast/test_loops/test_loops/test_lambda_in_loop.py#L45

https://github.com/wemake-services/wemake-python-styleguide/blob/ece40b94d7649cc30a3e8a896513719d28099aed/tests/test_visitors/test_ast/test_loops/test_loops/test_lambda_in_loop.py#L50

https://github.com/wemake-services/wemake-python-styleguide/blob/ece40b94d7649cc30a3e8a896513719d28099aed/tests/test_visitors/test_ast/test_loops/test_loops/test_lambda_in_loop.py#L55

https://github.com/wemake-services/wemake-python-styleguide/blob/ece40b94d7649cc30a3e8a896513719d28099aed/tests/test_visitors/test_ast/test_loops/test_loops/test_lambda_in_loop.py#L27

**On the other hand, this lambda function uses a variable outside its scope and is considered correct:**
https://github.com/wemake-services/wemake-python-styleguide/blob/ece40b94d7649cc30a3e8a896513719d28099aed/tests/test_visitors/test_ast/test_loops/test_loops/test_lambda_in_loop.py#L83

Happy for me to change these tests when I implement the fix?

**Comment by sobolevn** [comment]
Yes, these tests should be changed! It was a bad idea to forbid all lambdas in a for loop for someone who loves functional programming 😆 

Please, feel free to change anything that is related to this task.

And thanks a lot for your help! 👍
