### ISSUE TITLE
Update reviewdog to 0.11

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1698]
We use `reviewdog@0.9`, but `0.11` is released.
https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md#v0110---2020-10-25

Related: https://github.com/wemake-services/wemake-python-styleguide/blob/master/Dockerfile#L24

**Comment by sobolevn** [comment]
@mgrachev maybe you want to contribute to our small project? 🙂

**Comment by mgrachev** [comment]
With pleasure 🙂

**Comment by sobolevn** [comment]
Thanks a lot! 👍
