### ISSUE TITLE
Set setup.py package version constraints

### ISSUE THREAD

**Issue by anatoly-scherbakov** [wemake-services/wemake-python-styleguide#1699]
# Rule request

If using `setup.py` in a Python project (not everyone is on Poetry just yet), it is easy to forget assign explicit version constraints for dependencies.

This may lead to suddenly broken system due to a dependency updated.

## Thesis

I suggest to throw an error if version constraint is not specified. For example:

```python
import setuptools

...

setuptools.setup(
   ...,
    install_requires=[
        'pydantic',  # bad
        'pydantic<1.7', # okay
        'pydantic==1.6.1', # good
        'something @ git+ssh://git@github.com/SomeWhere/something.git@3.1.32'  # okay
    ],
    extras_require={
        'dev': [
            'pip>=19.2.3',  # all right
            'flake8-isort<4,>=3.0.1',  # okay as well
        ],
    },
    ...
)

```

## Reasoning

If linter can point out these errors, it will be a reminder to specify version constraints, and thus — to prevent potential fragility in the project.

**Comment by sobolevn** [comment]
This seems like a very hard feature. But I will think about it! Thanks a lot! @anatoly-scherbakov

**Comment by sobolevn** [comment]
I think that it is better to create a separate plugin for `setup.py`, like `flake8-setuppy`.
Since we don't really use `setup.py ` and don't recommend anyone to use it - there would be no rules about it in WPS.

Thanks again for the idea 👍
