### ISSUE TITLE
Dependency "pluggy" may have a wrong hash in the lock file

### ISSUE THREAD

**Issue by vergeev** [wemake-services/wemake-python-styleguide#17]
When I do `pipenv install -d` on MacOS, the `pluggy=0.6.0` dependency isn't getting installed because of the wrong hash: `THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!`.

The package version `pipenv` tries to install is: `https://files.pythonhosted.org/packages/ba/65/ded3bc40bbf8d887f262f150fbe1ae6637765b5c9534bd55690ed2c0b0f7/pluggy-0.6.0-py3-none-any.whl`

The problem can be caused by `pipenv` itself (see https://github.com/pypa/pipenv/issues/210).

Since I'm not sure I'm asking to verify that on other platforms.

**Comment by sobolevn** [comment]
Yeap, that's a known problem. 

I plan to migrate to `poetry`. 
Are you interested in helping me with this one: #13

**Comment by vergeev** [comment]
I am! But I will not be able to start it until at least the next week. I'll let you know when I start working on it!

**Comment by vergeev** [comment]
I am! But I will not be able to start it until at least the next week. I'll let you know when I start working on it!

**Comment by sobolevn** [comment]
I am pretty sure, that I won't start working on it anytime soon.
