### ISSUE TITLE
Some errors were encountered when parsing the FUNDING.yml file

### ISSUE THREAD

**Issue by mgrachev** [wemake-services/wemake-python-styleguide#1701]
<img width="646" alt="sponsors" src="https://user-images.githubusercontent.com/700998/97337705-ac00f300-1891-11eb-93ff-75d690e1167b.png">

**Comment by sobolevn** [comment]
Oh, this is because I have disable wemake.services from Github Sponsors. 
Because I need a different Stripe account, which I don't have.

I will fix it someday! 

Thanks for reporting.

**Comment by mgrachev** [comment]
What do you think about setting up GitHub Sponsors via Open Collective?
https://docs.opencollective.com/help/collectives/github-sponsors

For example: https://opencollective.com/dotenv-linter

**Comment by sobolevn** [comment]
Yeap, that's exactly where I need one extra Stripe Account. Because, I run multiple Github Sponsor accounts and each of them requires a separate Stipe Account. Each Stripe account requires a separate mobile phone number. And I am out of numbers 😆

**Comment by sobolevn** [comment]
Finally! You can now use GitHub Sponsors: github.com/sponsors/wemake-services/
