### ISSUE TITLE
Describe how to use this project with Jupyter Notebooks

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1704]
I get a lot of questions from users that what to use `WPS` together with IPython Notebooks.
Currently, you cannot *just* use it with raw `flake8`.

You need extra tooling and some tweaks in the configuration I suppose.
So, we need to document how to use it.

We can create a new entry in our `Intergrations` section. https://github.com/wemake-services/wemake-python-styleguide/tree/master/docs/pages/usage/integrations

**Comment by orsinium** [comment]
For jupyterlab:
https://github.com/mlshapiro/jupyterlab-flake8

**Comment by orsinium** [comment]
And for CLI, flakehell supports ipynb:
https://flakehell.readthedocs.io/parsers.html

**Comment by MarcoGorelli** [comment]
Hi @sobolevn ,

We've released `nbqa` version 0.4.0, which has support for in-line magics. This should make it safe for use with `wemake-python-styleguide`.

Essentially, just as you would run `flake8 script.py`, you can ran `nqba flake8 notebook.ipynb`.

I've tested this out on a few notebooks, and it seems to work as expected. If you could verify this we would really appreciate it!

**Comment by sobolevn** [comment]
@MarcoGorelli awesome news! Do you want to contribute a test case for us and some docs on how to use your library?

**Comment by MarcoGorelli** [comment]
Sure!

Would you want a sample test notebook in `tests/data` and then a snapshot test? If so, I'll get a PR together over the weekend

**Comment by sobolevn** [comment]
Yes, `fixtures/` looks like a good place for a notebook itself: https://github.com/wemake-services/wemake-python-styleguide/tree/master/tests/fixtures

And then `snapshot` the result 👍 

Thanks!

**Comment by MarcoGorelli** [comment]
closed in #1798 ?  Looks like I'd forgotten the "closes #1704" tag there
