### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1708]
# Bug report

## What's wrong

[wemake-python-stylegui.de](https://wemake-python-stylegui.de/) is down: "Read time out".

![image](https://user-images.githubusercontent.com/9638362/97715103-46477d80-1ac2-11eb-8243-9526148b26ec.png)

**Comment by sobolevn** [comment]
Looks like readthedocs is down https://returns.readthedocs.io/

**Comment by sobolevn** [comment]
It is working again! 👍
