### ISSUE TITLE
Google Style Guide causes RST210 and RST213 violations

### ISSUE THREAD

**Issue by webartifex** [wemake-services/wemake-python-styleguide#1725]
# Bug report

## What's wrong

Google's Python Style Guide says "If a function accepts `*foo` (variable length argument lists) and/or `**bar` (arbitrary keyword arguments), they should be listed as *foo and **bar" ([source](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods)).

However, in doing so, RST210 and RST213 violations are triggered.

## How it should be

rst-docstrings should not complain about this if the "Google" format is chosen as docstring format.

### flake8 information

Contents of `flake8 --bug-report`:
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.6",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "black",
      "version": "0.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-annotations",
      "version": "2.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.5.5"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-expression-complexity",
      "version": "0.0.8"
    },
    {
      "is_local": false,
      "plugin": "flake8-pytest-style",
      "version": "1.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "3.0.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.9.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.12"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.14.1"
    }
  ],
  "version": "3.8.4"
}

### pip information

Contents of `pip freeze`:

alabaster @ file:///home/webartifex/.cache/pypoetry/artifacts/01/50/a4/e8f66b1cc7b3896e348a7976ec6390f61a7ed3cc0583b406c9a737955a/alabaster-0.7.12-py2.py3-none-any.whl
appdirs @ file:///home/webartifex/.cache/pypoetry/artifacts/68/c7/33/ef0f6af8d1aa906f1a5641762fe5d6f47d565c5a4b3482f1c6fb0f5f20/appdirs-1.4.4-py2.py3-none-any.whl
argcomplete @ file:///home/webartifex/.cache/pypoetry/artifacts/65/1e/2f/3b8c5ecbfabcad80cd5c8120a2ca2858375e631a483fac40665929026c/argcomplete-1.12.1-py2.py3-none-any.whl
astor @ file:///home/webartifex/.cache/pypoetry/artifacts/00/68/e3/b2c93c6b1eabbb453b7a288336d64a2bb9f32b6821173440843f97f64b/astor-0.8.1-py2.py3-none-any.whl
astpretty @ file:///home/webartifex/.cache/pypoetry/artifacts/83/99/79/50c12ac187b945583845c1f4ecdc16c094c85ec731069b3c3f91a6a0da/astpretty-2.0.0-py2.py3-none-any.whl
astroid @ file:///home/webartifex/.cache/pypoetry/artifacts/f2/ce/d2/b73c9288be1ba36cbe7ab09e2c1db6e0fd8a7ad637523ac33d89e39ee7/astroid-2.4.2-py3-none-any.whl
attrs @ file:///home/webartifex/.cache/pypoetry/artifacts/b7/28/6f/acdd2c0e759f1cda97abf00db7723a0ffb3a151696d8d96398aea16171/attrs-20.3.0-py2.py3-none-any.whl
autoflake @ file:///home/webartifex/.cache/pypoetry/artifacts/74/62/62/d251f3f370b78f07f784b7c0f5be17b5800f48099af9a6c9c0fc9bc508/autoflake-1.4.tar.gz
Babel @ file:///home/webartifex/.cache/pypoetry/artifacts/ff/50/c8/59488715be6e53024188713fe5f553c3c5cb8cf90d5cb67d99a4537a1d/Babel-2.8.0-py2.py3-none-any.whl
bandit @ file:///home/webartifex/.cache/pypoetry/artifacts/47/cd/d3/5a6d0033a8180d54f1386733bfc852e9af38065a6ac17167ef1d419519/bandit-1.6.2-py2.py3-none-any.whl
black @ file:///home/webartifex/.cache/pypoetry/artifacts/8e/1c/f2/290c174cd674671ed5f1224e5d124c64390744b035245ddb7e2bacc76f/black-19.10b0-py36-none-any.whl
certifi @ file:///home/webartifex/.cache/pypoetry/artifacts/30/e0/fe/02be0b0d7bf5e7da8f0584a43b64890d8956bd395d188597ed45f16834/certifi-2020.6.20-py2.py3-none-any.whl
cfgv @ file:///home/webartifex/.cache/pypoetry/artifacts/a3/13/f8/c0bb0b5fe71b290d196baea9d689e3742c03153db00e38c913ca8c9100/cfgv-3.2.0-py2.py3-none-any.whl
chardet @ file:///home/webartifex/.cache/pypoetry/artifacts/c2/02/35/0d93b80c730b360c5e3d9bdc1b8d1929dbd784ffa8e3db025c14c045e4/chardet-3.0.4-py2.py3-none-any.whl
click @ file:///home/webartifex/.cache/pypoetry/artifacts/30/bc/bf/e00ffd8f0edf0294942e70e80e42a839bd2649d2c5b864e6389e526d2a/click-7.1.2-py2.py3-none-any.whl
codecov @ file:///home/webartifex/.cache/pypoetry/artifacts/e9/7e/52/2e5d4c7760c53ac0127a9b5334142ee1287b44c3c8715f437e4a42880f/codecov-2.1.10-py2.py3-none-any.whl
colorlog @ file:///home/webartifex/.cache/pypoetry/artifacts/1e/42/78/8638afdf2826496ecbd7c12883889cba275e0aa09de86714fc3143a855/colorlog-4.5.0-py2.py3-none-any.whl
coverage @ file:///home/webartifex/.cache/pypoetry/artifacts/3a/91/54/2cf1dc70616c58be152f7d5c8a2d4e5a73c30c07a3dee33242ebf0bf2a/coverage-5.3-cp38-cp38-manylinux1_x86_64.whl
darglint @ file:///home/webartifex/.cache/pypoetry/artifacts/75/d3/fa/7f69c452fedb144eba1f91f7d8a347871b1b088288b7162abf65603901/darglint-1.5.5-py3-none-any.whl
distlib @ file:///home/webartifex/.cache/pypoetry/artifacts/05/ef/a8/cc6b58b48105b14323bce7de07ff1c0c4add12d6f53f688a46288bd686/distlib-0.3.1-py2.py3-none-any.whl
docutils @ file:///home/webartifex/.cache/pypoetry/artifacts/9e/78/f1/81f20d21f3ed304c86fa5394fadbb173e75ad363029a8fefa635dadf2e/docutils-0.16-py2.py3-none-any.whl
eradicate @ file:///home/webartifex/.cache/pypoetry/artifacts/d7/9d/a9/4eb3af3b79f810cc0b1b6f09395d9ee84772b603a8e8978e12b12717d2/eradicate-1.0.tar.gz
filelock @ file:///home/webartifex/.cache/pypoetry/artifacts/f4/78/c1/69555c3867649a2a5dac43f12a078830700480a49be273fb2de82be2ab/filelock-3.0.12-py3-none-any.whl
flake8 @ file:///home/webartifex/.cache/pypoetry/artifacts/5c/5b/91/23d9fee55905e042e829a14e2fa56ffd39c81246aba659e2840bab728b/flake8-3.8.4-py2.py3-none-any.whl
flake8-annotations @ file:///home/webartifex/.cache/pypoetry/artifacts/c9/c1/48/e83c87338ed750abb22b3c8c2c73013a850fc2e957bd91cfd38a703c91/flake8_annotations-2.4.1-py3-none-any.whl
flake8-bandit @ file:///home/webartifex/.cache/pypoetry/artifacts/cc/6d/cf/94dc0d884687c0e10baebe95be53977448e1b59d7ad05e41a0f046cd7e/flake8_bandit-2.1.2.tar.gz
flake8-black @ file:///home/webartifex/.cache/pypoetry/artifacts/8f/31/af/88bf050b28749ffc11defbf11739754c5d51c54efdb45c613f7fa8772a/flake8-black-0.2.1.tar.gz
flake8-broken-line @ file:///home/webartifex/.cache/pypoetry/artifacts/b6/72/5f/b138cf8858a3bb7411d5443831c6a3d9c2170f1a4fb01b07a96a33b801/flake8_broken_line-0.2.1-py3-none-any.whl
flake8-bugbear @ file:///home/webartifex/.cache/pypoetry/artifacts/2d/c4/51/6e0f2c02d3e6a846fd30eded9b747688cecf8e55e1c9280ab30a793c04/flake8_bugbear-19.8.0-py35.py36.py37-none-any.whl
flake8-commas @ file:///home/webartifex/.cache/pypoetry/artifacts/b7/aa/76/e620a68b0be70f4132be94bfbfdacb20b16c060174b33dc856818db92d/flake8_commas-2.0.0-py2.py3-none-any.whl
flake8-comprehensions @ file:///home/webartifex/.cache/pypoetry/artifacts/22/08/cf/e2489bbc8810faf889c7d3b805e312583d8ad4992dc695e97dfa258126/flake8_comprehensions-3.3.0-py3-none-any.whl
flake8-debugger @ file:///home/webartifex/.cache/pypoetry/artifacts/da/2c/e3/d62fd2fc55b1f63fccb2997d98af07223eae27b3216cdb75fa9975b398/flake8-debugger-3.2.1.tar.gz
flake8-docstrings @ file:///home/webartifex/.cache/pypoetry/artifacts/14/46/f1/42800107fb2815121aebf831e269f0af48a45c669a24dbcec60fbbac9f/flake8_docstrings-1.5.0-py2.py3-none-any.whl
flake8-eradicate @ file:///home/webartifex/.cache/pypoetry/artifacts/ad/cc/3b/7c679e5a37dbe9e9d3b056d2e5ee8e3dceac70460c3edcb852b0c650f4/flake8_eradicate-0.3.0-py3-none-any.whl
flake8-expression-complexity @ file:///home/webartifex/.cache/pypoetry/artifacts/bb/00/32/1a20376732a96c7c4cb87dafaab31ba4984c299a0bb80c930ea65fa32e/flake8_expression_complexity-0.0.8.tar.gz
flake8-isort @ file:///home/webartifex/.cache/pypoetry/artifacts/56/70/ee/b8f0228abc9e3e9ff24faa6cf960fe806dc20e1a9d327835b90545585a/flake8_isort-3.0.1-py2.py3-none-any.whl
flake8-plugin-utils @ file:///home/webartifex/.cache/pypoetry/artifacts/99/73/fc/1fd22f303405c472d0dd047300335cdbbcc598f106b402ce1176be733b/flake8_plugin_utils-1.3.1-py3-none-any.whl
flake8-polyfill @ file:///home/webartifex/.cache/pypoetry/artifacts/37/d4/b9/446f3fe801eea4de2fdff2cd1e0be3fa836d08c04d62174d4ec65113f3/flake8_polyfill-1.0.2-py2.py3-none-any.whl
flake8-pytest-style @ file:///home/webartifex/.cache/pypoetry/artifacts/b9/91/aa/24d42f27861d7e5a75ff711270a98440f637f704a85bc7e67fbaa683c9/flake8_pytest_style-1.3.0-py3-none-any.whl
flake8-quotes @ file:///home/webartifex/.cache/pypoetry/artifacts/fb/94/4e/57a6dae12a87b982e4d35a28f9336ab761e0333a4be207d2d9f3ff5c99/flake8-quotes-2.1.2.tar.gz
flake8-rst-docstrings @ file:///home/webartifex/.cache/pypoetry/artifacts/a2/a0/d5/c25770b5624cb722839214583bf7156c6716d34aeb62ff9ee9d96ed7e6/flake8-rst-docstrings-0.0.12.tar.gz
flake8-string-format @ file:///home/webartifex/.cache/pypoetry/artifacts/54/fe/a4/42804621e559c82bc460b782340c42d279633fb413fe8911e1c45707fc/flake8_string_format-0.2.3-py2.py3-none-any.whl
gitdb @ file:///home/webartifex/.cache/pypoetry/artifacts/45/a9/94/d73ced00c6cf302a2e08bedd4f10d3424342b7a8a2fae6e4ccb7276641/gitdb-4.0.5-py3-none-any.whl
GitPython @ file:///home/webartifex/.cache/pypoetry/artifacts/bb/7d/e3/03ce0e77da368e61f7ddc587b791b0272880265992f05053a40cb306e3/GitPython-3.1.11-py3-none-any.whl
identify @ file:///home/webartifex/.cache/pypoetry/artifacts/c2/72/f0/e25a22eddff10e4ae2266e784139047f4109caec463c4b65abd49ee4b4/identify-1.5.9-py2.py3-none-any.whl
idna @ file:///home/webartifex/.cache/pypoetry/artifacts/9e/f9/03/6066b92d35486e7f0d4f310126e3c60a6619726e43ef98e32e105b5c52/idna-2.10-py2.py3-none-any.whl
imagesize @ file:///home/webartifex/.cache/pypoetry/artifacts/0b/69/4e/8e64ed37efc2f5438fce870c94736b2e1a21bc4cb0c286f936de14357b/imagesize-1.2.0-py2.py3-none-any.whl
iniconfig @ file:///home/webartifex/.cache/pypoetry/artifacts/ac/f9/da/e990ffcd9ec361a68676a5916e391286e1ea5d1b8907ae887e141a71f5/iniconfig-1.1.1-py2.py3-none-any.whl
isort @ file:///home/webartifex/.cache/pypoetry/artifacts/6e/4e/fa/c1a31b7a066920f2d2cebcdf14f804e3f48fc87e5d4c85ae4805b246b2/isort-4.3.21-py2.py3-none-any.whl
Jinja2 @ file:///home/webartifex/.cache/pypoetry/artifacts/a0/8d/d0/dce9f8c04cdcf457adcd58424bdacab8a7a2c3c42854fd3c0d2135046e/Jinja2-2.11.2-py2.py3-none-any.whl
lalib==0.2.0.dev0
lazy-object-proxy @ file:///home/webartifex/.cache/pypoetry/artifacts/6a/b4/9a/8a9fb199423a4845324dada8e215f55ff61e1c2f24cc15b3ea3399468d/lazy_object_proxy-1.4.3-cp38-cp38-manylinux1_x86_64.whl
MarkupSafe @ file:///home/webartifex/.cache/pypoetry/artifacts/11/bd/ad/5012ca1b0f41b786ac09ee7c185c0383d54f89f9d6f87e13a22b085a4f/MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl
mccabe @ file:///home/webartifex/.cache/pypoetry/artifacts/37/6e/69/4a33a4d6c80c775b1ee205face2c6e07b762c8602bb0f0d236ebe790c5/mccabe-0.6.1-py2.py3-none-any.whl
mypy @ file:///home/webartifex/.cache/pypoetry/artifacts/a0/40/de/609eb6ab07b140d3ba845e45394b031652f807f60c416393cd9da661f7/mypy-0.782-cp38-cp38-manylinux1_x86_64.whl
mypy-extensions @ file:///home/webartifex/.cache/pypoetry/artifacts/b6/a0/b0/a5dc9acd6fd12aba308634f21bb7cf0571448f20848797d7ecb327aa12/mypy_extensions-0.4.3-py2.py3-none-any.whl
nodeenv @ file:///home/webartifex/.cache/pypoetry/artifacts/72/5e/9d/1740227b4d8dad9da164470c03018a34f4aad0cc1e027b6c93d2ac6115/nodeenv-1.5.0-py2.py3-none-any.whl
nox @ file:///home/webartifex/.cache/pypoetry/artifacts/cb/24/01/323c41ae8b21f09672932ba3ca83cbf962c9fd22e7b4aee2468aff7046/nox-2020.8.22-py3-none-any.whl
packaging @ file:///home/webartifex/.cache/pypoetry/artifacts/09/cd/29/a435224f3203dfba4af491065632910aadb6f3ddd87ce3c6590ac29e7a/packaging-20.4-py2.py3-none-any.whl
pathspec @ file:///home/webartifex/.cache/pypoetry/artifacts/5d/98/c8/c7cd4decd7943aa5647824d8553b40e86f4e2ef814ca2a4e73ee708f7f/pathspec-0.8.1-py2.py3-none-any.whl
pbr @ file:///home/webartifex/.cache/pypoetry/artifacts/85/81/cf/9255f6df466921f8291c85ab33df01caeda1916c2745a5071ce06a963f/pbr-5.5.1-py2.py3-none-any.whl
pep8-naming @ file:///home/webartifex/.cache/pypoetry/artifacts/ce/6c/45/d883218e7ee597f1796a1593478f89443587aea185b8a63a863060d473/pep8_naming-0.9.1-py2.py3-none-any.whl
pluggy @ file:///home/webartifex/.cache/pypoetry/artifacts/9c/e5/0b/2d64d03361a081edeb5d2ec5f286ccf9719587781fbf6822e1b6384c27/pluggy-0.13.1-py2.py3-none-any.whl
pre-commit @ file:///home/webartifex/.cache/pypoetry/artifacts/7e/fa/7d/1e68ba8ce8eef50de8ad2200f52fdc400230b90794cc3e5fd9a6f3fb51/pre_commit-2.8.2-py2.py3-none-any.whl
py @ file:///home/webartifex/.cache/pypoetry/artifacts/f5/51/7d/d8aec03f59299351465053794c7b1f0e0e7a918e4a67911664f83929af/py-1.9.0-py2.py3-none-any.whl
pycodestyle @ file:///home/webartifex/.cache/pypoetry/artifacts/01/f4/cf/c7e34cb76e03e95d9eff28af16fe09ee8edd01cc985fc2b88453b6d311/pycodestyle-2.6.0-py2.py3-none-any.whl
pydocstyle @ file:///home/webartifex/.cache/pypoetry/artifacts/a4/ef/58/498033174cb8c68875036ec5d8a3d9d2e169c51bec9d35866bd62ff5ac/pydocstyle-5.1.1-py3-none-any.whl
pyflakes @ file:///home/webartifex/.cache/pypoetry/artifacts/da/83/11/1e9a80c39638c6967e9b1117b17d8ec5f723ddd0a88251cc08dc0807b0/pyflakes-2.2.0-py2.py3-none-any.whl
Pygments @ file:///home/webartifex/.cache/pypoetry/artifacts/d0/37/a5/bdd862c4f6538fafaf79d37ec67fd2337ac277eef4817a8ecd525570c9/Pygments-2.7.2-py3-none-any.whl
pylint @ file:///home/webartifex/.cache/pypoetry/artifacts/c2/d4/ba/db8a8147674104ef7fadb040179d5254b7724b1b2c0b65b91e998b884d/pylint-2.6.0-py3-none-any.whl
pyparsing @ file:///home/webartifex/.cache/pypoetry/artifacts/da/e7/3d/1780282f558e5fd157bf708b28b8ba0d08323ef6bc5b6396139ce38a0b/pyparsing-2.4.7-py2.py3-none-any.whl
pytest @ file:///home/webartifex/.cache/pypoetry/artifacts/f2/06/cd/33f03857dd5f06eba53bcd846bd250bc8f7125ac4851114b5392dcec47/pytest-6.1.2-py3-none-any.whl
pytest-cov @ file:///home/webartifex/.cache/pypoetry/artifacts/b9/58/55/db0439b8e3e9c6ad7790a801ddb71803fd3791b5d6fd7f65efe27016f5/pytest_cov-2.10.1-py2.py3-none-any.whl
pytz @ file:///home/webartifex/.cache/pypoetry/artifacts/7a/8e/a2/e796ae4d320aded38d3d61817b158184888dcd18c6a4f6d6ab011a6cda/pytz-2020.4-py2.py3-none-any.whl
PyYAML @ file:///home/webartifex/.cache/pypoetry/artifacts/28/fe/c8/ee41918e776a0a8fea86e3b4d45d54620381726103e666941e1218c099/PyYAML-5.3.1.tar.gz
regex @ file:///home/webartifex/.cache/pypoetry/artifacts/7b/ae/3c/12683960145c5f53e6dd03567a3ee58d3ec0e1d3d9b31430ad96ec85ff/regex-2020.10.28-cp38-cp38-manylinux2014_x86_64.whl
requests @ file:///home/webartifex/.cache/pypoetry/artifacts/1e/9a/75/03520154e60eb952530469162a6d43cd95ece92de272e2c3392058401c/requests-2.24.0-py2.py3-none-any.whl
restructuredtext-lint @ file:///home/webartifex/.cache/pypoetry/artifacts/b7/45/71/382cdebdbfe4603f3ff0494bfd4460f84940c634dd95f1e1ce1a023a82/restructuredtext_lint-1.3.1.tar.gz
six @ file:///home/webartifex/.cache/pypoetry/artifacts/be/98/c7/69fe6fea7a59659af1c6260899226129565330b1e07c9c5b3769be76bf/six-1.15.0-py2.py3-none-any.whl
smmap @ file:///home/webartifex/.cache/pypoetry/artifacts/39/8f/16/e7986b1d62635c17d6635e446732dd98686c7b0f663445a0cd6e59dcdf/smmap-3.0.4-py2.py3-none-any.whl
snowballstemmer @ file:///home/webartifex/.cache/pypoetry/artifacts/00/58/78/ad3aa1f5e8e5da623c9a205c7cdb41811fb480646c3e79278fc2aec1ad/snowballstemmer-2.0.0-py2.py3-none-any.whl
Sphinx @ file:///home/webartifex/.cache/pypoetry/artifacts/df/9d/a9/d2d9c76b33cb75c2570f64645799fb552f347b4d6a34e437dbf42d5ede/Sphinx-3.3.0-py3-none-any.whl
sphinx-autodoc-typehints @ file:///home/webartifex/.cache/pypoetry/artifacts/07/e9/63/83f90539db71f9ae4be4b5a9fb90ad6e5cb77afd4ae1303de549d51d3a/sphinx_autodoc_typehints-1.11.1-py3-none-any.whl
sphinxcontrib-applehelp @ file:///home/webartifex/.cache/pypoetry/artifacts/06/55/7c/cf28d2c944f7fc7cba94678d0ca98b77947cae69b6c801ffd04601cc8c/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl
sphinxcontrib-devhelp @ file:///home/webartifex/.cache/pypoetry/artifacts/95/e9/af/55ffd1a6f2b03f2bc460172ec6a9ee4a9353404fc6b9026b0fd4776f84/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl
sphinxcontrib-htmlhelp @ file:///home/webartifex/.cache/pypoetry/artifacts/a0/ad/8e/a970be3040e06e0264ff5263c1c64053370852e5711ebce0169f50d4c0/sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl
sphinxcontrib-jsmath @ file:///home/webartifex/.cache/pypoetry/artifacts/5f/c9/8c/2bf04b76e3b07f85857acb15a02dec77db17eb7069ef7e3e8200580fa0/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
sphinxcontrib-qthelp @ file:///home/webartifex/.cache/pypoetry/artifacts/bd/a5/cb/8f6c168f27ca463b2c09d5dfbaabea32b6bb9ebff80556a11bc2b1152f/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl
sphinxcontrib-serializinghtml @ file:///home/webartifex/.cache/pypoetry/artifacts/83/d2/78/3f17c9e1fa5ed17cb815a8d897bf2003c1197b16a36d4e9c6ffa0e8592/sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl
stevedore @ file:///home/webartifex/.cache/pypoetry/artifacts/82/a9/1a/89ccf2529a0533a62894da67e9660c47190abdfacf1f9d96eb7a17df85/stevedore-3.2.2-py3-none-any.whl
testfixtures @ file:///home/webartifex/.cache/pypoetry/artifacts/a7/32/a6/0fc95c70fae6ebc94fe74576a34cb054ee50832a4cfd380ca3754c2bc6/testfixtures-6.15.0-py2.py3-none-any.whl
toml @ file:///home/webartifex/.cache/pypoetry/artifacts/9f/8c/c3/7b4f6778d60f3c9fa11f8fd0e48243bbad25a04975e0a01006b6350594/toml-0.10.2-py2.py3-none-any.whl
typed-ast @ file:///home/webartifex/.cache/pypoetry/artifacts/18/1f/94/6f7cab4b91b697a39bde0b9dad925b0717b2f4b410a070d2cae0e44f7b/typed_ast-1.4.1-cp38-cp38-manylinux1_x86_64.whl
typing-extensions @ file:///home/webartifex/.cache/pypoetry/artifacts/ac/8f/3a/97dfae6ca13a6e156f19a5e8aa95fc250129d7e5e6cd0f7c76a1d45b4f/typing_extensions-3.7.4.3-py3-none-any.whl
urllib3 @ file:///home/webartifex/.cache/pypoetry/artifacts/b0/87/9a/1a8e2a4a36c962a03a9c1a35c9c0634febb4353159f230d7e9a76957a7/urllib3-1.25.11-py2.py3-none-any.whl
virtualenv @ file:///home/webartifex/.cache/pypoetry/artifacts/08/fd/e9/1add79f71f3eae25a8707f4616c2cc44d728af9b3f01d59b1ab762e122/virtualenv-20.1.0-py2.py3-none-any.whl
wemake-python-styleguide @ file:///home/webartifex/.cache/pypoetry/artifacts/c6/77/cd/c271dd6015ac40fc5bd5444626301783611963034f5c3a0c2a621106ea/wemake_python_styleguide-0.14.1-py3-none-any.whl
wrapt @ file:///home/webartifex/.cache/pypoetry/artifacts/0f/c6/81/bb7bbc33b17b52bf47e59ce050e5579a5b96362ba34f37d21ac716343d/wrapt-1.12.1.tar.gz
xdoctest @ file:///home/webartifex/.cache/pypoetry/artifacts/d0/b0/ae/fc9b79c04b07162ac46ce27d0613895704143b0755aceea51005979d1f/xdoctest-0.13.0-py2.py3-none-any.whl

**Comment by sobolevn** [comment]
I found it! https://github.com/peterjc/flake8-rst-docstrings/issues/18
