### ISSUE TITLE
TODO rules

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1726]
I've just found that the `flake8-todos` project has just been wiped off the face of the earth.

This had a few little checks to ensure good usage of TODO comments in big projects.

I think it would be nice to reproduce these checks within wemake.

Currently, you can still view the description at:
https://webcache.googleusercontent.com/search?q=cache:sY8YkzjKMCcJ:https://pypi.org/project/flake8-todos/+&cd=1&hl=en&ct=clnk&gl=uk

But, here's a summary in case the cache stops working:

Good:

```
# TODO(jamie): check performance
# https://github.com/eclecticiq/flake8-todos/issues/1337
```

Bad:

```
# FIXME idk how it works lol
```

Checks

    T001: use TODO instead of FIXME (or BUG) for consistency.
    T002: add author into TODO (read about motivation https://dave.cheney.net/practical-go/presentations/qcon-china.html#_dont_comment_bad_code_rewrite_it).
    T003: add link on issue into TODO.
    T004: missed colon in TODO.
    T005: missed text in TODO.
    T006: write TODO instead of ToDo (use upper case).

**Comment by orsinium** [comment]
I'm surprised that it had users. The code of the plugin never was published before and the plugin was never announced anywhere. Sorry for breaking your pipelines! I'm going to properly re-release it soon:
https://github.com/orsinium-labs/flake8-todos

The motivation to remove it and fork is described in the README. There are a few difficult ownership and licensing questions. I'm going to re-upload it soon. Probably, with a new name but I can't come up with a better one.

However, if the WPS team finds it suitable to merge all rules from the plugin into WPS, I'm all for it!

**Comment by Dreamsorcerer** [comment]
Ah, no problem. I took a look through all the projects on PyPI under the flake8 framework some time ago, so picked out any project that looked interesting/useful. Seemed like the only place where you could find a list of flake8 plugins available.
https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Flake8

**Comment by orsinium** [comment]
Release 0.1.5 is uploaded on PyPI, the project name is the same:
https://pypi.org/project/flake8-todos/
