### ISSUE TITLE
Recommend to use named arguments

### ISSUE THREAD

**Issue by Aleksey94Dan** [wemake-services/wemake-python-styleguide#1736]
# Rule request

## Thesis

If the function has three or more arguments,
it is recommended to use named arguments in the function.

    # bad
    >>> first_member = 1
    >>> step = 2
    >>> difference = 3
    >>> # bad
    >>> def calc_member_progression(first_member, step, difference):
        return first_member + (step - 1) * difference

    >>> calc_member_progression(first_member, step, difference)
    4
    >>> calc_member_progression(first_member, difference, step)
    5
    >>> calc_member_progression(difference, step, first_member)
    4

    >>> # good
    >>> def calc_member_progression(*, first_member, step, difference):
        return first_member + (step - 1) * difference
    >>> calc_member_progression(first_member=first_member, step=step, difference=difference)
    4
    >>> calc_member_progression(step=step, difference=difference, first_member=first_member)
    4
    >>> calc_member_progression(difference=difference, step=step, first_member=first_member)
    4

## Reasoning
    To make code even more intuitive.

**Comment by sobolevn** [comment]
This is a really good idea, but it doesn't really fit our style.
We use both.

And because `mypy` really helps in this case, I am going to mark this as "wontfix".

Thanks a lot for the suggestion! It might be a good idea for a separate plugin you can use together with `wps` in your own projects. 👍
