### ISSUE TITLE
Check only files in the PR

### ISSUE THREAD

**Issue by vnmabus** [wemake-services/wemake-python-styleguide#1751]
Would it be possible to add the option in the Github action to check only the files in the current PR? This would be useful in combination with the github-pr-review reporter, as it would execute faster and consume less Github resources.

**Comment by skarzi** [comment]
hi :wave:

there is already an input `path` in WPS action (however, there is one bug related to it, but fix #1752 is already waiting to for a review) that you can use to implement such behavior with some bash and GitHub actions environments, look at an example [here](https://github.com/skarzi/wemake-python-styleguide/blob/example-for-issue-1751/.github/workflows/wps.yml) and check following GitHub workflow runs:

+ https://github.com/skarzi/wemake-python-styleguide/runs/1478877628?check_suite_focus=true - python files not edited, so action not run
+ https://github.com/skarzi/wemake-python-styleguide/runs/1478902341?check_suite_focus=true - python files edited, but no violation found
+ https://github.com/skarzi/wemake-python-styleguide/runs/1478915207?check_suite_focus=true - violation in one of edited files

**Comment by vnmabus** [comment]
Thanks, that is exactly what I wanted. I saw that the fix is already merged, will it be in a release soon?

I also think that it would be useful to explain this pattern in the documentation of the Github action, as it seems a common one.

**Comment by sobolevn** [comment]
> will it be in a release soon?

Not **really** soon, but soon *enough*. I can probably work on it during my holiday on Jan.

**Comment by vnmabus** [comment]
I can close this, unless you want the issue as a reminder to explain this pattern in the documentation of the Github action.
