### ISSUE TITLE
Make a patch release bumping flake8-eradicate?

### ISSUE THREAD

**Issue by webknjaz** [wemake-services/wemake-python-styleguide#1761]
# Bug report

There's `flake8-eradicate==1.0.0` on PyPI having useful whitelisting features that should, in theory, close #1457. But the last release of `wemake-python-styleguide` limits it to `< 0.4` preventing users from actually installing it.

## What's wrong

While it should be technically possible to upgrade `flake8-eradicate` via a separate command using `pip < 20.3`, it's not that easy in uncontrolled envs like the ones `pre-commit` maintains. It'll also be virtually impossible to have conflicts with the new resolvelib-based pip resolver in 20.3+.

```console
$ grep flake8-eradicate env/lib/python3.9/site-packages/wemake_python_styleguide-0.14.1.dist-info/METADATA  
Requires-Dist: flake8-eradicate (>=0.3,<0.4)
```

## How it should be

The metadata should be more permissive.

## System information

N/A

**Comment by webknjaz** [comment]
This may be a blocker: https://github.com/wemake-services/flake8-eradicate/issues/182.

**Comment by sobolevn** [comment]
I will release `0.15` soon, it requires some final touches.
