### ISSUE TITLE
Rule exceptions for typing stubs

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1778]
Typing stubs tend to trigger a few rules that are unnecessary.

```
class _VehicleTaskState(Protocol):
    def __call__(self) -> Awaitable["_VehicleTaskState"]: ...
```

Triggers:
```
WPS428 Found statement that has no effect
WPS220 Found too deep nesting: 58 > 20
```

As this seems to be the preferred style for typing stubs (e.g. look at the typeshed repo), it should allow the `...` to appear on the same line (and not complain that it has no effect).

**Comment by ariebovenberg** [comment]
Also a frequent violation in typing stubs: WPS112:

```python
class Copy(Protocol):
    def __call__(self, __origin: T) -> T: ...
```

```
WPS 112 Found private name pattern: __origin
```

However, this is the _only endorsed_ way to define positional-only arguments according to mypy docs (at least pre-python 3.8). [link](https://mypy.readthedocs.io/en/stable/protocols.html#callback-protocols)

**Comment by sobolevn** [comment]
All rules from https://github.com/wemake-services/wemake-python-styleguide/issues/1778#issue-770138196 are now disabled.

https://github.com/wemake-services/wemake-python-styleguide/issues/1778#issuecomment-966228496 can be replaced with `/` args now.
