### ISSUE TITLE
@overload functions are counted as module members

### ISSUE THREAD

**Issue by vnmabus** [wemake-services/wemake-python-styleguide#1779]
# Bug report

## What's wrong

Function prototipes marked with the `@overload` decorator in the `typing` module are counted as if they were separate functions to compute WPS202 violations. A previously compliant module can now have this violation merely by adding typing information.

## How it should be

`@overload` functions should not be taken into account, as they must be placed near the original function and do not hinder legibility too much.

**Comment by sobolevn** [comment]
Thanks, @vnmabus for the suggestion! You have contributed a lot of useful ideas 👍
