### ISSUE TITLE
WPS323 Found `%` string formatting for datetime.strftime('%d.%m.%Y')

### ISSUE THREAD

**Issue by tahirjalilov** [wemake-services/wemake-python-styleguide#1796]
# Bug report

## What's wrong

linter show me the warning WPS323 Found `%` string formatting when I use date/time formatting like  datetime.strftime('%d.%m.%Y')

## How it should be

Should not show the warning

**Comment by sobolevn** [comment]
Thanks!

But it is a duplicate of #1329
