### ISSUE TITLE
Forbid os.curdir

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1803]
# Rule request

## Thesis

Forbid `os.curdir`. It is a constant that is always equal to `.` for UNIX and Windows.

UPD: the same applies to `os.path.curdir`

## Reasoning

In most of the cases, it is a bug, and `os.getcwd()` should be used instead. 

IDK what are the operating systems that have a different value for this constant (and if there are any) and in these rare cases when you want to support them, the rule should be explicitly disabled.

**Comment by orsinium** [comment]
A bit of context:
https://stackoverflow.com/questions/14512087/why-does-python-have-os-path-curdir

**Comment by sobolevn** [comment]
It should not be used where `os.getcwd()` must be used. But, other than that - it is a perfectly fine constant.
