### ISSUE TITLE
Multiple grammatical errors in docs/pages/api/index.rst

### ISSUE THREAD

**Issue by adenhaus** [wemake-services/wemake-python-styleguide#1829]
I noticed two grammatical errors in the Philosophy section of the documentation.

1. "However, we pursuit perfect software" should be "However, we pursue perfect software"
2. "Consistent code is more readable then inconsistent" should be "Consistent code is more readable than inconsistent"

<img width="679" alt="Screenshot 2021-01-23 at 14 41 30" src="https://user-images.githubusercontent.com/57678819/105578466-176f3980-5d89-11eb-82b2-3c7ad38aecde.png">

I will fix the sentences myself, and submit a PR.

**Comment by adenhaus** [comment]
I've made the changes and submitted a PR, can someone with write access please review? Thanks a mil.
https://github.com/wemake-services/wemake-python-styleguide/pull/1830

**Comment by sobolevn** [comment]
Merged 👍
