### ISSUE TITLE
Cannot install in pip 20.3+ because of conflicting dependencies

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1847]
It seems that in pip 20.3+ conflicting dependencies now refuse to install at all (in previous versions it would install one with a warning).

Please consider releasing 0.15 ASAP (which already has required changes), and pushing remaining issues to the next milestone.

Maybe also consider removing the upper bounds on dependencies, so these issues are less likely to happen (particularly for all these flake8 plugins, where you're not really interacting with any API).

```
ERROR: Cannot install -r /tmp/requirements-dev.txt (line 33) and flake8-isort>=4 because these package versions have conflicting dependencies.The conflict is caused by:
    The user requested flake8-isort>=4
    wemake-python-styleguide 0.14.1 depends on flake8-isort<4 and >=3.0.1To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflictERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
ERROR: Service 'web' failed to build : The command '/bin/sh -c pip3 install --no-warn-script-location -r /tmp/requirements-dev.txt' returned a non-zero code: 1
```

**Comment by sobolevn** [comment]
Yes, I will release it tomorrow. Thanks! 👍

**Comment by sobolevn** [comment]
Done, `0.15` is released. I have already found some bugs: #1857 #1863 #1864 
So, `0.15.1` is on its way (ETA is the end of this week).

**Comment by Dreamsorcerer** [comment]
Great, thanks.
