### ISSUE TITLE
InfiniteWhileLoopViolation should allow `try:`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1857]
This code does contain `raise` or `break`, but you can clearly see that it is meant to be correct.

```python
while True:
   try:
       some_function_that_raises()
   except Exception:
       print('Shut down')
       sys.exit()
```

So, if `while` loop has `try` - it is good enough for us.

**Comment by Aleksey94Dan** [comment]
Hello. Can you assign me this issue? I'd like to contribute. Thanks.

**Comment by sobolevn** [comment]
@Aleksey94Dan thanks a lot! 👍

**Comment by Aleksey94Dan** [comment]
Sorry.Could you appoint me again? I clicked the wrong place by mistake. Thanks.
