### ISSUE TITLE
Address review from @sindresorhus

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1861]
There are some awesome ideas in this tweet: https://twitter.com/sindresorhus/status/1359226274368028672

We need to:
- fix `python` -> `Python`
- Describe why "strict" is cool 💪 
- Add more examples of bad code => good code

**Comment by aceking007** [comment]
Hi! @sobolevn  Can I work on this issue for Hacktoberfest 2021?

**Comment by sobolevn** [comment]
@aceking007 sure! Thank you!

**Comment by aceking007** [comment]
I'll get to work:
- [ ] fix python => Python
- [ ] Describe why "strict" is cool
- [ ] Add examples to readme

**Comment by aceking007** [comment]
Hey @sobolevn, how many examples should I add to the readme?
