### ISSUE TITLE
Windows 10 Tests Failed

### ISSUE THREAD

**Issue by AlexandrKhabarov** [wemake-services/wemake-python-styleguide#1891]
# Bug report

## What's wrong

I have an issue connected with tests.

Currently, I have 7 failed tests. I didn't make any changes in the code.

Can you help me investigate the source of this issue?

================================================================================ short test summary info =================================================================================
FAILED tests/test_checker/test_noqa.py::test_noqa_fixture_disabled[noqa.py-violations0-True] - IndexError: list index out of range
FAILED tests/test_checker/test_noqa.py::test_noqa_fixture_diff - AssertionError: assert {'WPS110', 'W...'WPS115', ...} == set()
FAILED tests/test_plugins.py::test_external_plugins_diff - AssertionError: B002
FAILED tests/test_visitors/test_tokenize/test_comments/test_shebang.py::test_wrong_shebang_executable[# regular comment-True-{0}\n# some other\n] - AssertionError: assert 1 == 0
FAILED tests/test_visitors/test_tokenize/test_comments/test_shebang.py::test_wrong_shebang_executable[# regular comment-True-{0}] - AssertionError: assert 1 == 0
FAILED tests/test_visitors/test_tokenize/test_comments/test_shebang.py::test_wrong_shebang_executable[#!/bin/python-False-{0}\n# some other\n] - AssertionError: assert 1 == 0
FAILED tests/test_visitors/test_tokenize/test_comments/test_shebang.py::test_wrong_shebang_executable[#!/bin/python-False-{0}] - AssertionError: assert 1 == 0
=========================================================== 7 failed, 31839 passed, 36 skipped, 1 warning in 165.27s (0:02:45) ===========================================================

## How it should be

Tests should finishe sucessfully.

## System information

Windows 10

### flake8 information

{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.6",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "20.11.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.6.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-pytest-style",
      "version": "1.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.2.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "nitpick",
      "version": "0.23.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.14"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.15.1"
    }
  ],
  "version": "3.8.4"
}

### pip information

added-value @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/59/a7/0a/af11cbc458e6ab7584980c90273c1da39a72c05c8eda7cb032df29f1a9/added_value-0.15.0-py2.py3-none-any.whl
alabaster @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/01/50/a4/e8f66b1cc7b3896e348a7976ec6390f61a7ed3cc0583b406c9a737955a/alabaster-0.7.12-py2.py3-none-any.whl
asciitree==0.3.3
astboom @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b1/ae/99/3be88e629f24d17b8b90bb1a39298ec9c66aa393f9fdcd1741300912ba/astboom-0.4.2-py3-none-any.whl
astor @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/00/68/e3/b2c93c6b1eabbb453b7a288336d64a2bb9f32b6821173440843f97f64b/astor-0.8.1-py2.py3-none-any.whl
astpath==0.9.0
atomicwrites @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ca/84/dd/000dbc2864acca52a74a82da8b597c9e4778eb3fe64687a31a8095ad5f/atomicwrites-1.4.0-py2.py3-none-any.whl
attrs @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b7/28/6f/acdd2c0e759f1cda97abf00db7723a0ffb3a151696d8d96398aea16171/attrs-20.3.0-py2.py3-none-any.whl
autopep8 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/12/32/85/a47de676392aadcd1e12b3a4b7bf30ff71acd9dcfd3a93d04e4759d0a6/autopep8-1.5.5-py2.py3-none-any.whl
Babel @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e3/ab/8c/e6b588d52a460a9eca8f0b62cffeb18d90d8631d8b5c7e180c56b123f8/Babel-2.9.0-py2.py3-none-any.whl
backcall @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/62/2c/f2/bf9c43ca0bcfca41150901227b0d023dc854851b710f82a72f5beaa09b/backcall-0.2.0-py2.py3-none-any.whl
bandit @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a2/02/ff/eaae30b6c44acbb38e05e07e4a685c781ebb46ec87a72eeafbc8ede15b/bandit-1.7.0-py3-none-any.whl
certifi @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a5/b1/71/0fb759c6550e4dc0a538f0fc47cdf7dcd23bae70385241ee92b4d5b87c/certifi-2020.12.5-py2.py3-none-any.whl
chardet @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/47/b7/82/19c2b887f87f3adbaf4e34c55189388e5132c78f6929d7001a78b0209b/chardet-4.0.0-py2.py3-none-any.whl
click @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/30/bc/bf/e00ffd8f0edf0294942e70e80e42a839bd2649d2c5b864e6389e526d2a/click-7.1.2-py2.py3-none-any.whl
colorama @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b0/f3/a3/cf94f06cbe1d286a25116cfe54d5a75cb1c4b54d15b2b1b4fc03a7f657/colorama-0.4.4-py2.py3-none-any.whl
coverage @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/8b/b8/fc/3ec5b86047de11d961a663c50d0715cd91387693738b9c0ea47d5052b2/coverage-5.4-cp38-cp38-win_amd64.whl
coverage-conditional-plugin @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/df/17/e1/49d5af25901456859f1afa58d4d3f89d6f0f97fbad079a5038ae0816b3/coverage_conditional_plugin-0.3.1-py3-none-any.whl
darglint @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/80/c4/1a/52f5cf3eb444ebf89ac0044bc1311dda1e438503d53a79b8ce6f0ab3c6/darglint-1.6.0-py3-none-any.whl
decorator @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e8/56/46/038f0f95c2eb2a2792092491cba740226306e663708d5062754d1cb91f/decorator-4.4.2-py2.py3-none-any.whl
dictdiffer @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/eb/97/47/75d6a828e2d9ef1962485d485975c13ff4d8935bb03440f802941f5df2/dictdiffer-0.8.1-py2.py3-none-any.whl
doc8 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/15/14/54/c10d16daae42bacb0d561fbf93d68019c90d273d773c79cdb447cb9111/doc8-0.8.1-py2.py3-none-any.whl
docutils @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/9e/78/f1/81f20d21f3ed304c86fa5394fadbb173e75ad363029a8fefa635dadf2e/docutils-0.16-py2.py3-none-any.whl
dparse @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/45/f0/d9/1a980d82905c06a7365c6227aac29281c69dce4021fafe2a199de092e8/dparse-0.5.1-py3-none-any.whl
eradicate==2.0.0
fastdiff==0.2.0
flake8 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/5c/5b/91/23d9fee55905e042e829a14e2fa56ffd39c81246aba659e2840bab728b/flake8-3.8.4-py2.py3-none-any.whl
flake8-bandit==2.1.2
flake8-broken-line @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/8f/48/91/0d6bc500782a1a3e000937daf9757ae8a66b6eb6cfb37a205bf8b7f786/flake8_broken_line-0.3.0-py3-none-any.whl
flake8-bugbear @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ee/34/92/1a1933902453517c848d54696c56cadd58a50e81e7b6822f86a1a8f14a/flake8_bugbear-20.11.1-py36.py37.py38-none-any.whl
flake8-commas @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b7/aa/76/e620a68b0be70f4132be94bfbfdacb20b16c060174b33dc856818db92d/flake8_commas-2.0.0-py2.py3-none-any.whl
flake8-comprehensions @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/79/68/a1/ad2a93c936991789c7abe3cfaad2061386a4a605875dc6031c7bf68a96/flake8_comprehensions-3.3.1-py3-none-any.whl
flake8-debugger @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/53/fa/32/0169f891a8c8722d66ad761e363416818d8b0bcc7df8ac07903d7e92e7/flake8_debugger-4.0.0-py3-none-any.whl
flake8-docstrings @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/14/46/f1/42800107fb2815121aebf831e269f0af48a45c669a24dbcec60fbbac9f/flake8_docstrings-1.5.0-py2.py3-none-any.whl
flake8-eradicate @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/36/d5/cc/644a05fd3f5223a3cf18d54aa7aa552d16177044159cf71cdb7e277279/flake8_eradicate-1.0.0-py3-none-any.whl
flake8-isort @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/7f/ff/4b/ccb1bf1f070d294477259bb95f68c42dcffe931cbd8e9288d9f8bc2fe9/flake8_isort-4.0.0-py2.py3-none-any.whl
flake8-plugin-utils @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/99/73/fc/1fd22f303405c472d0dd047300335cdbbcc598f106b402ce1176be733b/flake8_plugin_utils-1.3.1-py3-none-any.whl
flake8-polyfill @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/37/d4/b9/446f3fe801eea4de2fdff2cd1e0be3fa836d08c04d62174d4ec65113f3/flake8_polyfill-1.0.2-py2.py3-none-any.whl
flake8-pytest-style @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b9/91/aa/24d42f27861d7e5a75ff711270a98440f637f704a85bc7e67fbaa683c9/flake8_pytest_style-1.3.0-py3-none-any.whl
flake8-quotes==3.2.0
flake8-rst-docstrings==0.0.14
flake8-string-format @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/fd/52/74/3de7f09d54ed637290f8522dc409ca9af53673b8ddc0d4026f088e4c09/flake8_string_format-0.3.0-py2.py3-none-any.whl
gitdb @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/45/a9/94/d73ced00c6cf302a2e08bedd4f10d3424342b7a8a2fae6e4ccb7276641/gitdb-4.0.5-py3-none-any.whl
GitPython @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/10/1b/79/23f0336e0ab7fd0047aaa114f981415f7da4e553edc8017366c4d36e82/GitPython-3.1.13-py3-none-any.whl
grimp==1.2.3
hypothesis @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/89/f4/e5/4685f2ff3742fc1f3e2c2b8b77633db1114ad9c7049cff8beb8e8487e4/hypothesis-6.2.0-py3-none-any.whl
hypothesmith @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/78/6a/70/6cd18fb81a1da7dcf17541c29bb6bee9a8c946418fb3f0a410d3d9c636/hypothesmith-0.1.8-py3-none-any.whl
identify @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/84/bc/7d/31f1bb352c4632a4ff3b4d6058249fbf6ca782b6820081558c4081baf5/identify-1.5.13-py2.py3-none-any.whl
idna @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/9e/f9/03/6066b92d35486e7f0d4f310126e3c60a6619726e43ef98e32e105b5c52/idna-2.10-py2.py3-none-any.whl
imagesize @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/0b/69/4e/8e64ed37efc2f5438fce870c94736b2e1a21bc4cb0c286f936de14357b/imagesize-1.2.0-py2.py3-none-any.whl
import-linter @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/8f/50/90/35176b24738a6a2c009d9e2b6e1489b044128988b3426ade0a3ce9ddda/import-linter-1.2.1.tar.gz
iniconfig @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ac/f9/da/e990ffcd9ec361a68676a5916e391286e1ea5d1b8907ae887e141a71f5/iniconfig-1.1.1-py2.py3-none-any.whl
ipdb==0.13.4
ipython @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ee/15/e4/46c9aac48c17943cf2b157b42f91ea38a776eb75555dda9b3ce97460be/ipython-7.16.1-py3-none-any.whl
ipython-genutils @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e6/8e/a3/8f37e14310c0072b3fcc4240490bcb42630aa695d069aee89953ebd9f8/ipython_genutils-0.2.0-py2.py3-none-any.whl
isort @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/c7/65/52/89112b51dedef2d5c6ae731072aace88c4bb499093e551cceec24f2b18/isort-5.7.0-py3-none-any.whl
jedi @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/42/26/07/496d2180e241dbf58cf832e0c7a617d8fcbdd6f3f93937056d106545fc/jedi-0.18.0-py2.py3-none-any.whl
Jinja2 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/1e/19/63/9b4675e143abad59de60e0e667815fd5e19dd0b28fc2815f9f957726d3/Jinja2-2.11.3-py2.py3-none-any.whl
jmespath @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/43/d5/a2/f83573231324de7f5b61f5c607fbbe82ca535359a452de4852d2e25e8d/jmespath-0.10.0-py2.py3-none-any.whl
lark-parser @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/2d/fb/1a/f7d6d00da5f2c84242405452b38cfc7865346a717626e66f1718c3bb83/lark_parser-0.11.1-py2.py3-none-any.whl
libcst @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/80/dd/86/916f972814aade9f4721a874d4b12eff72cee2b434be48a2ac36283524/libcst-0.3.17-py3-none-any.whl
lxml @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ab/af/ca/aeff8cb63b678f5e1da144f56ff4ec3bd4c6e334df89e2604a24c3b119/lxml-4.6.2-cp38-cp38-win_amd64.whl
m2r2 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/39/34/88/117e6424dbc37ae8415c6169ce97fad37fb90000feb01d9870e3a01667/m2r2-0.2.7-py3-none-any.whl
MarkupSafe @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/81/c9/c6/16c9c81737606d9ad09be7dfc836da11c6da30087ee4ad8e786489cc84/MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl
marshmallow @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/78/e7/6d/37c098bfe4a91d91057e01d2b2df13cd652fccf5434981b817618a71ae/marshmallow-3.10.0-py2.py3-none-any.whl
marshmallow-polyfield==5.9
mccabe @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/37/6e/69/4a33a4d6c80c775b1ee205face2c6e07b762c8602bb0f0d236ebe790c5/mccabe-0.6.1-py2.py3-none-any.whl
mistune @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/d9/d8/5c/8eac14aaa95c3aa81409d56b7423ff6dd88eb398f551c1bf0b8c05b916/mistune-0.8.4-py2.py3-none-any.whl
more-itertools @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e5/3f/ef/7962cb207c9c377a5e2858c39136056c76582b87e3716935561bdcae94/more_itertools-8.7.0-py3-none-any.whl
mypy @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/f4/90/cb/7c73a4aefb115e0996c2251573e3c7094858829f82768d972acce0468d/mypy-0.800-cp38-cp38-win_amd64.whl
mypy-extensions @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b6/a0/b0/a5dc9acd6fd12aba308634f21bb7cf0571448f20848797d7ecb327aa12/mypy_extensions-0.4.3-py2.py3-none-any.whl
natsort @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/dc/ad/66/dcfa104ac1ec400ed48047f88aa2a7697b217f3f3f261242fd21af1b19/natsort-7.1.1-py3-none-any.whl
networkx @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/11/45/ad/ed189e076cabf73adf5f9000e776d2c303e2f20feaa3546c0bed9aa645/networkx-2.5-py3-none-any.whl
nitpick @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/28/98/16/5682d5116b7b7060227becef96a14e31c189a936800abb96b0c0dfc7b9/nitpick-0.23.1-py3-none-any.whl
packaging @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/69/b5/74/4884010222ec7d09be9bd10d71316b7c49153ef24103605e4a2650af7c/packaging-20.9-py2.py3-none-any.whl
parso @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/fe/ac/61/368c9383d3833586c1d666ec86359b6511fa79adb884e5f3ac5fd47a90/parso-0.8.1-py2.py3-none-any.whl
pbr @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/85/81/cf/9255f6df466921f8291c85ab33df01caeda1916c2745a5071ce06a963f/pbr-5.5.1-py2.py3-none-any.whl
pep8-naming @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e7/c8/00/b145306a40eba2961774c78d56e8fb9b09c08e44af6fd83642c5114bba/pep8_naming-0.11.1-py2.py3-none-any.whl
pickleshare @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/27/b2/0a/93a92c700a1993b2923519262ddf76a629bd459a0597c0ae28bf80c7a6/pickleshare-0.7.5-py2.py3-none-any.whl
pluggy @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/9c/e5/0b/2d64d03361a081edeb5d2ec5f286ccf9719587781fbf6822e1b6384c27/pluggy-0.13.1-py2.py3-none-any.whl
prompt-toolkit @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/29/07/32/ab905b813084669526473701a9c9a296c4b637bad0d2679d4f086b91ea/prompt_toolkit-3.0.3-py3-none-any.whl
py @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/6b/b2/2b/e6686e7d0183dbd36bd66921efa3e77ce26260a3671524cd86614290e0/py-1.10.0-py2.py3-none-any.whl
pycodestyle @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/01/f4/cf/c7e34cb76e03e95d9eff28af16fe09ee8edd01cc985fc2b88453b6d311/pycodestyle-2.6.0-py2.py3-none-any.whl
pydocstyle @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a4/ef/58/498033174cb8c68875036ec5d8a3d9d2e169c51bec9d35866bd62ff5ac/pydocstyle-5.1.1-py3-none-any.whl
pyflakes @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/da/83/11/1e9a80c39638c6967e9b1117b17d8ec5f723ddd0a88251cc08dc0807b0/pyflakes-2.2.0-py2.py3-none-any.whl
Pygments @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/d8/89/8d/dd9d739214940ed315c7a6aa2fc949a9ed6257976b13c0e7d40e684012/Pygments-2.8.0-py3-none-any.whl
pyparsing @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/da/e7/3d/1780282f558e5fd157bf708b28b8ba0d08323ef6bc5b6396139ce38a0b/pyparsing-2.4.7-py2.py3-none-any.whl
pytest @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ba/91/14/23adb9b15ce836665a99c972a5135db1ca93b99dfe4946fddf87c531b6/pytest-6.2.2-py3-none-any.whl
pytest-cov @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e8/ed/6e/eac235440db34634156d9b3964828f68d21a7a936edfeed08da39c8ba4/pytest_cov-2.11.1-py2.py3-none-any.whl
pytest-randomly @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ec/d0/3c/142a2f637a49d6c11feea2a694c02e488b83021cfc00b940c1b09736ce/pytest_randomly-3.5.0-py3-none-any.whl
python-slugify==4.0.1
pytz @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/19/50/c9/f8bffb0360052b3c85b912bc4172f824bc2571e24002806fb3a428302e/pytz-2021.1-py2.py3-none-any.whl
PyYAML @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b4/f2/b7/896cbc27af4e3a043c1f28a3cdccbbe7303ef9f6173686768187be02a5/PyYAML-5.4.1-cp38-cp38-win_amd64.whl
requests @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/fe/f0/74/d691c7619cd645682c495ff78949b9c284e88d3f2ee85124df5cec5b0a/requests-2.25.1-py2.py3-none-any.whl
restructuredtext-lint==1.3.2
ruamel.yaml @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/fa/10/2b/409b73cb7fd78317ea1094d48cb62274d1ceb83475047162e073699ec5/ruamel.yaml-0.16.12-py2.py3-none-any.whl
ruamel.yaml.clib @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/3f/90/23/24dc6fd6c3b2b0fc5078e495a51cd817f5b06b7e1037f15b14bb8865e8/ruamel.yaml.clib-0.2.2-cp38-cp38-win_amd64.whl
safety @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/63/c0/5e/ad040630c3c4e32471b7b2dbd488d35607706d7edfa79c7cd005822b82/safety-1.10.3-py2.py3-none-any.whl
six @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/be/98/c7/69fe6fea7a59659af1c6260899226129565330b1e07c9c5b3769be76bf/six-1.15.0-py2.py3-none-any.whl
smmap @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ab/27/f3/6ab65f7970ca4dbc0d01a73d5a79abe597252970bf3abc442a7084a6f5/smmap-3.0.5-py2.py3-none-any.whl
snapshottest @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ec/b6/6a/921028c2bc2c700db3f83a8f52280b46e33b89fff4b69fc5357c978425/snapshottest-0.6.0-py2.py3-none-any.whl
snowballstemmer @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a6/21/11/58b79c57cfc922455998165c2ecc503603be058fe178af058936deaf1f/snowballstemmer-2.1.0-py2.py3-none-any.whl
sortedcontainers @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/b3/bf/a2/83677c4175a4561da36b5ec625e33e1cdd6d78137304a914eb5d6fdcdd/sortedcontainers-2.3.0-py2.py3-none-any.whl
Sphinx @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/1e/a0/2c/e95d3eab0d6a56367654490bd40b64bf549dad60087c00af494cc3c5b3/Sphinx-3.5.1-py3-none-any.whl
sphinx-autodoc-typehints @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/07/e9/63/83f90539db71f9ae4be4b5a9fb90ad6e5cb77afd4ae1303de549d51d3a/sphinx_autodoc_typehints-1.11.1-py3-none-any.whl
sphinxcontrib-applehelp @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/06/55/7c/cf28d2c944f7fc7cba94678d0ca98b77947cae69b6c801ffd04601cc8c/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl
sphinxcontrib-devhelp @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/95/e9/af/55ffd1a6f2b03f2bc460172ec6a9ee4a9353404fc6b9026b0fd4776f84/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl
sphinxcontrib-htmlhelp @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a0/ad/8e/a970be3040e06e0264ff5263c1c64053370852e5711ebce0169f50d4c0/sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl
sphinxcontrib-jsmath @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/5f/c9/8c/2bf04b76e3b07f85857acb15a02dec77db17eb7069ef7e3e8200580fa0/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
sphinxcontrib-mermaid @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/5f/fc/9d/39829fbf749b81a3a9ffe749a075d85f4804a40cf7137265e477677a0f/sphinxcontrib_mermaid-0.6.2-py2.py3-none-any.whl
sphinxcontrib-qthelp @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/bd/a5/cb/8f6c168f27ca463b2c09d5dfbaabea32b6bb9ebff80556a11bc2b1152f/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl
sphinxcontrib-serializinghtml @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/83/d2/78/3f17c9e1fa5ed17cb815a8d897bf2003c1197b16a36d4e9c6ffa0e8592/sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl
stevedore @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/df/1c/87/ee139e37999b53501924b31a04b30301f789c2944af24daea1ada94ceb/stevedore-3.3.0-py3-none-any.whl
termcolor==1.1.0
testfixtures @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/33/ef/82/2cdf5deff816074815a062ea94bc53083040ae5ca90178494e082a6cc0/testfixtures-6.17.1-py2.py3-none-any.whl
text-unidecode @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/9b/cc/f2/c615087594418f3b86c03fb83c56a1d3b673e89924d4bd0cece68a7615/text_unidecode-1.3-py2.py3-none-any.whl
tokelor @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/59/5a/f2/06d9f4337f3d8ba36792abb5483212fd76217f450482669e4bede715ec/tokelor-0.1.6-py3-none-any.whl
toml @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/9f/8c/c3/7b4f6778d60f3c9fa11f8fd0e48243bbad25a04975e0a01006b6350594/toml-0.10.2-py2.py3-none-any.whl
tomlkit @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/db/c3/df/baf014ce3b04caffe7ac34bde699f5be82c4acbaf43f49db1ce681a500/tomlkit-0.7.0-py2.py3-none-any.whl
traitlets @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/c8/9d/8a/0ac7b9700197ce07d35f1f4db4c2afa79c83149e7ad6fafd4e82aa1143/traitlets-4.3.3-py2.py3-none-any.whl
typed-ast @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ba/68/45/0b3dcb308baa39234616e9e9932f250e042d0a89d24b233ed86bb05e61/typed_ast-1.4.2-cp38-cp38-win_amd64.whl
typing-extensions @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/ac/8f/3a/97dfae6ca13a6e156f19a5e8aa95fc250129d7e5e6cd0f7c76a1d45b4f/typing_extensions-3.7.4.3-py3-none-any.whl
typing-inspect @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/e4/73/a2/26dc4873052845e2b869a836f9b8fdccfafa251e7ff170d9e49ecb4db3/typing_inspect-0.6.0-py3-none-any.whl
urllib3 @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/a9/fc/7b/ab7ab6ea0d0cbf7347c6de7a3ab67af2f715357ebb539bdf464671b640/urllib3-1.26.3-py2.py3-none-any.whl
wcwidth @ file:///C:/Users/hubsa/AppData/Local/pypoetry/Cache/artifacts/36/68/e2/7232f431072d5e8aeec124120b9a1d095d45da10311d271fac10982473/wcwidth-0.2.5-py2.py3-none-any.whl
wemake-python-styleguide==0.15.1

**Comment by sobolevn** [comment]
That's ok, because `test_wrong_shebang_executable` checks unix-specific things.
To be specific it checks that a given file is executable if it has a shebang.

**Comment by AlexandrKhabarov** [comment]
> That's ok, because `test_wrong_shebang_executable` checks unix-specific things.
> To be specific it checks that a given file is executable if it has a shebang.

Oh, Thanks!

**Comment by AlexandrKhabarov** [comment]
I will fix it.

**Comment by sobolevn** [comment]
@AlexandrKhabarov thanks a lot!

We can also add `windows` job on GitHub Actions. 
See: https://github.com/HypothesisWorks/hypothesis/blob/master/.github/workflows/main.yml#L67
