### ISSUE TITLE
Forbid effectless try-except

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1904]
# Rule request

## Thesis

```python
# bad
try:
  do_something()
except SomeException:
  raise

# bad
try:
  do_something()
except SomeException as exc:
  raise exc

# all above the same as just
do_something()
```

## Reasoning

Code simplification.

**Comment by orsinium** [comment]
PyLint has W0706 "The except handler raises immediately". Looks like it is the same. Good to have it re-implemented on WPS side, I think.

**Comment by orsinium** [comment]
Another interesting case:

```python
try:
    do_something()
finally:
    pass
```

**Comment by orsinium** [comment]
Sure! Go on :)

**Comment by sobolevn** [comment]
Yeap, should be closed: https://github.com/wemake-services/wemake-python-styleguide/blob/a404bc01a304fe7dfc70389e55696f0d1cc68ce0/wemake_python_styleguide/violations/consistency.py#L1222

Thanks!
