### ISSUE TITLE
Feature: allow magic numbers in async functions constructors

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#193]
We check that some magic numbers can be used in function constructors like so:

```python
def some_function(price, delta=0.1):
      return price * delta
```

But, we only allow regular functions, not `async` ones: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/numbers.py#L19-L21

What we need to do is:
1. Add `ast.AsyncFunctionDef` to the allowed list
2. Write a unit test for it: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_visitors/test_ast/test_general/test_magic_numbers.py

**Comment by xarus01** [comment]
Hi! I'd like to give it a try
