### ISSUE TITLE
Enforce strict class attribute names

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#194]
We need to track this issue in `pep8-naming`: https://github.com/PyCQA/pep8-naming/issues/78

In the worst case scenario we will need to implement this rule in our linter.

## Thesis

We need to enforce `snake_case` class attribute names.
Currently one case use any notation. Without any limitations.

**Comment by sobolevn** [comment]
There's no question left: we need to enforce `snake_case` for class attributes.
We do not allow `CONSTANT_CASE` for `class` level constants. Since I prefer to use regular constants.

**Comment by lensvol** [comment]
I'm willing to take this over. :)

**Comment by sobolevn** [comment]
We should only track constants defined on the class, not instance.

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/pull/242
