### ISSUE TITLE
pyproject.toml Cannot inherit from [tool.flakehell] remote config

### ISSUE THREAD

**Issue by psychonaute** [wemake-services/wemake-python-styleguide#1971]
### What's wrong

trying to follow the doc, when adding the following to my pyproject.toml

```
[tool.flakehell]
# optionally inherit from remote config (or local if you want)
base = "https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/flakehell.toml"
```
I got the following error when running the linter
```
toml.decoder.TomlDecodeError: Found invalid character in key name: '!'. Try quoting the key name. (line 7 column 2 char 7)
```

### How it should be

get no stack trace :)

### Flake8 version and plugins

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.1",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "20.11.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.4.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.2.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "pylint",
      "version": "0.0.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.14"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.15.2"
    }
  ],
  "version": "3.9.0"
}
```

### pip information

arrow==1.0.3
astor==0.8.1
attrs==20.3.0
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
backports.shutil-get-terminal-size==1.0.0
bandit==1.7.0
binaryornot==0.4.4
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
colorama==0.4.4
comtypes==1.1.8
cookiecutter==1.7.2
cryptography==3.3.1
darglint==1.8.0
docutils==0.17
entrypoints==0.3
eradicate==2.0.0
flake8 @ file:///tmp/build/80754af9/flake8_1615834841867/work    
flake8-bandit==2.1.2
flake8-broken-line==0.3.0
flake8-bugbear==20.11.1
flake8-commas==2.0.0
flake8-comprehensions==3.4.0
flake8-debugger==4.0.0
flake8-docstrings==1.6.0
flake8-eradicate==1.0.0
flake8-isort==4.0.0
flake8-polyfill==1.0.2
flake8-quotes==3.2.0
flake8-rst-docstrings==0.0.14
flake8-string-format==0.3.0
flakehell==0.9.0
gitdb==4.0.7
GitPython==3.1.14
idna==2.10
importlib-metadata @ file:///C:/ci/importlib-metadata_1615900668184/work
isort==5.8.0
Jinja2==2.11.3
jinja2-git==1.1.0
jinja2-time==0.2.0
lice==0.6
MarkupSafe==1.1.1
mccabe==0.6.1
olefile==0.46
pbr==5.5.1
pep8-naming==0.11.1
Pillow @ file:///C:/ci/pillow_1607027481264/work
poyo==0.5.0
psutil==5.8.0
pycodestyle==2.7.0
pycparser==2.20
pydocstyle==6.0.0
pyflakes==2.3.1
Pygments==2.8.1
python-dateutil==2.8.1
python-slugify==4.0.1
pywin32==228
PyYAML==5.4.1
requests==2.25.1
restructuredtext-lint==1.3.2
six==1.15.0
smmap==4.0.0
snowballstemmer==2.1.0
stevedore==3.3.0
testfixtures==6.17.1
text-unidecode==1.3
toml==0.10.2
typing-extensions==3.7.4.3
urllib3==1.26.4
wemake-python-styleguide==0.15.2
wincertstore==0.2
windows-curses==2.2.0
zipp @ file:///tmp/build/80754af9/zipp_1615904174917/work

### OS information

Windows 10

**Comment by sobolevn** [comment]
Sorry, but it does not look like we have `!` somewhere in https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/flakehell.toml

Can you please create a new issue in https://github.com/andreoliwa/nitpick ?

**Comment by psychonaute** [comment]
is nitpick used under the hood?

**Comment by sobolevn** [comment]
Oh, no. Looks like you are using `flakehell`.

It is deprecated: https://github.com/life4/flakehell#the-project-is-archived

**Comment by sobolevn** [comment]
@psychonaute I will do it soon! 👍

**Comment by gpchelkin** [comment]
@sobolevn Original root cause of this issue was that link used in doc is GitHub Web UI link:
`https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/flakehell.toml`
But correct link is:
`https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/flakehell.toml`
I would also suggest removing flakehell from the doc.
Also FYI according to https://github.com/orsinium/forks there is an active fork: https://github.com/flakeheaven/flakeheaven
