### ISSUE TITLE
conda-forge support?

### ISSUE THREAD

**Issue by ma-sadeghi** [wemake-services/wemake-python-styleguide#1994]

**Comment by orsinium** [comment]
What's the motivation? Conda supports PyPI out of the box: https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-packages/#using-package-managers

**Comment by ma-sadeghi** [comment]
@orsinium Thanks for your reply.

The motivation is that for a conda-forge package to work, all its dependencies must be on conda-forge as well.

**Comment by orsinium** [comment]
You can install Python packages into conda environment using pip, and so all dependencies will be installed as well:
![image](https://user-images.githubusercontent.com/9638362/120590922-94977300-c43b-11eb-96a3-4650f58dca43.png)

**Comment by ma-sadeghi** [comment]
@orsinium Sorry I was not clear enough. Indeed, on your local machine that works fine.

My point was that if you want to contribute a package to conda-forge (so people can install it using `conda install your_package`), all the dependencies need to be hosted on conda-forge as well. For instance, our package [`porespy`](https://github.com/PMEAL/porespy/) is hosted on conda-forge. Now, if we want to add `wemake-python-styleguide` as a dependency, it has to be hosted on conda-forge as well.

Reference: https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies

> As a general rule: all dependencies have to be packaged by conda-forge as well. This is necessary to assure ABI compatibility for all our packages.

**Comment by sobolevn** [comment]
@ma-sadeghi this would be really hard to make! Because, `wps` has lots of dependencies and it would be hard to copy all of them to `conda`.

**Comment by orsinium** [comment]
Sure, the question is why one would need it in conda if WPS already can be installed in conda environment using pip? There is not much difference to type `conda install` or `pip install`

**Comment by ma-sadeghi** [comment]
@orsinium Because you can explicitly include C/Fortran dependencies if you ship your package in conda, and not in pip.

**Comment by orsinium** [comment]
Sure, I know why one needs conda 👍🏿 However, WPS doesn't have any C-dependencies, so you can deploy in 2 commands:

```
conda install ...
pip install wemake-python-styleguide
# or
pip install -r requirements.txt
```

What do you use for deployment? Ansible, Docker, Taskfile, Makefile? In any case, one more command isn't a big deal. Even if WPS would come into Anaconda Cloud, there are [tons of good flake8 extension](https://github.com/DmytroLitvinov/awesome-flake8-extensions) that aren't on PyPI but deserve giving it a try, and so you still will need pip-based installation for them.

**Comment by ma-sadeghi** [comment]
@orsinium Fair enough and agreed :)
