### ISSUE TITLE
Restrict names with underscored numbers

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#205]
# Rule request

## Thesis

There are two possible ways how one can write "Star Wars Episode 2" in snake case: `star_wars_episode2` and `star_wars_episode_2`.

The same goes for numbers in the middle of the name: `come2_me` vs `come_2_me`.

We need to enforce the first version and restrict the former.

## Reasoning

This is done for consistency in naming.

**Comment by sobolevn** [comment]
This should be allowed: `ISO-123-456` should become: `iso_123_456`. 
So, having this pattern is allowed: `r'\d_\d'`.

**Comment by riyasyash** [comment]
@sobolevn, Two questions: 
1. This restriction has to be implemented for both variable names and file names, right?
2. `star_wars_episode_2_2` is this allowed ?

**Comment by sobolevn** [comment]
@riyasyash 

Yes for both of your questions 🙂 
We can even use the same violation for variables and modules. 

Are you willing to take this over?

**Comment by riyasyash** [comment]
@sobolevn Yes I am. :)

**Comment by swats-the-floran** [comment]
all my scripts for 1C are named like {endpoint}_1c.py
