### ISSUE TITLE
Python 3.10: ImportError

### ISSUE THREAD

**Issue by sshishov** [wemake-services/wemake-python-styleguide#2053]
### What's wrong

Trying to run the code and getting the following exception:
```
ImportError: cannot import name 'Hashable' from 'collections'
```

### How it should be

There should be no exception, the import should be properly handled for Python 3.10

### Flake8 version and plugins

Not installed

### pip information

21.0.1

### OS information

MacOS

**Comment by rudranshsharma123** [comment]
Hello, I am new to open source would love to make a contribution to this issue. Can you provide guidance on how to proceed with this issue?

**Comment by sobolevn** [comment]
Hi @rudranshsharma123 !

You need to fix import error on Python3.10. To do that:
1. Install python 3.10 alpha or beta
2. Install `wemake-python-styleguide` the usual way
3. Try to lint any file, it should break with the same message
4. Fix it! I think that `Hashable` was moved or renamed
5. Try once again, everything must work correctly!

**Comment by sshishov** [comment]
Please read the first paragraph [here](https://docs.python.org/3/library/collections.html#module-collections).
It was moved from `collections` to `collections.abc` since Python 3.3. It supported the old location till Python 3.9. But in python 3.10 it was removed.

It depends what type of python is supported by this tool. If it is python 3.5+ then it is safe to just change the import and not to pollute code with `try...except...` But if we support Python 2 then we should go with the latter.

I vote for clean import as Python 3.4 and down are not supported by community and should be deprecated.
