### ISSUE TITLE
Add flake8-print to the rules list

### ISSUE THREAD

**Issue by AlexArcPy** [wemake-services/wemake-python-styleguide#209]
# Rule request

`flake8-print` is already listed [as dev dependency](https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L72). Is there any particular reason why we should not include in the list of rules? 

https://github.com/jbkahn/flake8-print

## Thesis

Having `print` statements _may_ indicate that they have been left after the troubleshooting was done or developer needed to have more detailed info printed while working on a code block and forgot to remove the `print` statements. When having a problematic piece of code one knows to cause issues often, it can be helpful to use instead the [`logging.debug` function](https://docs.python.org/2/library/logging.html) and setting the logging level for the program; having the level set to `logging.INFO` would not trigger execution of `debug` function calls. This provides a clean solution for cases when one needs to steer whether debug information should be printed or not; the change is done in a single place (by setting the logging level) and there is no need to comment/uncomment `print` statements all the time.

```python
import sys
import logging
from logging import debug

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format='%(message)s')
debug("------- ProductId {} -------".format(productid))
```

## Reasoning

[Print statements _may_ add extra time to the program execution time](https://stackoverflow.com/questions/3857052/why-is-printing-to-stdout-so-slow-can-it-be-sped-up) while not providing any value unless the results of program execution are being examined by a developer. Furthermore, the result of printing may pollute the output of the tests being run making it difficult to examine the feedback provided by the tests programmatically.

**Comment by sobolevn** [comment]
@AlexArcPy sure! I have just missed it. 

Thanks for mentioning that.

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/commit/c3a04a1f3d7123ecef41ba6d1991a7a722ef92c8
