### ISSUE TITLE
Wrong Getter and Setter example

### ISSUE THREAD

**Issue by GibranHL0** [wemake-services/wemake-python-styleguide#2102]
### What's wrong

I believe that the example within the `UnpythonicGetterSetterViolation` is not well explained. A getter function should retrieve an attribute value without specifying the value itself, and a setter function should provide a value for the attribute. The current example is:
```python
# Correct:
    class Example(object):
        def __init__(self):
        self._attribute = None

# Wrong:
    class Example(object):
        def __init__(self):
        self.attribute = None

    def set_attribute(self):
        ...

    def get_attribute(self, value):
        ...
```

### How it should be

The correct example should be:

```python
# Correct:
    class Example(object):
        def __init__(self):
        self._attribute = None

# Wrong:
    class Example(object):
        def __init__(self):
        self.attribute = None

    def set_attribute(self, value):
        ...

    def get_attribute(self):
        ...
```

### Flake8 version and plugins

There's no need.

### pip information

There's no need

### OS information

There's no need

**Comment by sobolevn** [comment]
Correct should be:

```python
# Correct:
 class Example(object):
    def __init__(self):
        self.attribute = None
```

Can you please create a PR with the fix? 🙂

**Comment by GibranHL0** [comment]
Sure, I'll create the PR right away. 😌
