### ISSUE TITLE
Feature: find unreachable and dead code

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#213]
# Rule request

## Thesis

We need to find dead code. That includes:

1. Code that is unreachable due to `raise` 
2. Code after `return` statement

## Reasoning

This kind of code indicate a serious problem in your app.
This code 100% should be removed or refactored.

**Comment by AlexArcPy** [comment]
Found recently https://github.com/jendrikseipp/vulture, maybe this could be used?

From the docs:

> Vulture uses the ast module to build abstract syntax trees for all given files. While traversing all syntax trees it records the names of defined and used objects. Afterwards, it reports the objects which have been defined, but not used. This analysis ignores scopes and only takes object names into account.
> 
> Vulture also detects unreachable code by looking for code after return, break, continue and raise statements, and by searching for unsatisfiable if- and while-conditions.

**Comment by sobolevn** [comment]
@AlexArcPy we are already using it: https://wemake-python-styleguide.readthedocs.io/en/latest/_pages/usage.html#extras

**Comment by AlexArcPy** [comment]
@sobolevn Oh, from the docs you refer to it is listed as a tool you recommend users to take advantage of however I have not seen any piece of code of the linter that actually uses `vulture`. Have I missed it? My idea was that maybe it could help with this particular rule request.

**Comment by sobolevn** [comment]
We do not use `vulture` in this project due to its dynamic nature. Because `visit_*` methods are completely magic.
