### ISSUE TITLE
Forbid `try` with `finally`without `except`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#215]
# Rule request

## Thesis

We should forbid using `try` block with anything other than `except`.

## Reasoning

Related: https://help.semmle.com/wiki/display/PYTHON/Should+use+a+%27with%27+statement

Let's remember why do we use `try` with `finally`. To clean thing up when something explodes inside `try` block. That a popular pattern for files, streams, etc.

What else can be used in this case? We can use `with` to make this code readable. Consider this example:

```python
try:
    f = open("filename")
    f.write(...)
finally:
    f.close()
```

Versus context manager:

```python
with open("filename") as f:
    f.write(...)
```

The second version looks cleaner and more readable. 

## Limitations

This rule is limited to cases when there are no `except` blocks. Because when there are except blocks `finally` becomes very useful to execute any logic after both successful and exceptional branches.

**Comment by sobolevn** [comment]
@novikovfred do you have the time to take this one? Should be a really simple one.

**Comment by novikovfred** [comment]
@sobolevn ye, i'll do it
