### ISSUE TITLE
Forbid `try` with `else` block

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#216]
# Rule request

## Thesis

After using `python` for almost a decade I have ever seen a use of `try-else` blocks.
Let's enforce writing everything in a single block.

## Reasoning

Example:

```python
try:
    file_object = open()
    book = file_object.read()
except Exception:
    panic()
```

Versus:

```python
try:
    file_object = open()
except Exception:
    panic()
else:
    book = file_object.read()
```

In the second example logic is split into two blocks. It is easier to miss something. It is harder to read it.

After reading the corresponding articles I have found out that I am not alone. The most popular SO answer about `try-else` states:

> The statements in the else block are executed if execution falls off the bottom of the try - if there was no exception. Honestly, I've never found a need.

https://stackoverflow.com/a/855764/4842742

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/215

**Comment by pywkm** [comment]
You might want to change `catch` to `except`, or I start to doubt you use Python for almost 10 years.

Also, what the heck? You want to forbid legitimate construct of language? Because of S.O. article?
What next? Forbidding for loop with else block?

**Comment by sobolevn** [comment]
@pywkm thanks for finding a typo. 

Can you please prove your point? What situations can be handled with only `try-else`?

**Comment by sobolevn** [comment]
Yeap, that was an incorrect rule. 

I have missed one very important thing: `else` does not swallow exceptions.
It is totally different from the regular `try-except`. 

@pywkm thanks for bringing this up.
