### ISSUE TITLE
Forbid to compare the identical variables

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#219]
# Rule request

## Thesis

We need to find cases like this: `if some_value == some_value:`.
We also need to find other operators: `is`, `is not`, `>`, `<`, `!=`, `>=`, `<=`.

## Reasoning

It clearly does not make any sense. It is a bug in the source code.

Related: https://help.semmle.com/wiki/display/PYTHON/Comparison+of+identical+values

**Comment by SheldonNunes** [comment]
Happy to take a look at this one!
