### ISSUE TITLE
`recommonmark` is deprecated

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#2193]
https://github.com/readthedocs/recommonmark#recommonmark

We should switch to `myst`: https://github.com/executablebooks/MyST-Parser

**Comment by ShehanAT** [comment]
Hi @sobolevn can I work on this issue?

**Comment by sobolevn** [comment]
We are going to use deprecate parser, `myst` just does not work for us:
1. It cannot include `md` files with `html` in it
2. It raises lots of errors for our `md` formatting: it requires empty lines in random positions: `Definition list ends without a blank line; unexpected unindent.`
3. It cannot parse our valid `CONTRIBUTING.md` markup
4. It raises strange `Inline literal start-string without end-string.`
5. It raises lots of warnings for our Python code
6. Sometimes it raises: `../README.md:121: WARNING: Unexpected indentation.`

I don't think that it is worth it.
