### ISSUE TITLE
We use `wemake_python_styleguide.options.defaults.FORBIDDEN_NOQA` when we should use `wemake_python_styleguide.options.defaults.FORBIDDEN_INLINE_IGNORE`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#2195]
### What's wrong

Our docs is wrong, we need to update `wemake_python_styleguide/options/config.py`
The incorrect default is in `forbidden-inline-ignore` option

**Comment by DireWolf707** [comment]
Hye, I am new to open source and want to contribute to this issue for hacktoberfest.
So, can you assign this issue to me?

**Comment by sobolevn** [comment]
Sure! Thanks!

**Comment by singhaditya28** [comment]
@sobolevn is the pr correct? or can i take this too?

**Comment by DireWolf707** [comment]
@singhaditya28 I am an active contributor and will make suggested changes further if any are required to my PR :)

**Comment by sobolevn** [comment]
Thanks a lot, @DireWolf707 for the fix! And @singhaditya28 for the ping! 🙂
