### ISSUE TITLE
Forbid `BaseException` in `except` block

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#220]
# Rule request

## Thesis

We need to forbid `except BaseException:` handlers.

## Reasoning

We can silence system exit and keyboard interrupt with this handler. It is almost the same as raw `except:` block.

Related: https://help.semmle.com/wiki/pages/viewpage.action?pageId=1608527

**Comment by AlexArcPy** [comment]
Pushed code into my fork - could you please take a look to see if there is something wrong / more code should be added before I do a PR? Thanks!

**Comment by AlexArcPy** [comment]
@sobolevn , done!

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/commit/58cfab4a23d54d0c61d2879c161a4d2dc9985096
