### ISSUE TITLE
Add exception to WPS226 to allow commas and dots

### ISSUE THREAD

**Issue by 0anton** [wemake-services/wemake-python-styleguide#2209]
# Rule request

I suggest adding comma `,` and dot `.` to the list of allowed exceptions for WPS226

## Thesis

Forcing defining a constant for dot and comma strings worsen the code readability without need.

## Reasoning

It is a [classical](https://realpython.com/python-string-split-concatenate-join/#going-from-a-list-to-a-string-in-python-with-join) pattern to build a sentence with the code like:
```
strings = ['a', 'b', 'c']
','.join(strings)
```
It feels unnatural to define a constant (e.g. DOT, COMMA) for such obvious case.

Besides that the check WPS226 looks good. I don't like disabling it or increasing the number of string occurrences.
This extends the idea in https://github.com/wemake-services/wemake-python-styleguide/issues/1534

**Comment by sobolevn** [comment]
@0anton do you want to send a PR with the fix? 🙂

**Comment by 0anton** [comment]
Yes, sure! Just give me a couple of days for that.
