### ISSUE TITLE
Only show recommendations for files changed in a PR

### ISSUE THREAD

**Issue by ma-sadeghi** [wemake-services/wemake-python-styleguide#2239]
Is there a way to force the wemake-python-styleguide action to show recommendation only for those files that have been changed in the PR? Currently, the action log shows recommendations for the entire repo.

**Comment by sobolevn** [comment]
I guess that it can be done via https://github.com/reviewdog/reviewdog#filter-mode
We can also support this as a parameter to our action.

Contributions are welcome!

Ping to @mgrachev
