### ISSUE TITLE
Provide Flake8 4 support

### ISSUE THREAD

**Issue by dreamflasher** [wemake-services/wemake-python-styleguide#2253]
### What's wrong

`wemake-python-styleguide 0.15.3 requires flake8<4.0,>=3.7, but you have flake8 4.0.1 which is incompatible.`

### How it should be

Support flake8 4 and higher

### Flake8 version and plugins

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.7",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "21.9.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.7.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.8.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {                                                                                                                                          [16/25121]
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.15.3"
    }
  ],
  "version": "4.0.1"
}

```

### pip information

`pip 21.3.1`

pip freeze is a bit too much, how about you go for more specific packages you care about?

### OS information

Ubuntu 20 LTS

**Comment by sobolevn** [comment]
@dreamflasher can you please try to bump it? What would happen?

**Comment by dreamflasher** [comment]
Unfortunately, I can't find the version constraint. I looked into poetry.lock and pyproject.toml. Where are those defined? 
I'd assume it just works, because it works even if I have conflicting packages (and flake8 4).

**Comment by sobolevn** [comment]
https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L58

**Comment by dreamflasher** [comment]
The line you are pointing at states `flake8 = "^3.7"`. There is no upper bound to 4.0.

**Comment by sobolevn** [comment]
We can change that to `>=3.7,<5` 🙂

**Comment by dreamflasher** [comment]
Ah, I wasn't aware that poetry does automatic version constraining.

**Comment by dreamflasher** [comment]
@sobolevn May I kindly ask for a new release of wemake? We'd love to see this change being integrated in a release, currently wemake is creating build conflicts (we need flake8 4), and I would love to convince my team of wemake! :)

**Comment by sobolevn** [comment]
@dreamflasher yes! Thanks for the reminder!

I will release it before the dec.

**Comment by dreamflasher** [comment]
Amazing, thank you so much!

**Comment by webknjaz** [comment]
> Ah, I wasn't aware that poetry does automatic version constraining.

`^` is Poetry's way of implementing `~=` IIRC. So `~= 3.7` is equivalent to `>= 3.7, < 4.0`, which should be the same as `^ 3.7` in Poetry. In general, it seems to promote the ideas from npmjs and rust ecosystems assuming that every project in the world follows SemVer (which is not always the case but is true for flake8 — https://flake8.pycqa.org/en/latest/internal/releases.html#releasing-flake8).

**Comment by webknjaz** [comment]
> I will release it before the Dec.

Dec started 13 days ago FYI.
