### ISSUE TITLE
Option to promote info level to warning level

### ISSUE THREAD

**Issue by dreamflasher** [wemake-services/wemake-python-styleguide#2265]
This is not a rule request, but a feature request.

## Thesis

For example B006 has info level ("Do not use mutable data structures for argument defaults"), and we would like to have it warning level. We'd actually be fine to promote all info messages to warning level (they are good!).

## Reasoning
People have different opinions about which violations they find important enough to consider.

**Comment by sobolevn** [comment]
Hi! Thanks for the idea! 

But, looks like there's nothing we can do here. We rely on `flake8` to report all errors for us.
And it does not support warnings.

So, you can try to suggest this feature on their repo.

**Comment by dreamflasher** [comment]
Don't you determine the severity level? I get errors, warnings and info level severities from wemake.

**Comment by sobolevn** [comment]
😨 No

Can you please show me your output?

**Comment by dreamflasher** [comment]
It appears to be a VS Code thing. Nothing from the command line flake8 output shows any categories. I wonder how VS Code decides this…
