### ISSUE TITLE
[RFE] Include actual WPS code in docs

### ISSUE THREAD

**Issue by cidrblock** [wemake-services/wemake-python-styleguide#2288]
New to wemake here, great stuff.

I noticed that if I google WPS326 no good results are found, I suspect this is because in the docs, only '326' can be found.

I don't know if it's possible, but including a WPS326 somewhere might make it easier to go directly from the error I'm seeing to the docs where it is described if the WPSXXX code got picked up by a search engine.

It could go inline or even in the table up top.

Just a thought & suggestion.

Thanks for all this btw, my code is better now.

**Comment by sobolevn** [comment]
Thanks a lot! I think that we can do that.

**Comment by webknjaz** [comment]
I think it's possible to add per-document metadata for HTML keywords in RST. If this is generated from docstrings, this could go into the module-level one.

**Comment by bergerx** [comment]
I came here to create this issue to find it was created ten days ago 👍 .

The suggestion would be helpful if the search engine results for a violation code in google take me to the immediate section of the violation doc.

Currently, developers usually search the violation code in their favorite search engine, end up in a GitHub issue, trying to figure out their problem from there. I quite often try telling individuals about the https://wemake-python-stylegui.de/en/latest/pages/usage/violations/index.html page and how they should find a violation from there, either by using an in page search with just the numeric part of the violation id or by using the description text.

This educating-individuals-on-how-to-use-WSP-docs process gets even worse if your project has lots of random contributors among your company with varying levels of experience in coding/style guides/python/linters/flake8/WPS.

**Comment by sobolevn** [comment]
I have also mention other projects that do kinda similar things:
- https://flake.ale.sh/WPS332
- https://flake8.codes/WPS226

I think the proper solution to this problem would be: 
1. Adding custom `sphinx` plugin to inject proper "WPS" code to final docs. Somewhere at the top of docs. Like this:
<img width="1280" alt="Снимок экрана 2021-12-21 в 14 59 39" src="https://user-images.githubusercontent.com/4660275/146926595-29d3f034-c456-4b16-8dc4-769118736419.png">

Or maybe we can even generate unique pages for each violation. I don't know anything about sphinx plugins, so the first one seems more realistic 🙂 

2. Possibly we can also generate some `#` metadata for better navigation. Right now full urls look like https://wemake-python-stylegui.de/en/latest/pages/usage/violations/consistency.html#wemake_python_styleguide.violations.consistency.WalrusViolation Which is not readable. I can try to make it `https://wemake-python-stylegui.de/e/WPS332`

3. We can also add an option to our formatter: to show links to exact violation (not all of them, but at least `WPS` ones).

CC @anatoly-scherbakov
