### ISSUE TITLE
Do not allow `super()` without parameters in generator expressions

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#2310]
This bug: https://bugs.python.org/issue46175

We need to require `super(cls, self)` in this case.

**Comment by nasdev-cmd** [comment]
Hi ! I would like to work on this issue :)

**Comment by sobolevn** [comment]
@nasdev-cmd thank you!

**Comment by kitsiosvas** [comment]
Hello, is this issue still open?
If so, I would appreciate it greatly if I could provided with the information of where is the code linked to this behavior located.

**Comment by sobolevn** [comment]
@kitsiosvas I think that we can add this check here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/classes.py

Are you familiar with python's AST?

**Comment by kitsiosvas** [comment]
@sobolevn I am somewhat familiar with AST indeed. Are there any other similar checks that I could consult? 
I've been studying the code you included in your previous message to understand what exactly I will need to implement.
Thank you.

**Comment by kitsiosvas** [comment]
If I understand it correctly, I need to somehow check if super() exists as a node with parent a generator expression and it's kids
are not in the form you have pointed out initially (super(cls, self)).
I don't know if I am missing something. Any input is more than welcome.

**Comment by sobolevn** [comment]
Yes, sounds right!

If `super` call:
- is inside a gen expr
- and does not have two args

We raise a violation.

**Comment by sobolevn** [comment]
I would go this way:
1. Find `ast.Call` nodes, check name to be `super`
2. Check args count (it is fast and cheap)
3. Then `get_closest_parent(call, ast.GeneratorExpr)`

**Comment by kitsiosvas** [comment]
In order to get the node's name I would have to use `given_function_called(node, to_check: Container[str])` method.
What would I use as Container in this case. I couldn't find anything clear on this. Or maybe there is another way of getting the name of the node?

**Comment by sobolevn** [comment]
`given_function_called`(node, {'super'})`

**Comment by kitsiosvas** [comment]
I have implemented the feature. Should I issue a Pull Request for review?

**Comment by sobolevn** [comment]
Please! 👍

**Comment by kitsiosvas** [comment]
According to the "Raise a violation" part, I tried doing something similar to the comment https://github.com/wemake-services/wemake-python-styleguide/issues/2310#issuecomment-1023135723 , but it raises errors apparently. I couldn't figure out what is the proper way of achieving this, so far. Will keep searching, but any help is amazing.
Thank you.

**Comment by akshaybhadange** [comment]
does this issue still exists , I want to contribute in this project , actually its my first opensource contribution , so any help regarding this really appreciated

**Comment by lensvol** [comment]
Can I take this issue over?

**Comment by sobolevn** [comment]
Please!

**Comment by lensvol** [comment]
I'll do what I can.
