### ISSUE TITLE
Forbid to use names that break future versions of python

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#235]
# Rule request

## Thesis

We need to restrict usage of names like `async` and `await` in `python3.6`. Since it would be a syntax error in `python3.7`.

This should be a separate rule from `WrongVariableName`. Since it does other "warning level".

## Reasoning

It would be hard to update if you don't follow this rule.

**Comment by HassankSalim** [comment]
Can i work on this  ?

**Comment by sobolevn** [comment]
@HassankSalim sure! Feel free to ask any questions you have.

**Comment by HassankSalim** [comment]
Should i add the new rule to violations/naming.py
I am confused about where i should add the new rule

**Comment by sobolevn** [comment]
Yes, `naming.py` is an appropriate place.

**Comment by sobolevn** [comment]
Solved via http://pycodestyle.pycqa.org/en/latest/intro.html `W606`.
