### ISSUE TITLE
Violation shortlinks in the formatter

### ISSUE THREAD

**Issue by notpushkin** [wemake-services/wemake-python-styleguide#2374]
I've set up a short URL for violations at https://pyflak.es/. It works like this:

- for WPS violations, it links to the specific violation in the WPS docs: https://pyflak.es/WPS235
- for violations present on Grant McConnaughey's [Flake8 Rules][1], it links to the respective page: https://pyflak.es/E117
- for other violations, it links back to the respective Flake8 plugin docs: https://pyflak.es/D300, https://pyflak.es/RST202

[1]: https://www.flake8rules.com/

It's currently semi-manually generated and a few links are broken (which I intend to fix soon-ish).

Would you be interested in integrating this deeper with wemake-python-styleguide? For example, the `wemake` formatter could print the URLs out, for easier documentation lookup.

**Comment by sobolevn** [comment]
Totally! PR is welcome. But, please make this configurable and turned off by default.
