### ISSUE TITLE
Restrict writing `import numpy as np` when there are no name conflicts

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#238]
# Rule request

## Thesis

Some people write `import numpy as np`. Some people don't like any abbreviations for any modules except name conflicts.

## Reasoning

1. On the one hand this is very common abbreviation.
1. On the other hand this is not pythonic and goes from data science and can be used only in one-run scripts and Jupyter Notebooks.

What do you think about this? I think, we should choose one of this options for code consistency.

**Comment by sobolevn** [comment]
This rule should analyze the context of the `import .. as ...`.
If there are name conflicts we should allow `import ... as ...` statements.

Otherwise we should rise a `RedundantImportAliasViolation`.

**Comment by orsinium** [comment]
What if `as` statement used for avoiding conflict with local variable in some function? Do we need to analyze all variables in all module?

**Comment by sobolevn** [comment]
Nope, only module level variables (aka constants), other imports, classes and functions.

**Comment by BluePhoenixGame** [comment]
This rule should allow import like this `import assets.data.image as image`

**Comment by sobolevn** [comment]
@BluePhoenixGame  why not `from assets.data import image`?

**Comment by BluePhoenixGame** [comment]
Ahh, yeah.

**Comment by orsinium** [comment]
Plugin to restrict unnecessary import aliases:
[flake8-tidy-imports](https://github.com/adamchainz/flake8-tidy-imports)

**Comment by sobolevn** [comment]
We already have this rule in our linter made from ground up. Since I have missed this module when I was working on it.

But your original idea is not implemented there.

**Comment by sobolevn** [comment]
I came to realisation that this should not be disallowed. 
Why? Here's my proof.

1. You can `import numpy`
2. Then you can `np = numpy`
3. Then you can use both `numpy.` and `np.`
4. Boom!

But, when using aliases it is not possible. So, `import numpy as np` is a way to go.
