### ISSUE TITLE
609: Allow __enter__() inside an __enter__()

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#2381]
### What's wrong

One design pattern is to wrap a context manager. It would be nice to avoid WPS609 errors with this code, which seems to require accessing the direct magic methods.

### How it should be

Allow code like:
```
class Foo:
    ...

    def __enter__(self):
        self._conn.__enter__()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self._conn.__exit__(exc_type, exc_value, traceback)
```

I guess the same for aenter/aexit as well.

**Comment by sobolevn** [comment]
Yeah, I guess that calling the same magic method inside a magic method is fine.

**Comment by lensvol** [comment]
If it's not taken, then I could work on this.

**Comment by sobolevn** [comment]
Just note, that we allow calling all same magic methods. Not just `__enter__`
