### ISSUE TITLE
433: Import under try

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#2382]
### What's wrong

WPS433 seems to be given when `try`ing an import, due to it being an optional dependency.

Code I produced this on:
```
try:
    from gi.repository import GLib  # noqa: I900
except ImportError:
    runtime_dir = Path(os.environ.get("XDG_RUNTIME_DIR", "/run"))
else:
    runtime_dir = Path(GLib.get_user_runtime_dir())
```

### How it should be

No violation when import is under a `try`, but otherwise still top-level.

**Comment by sobolevn** [comment]
I agree, this is way too common.
