### ISSUE TITLE
Enforce usage of built-in types in typing.

### ISSUE THREAD

**Issue by Waszker** [wemake-services/wemake-python-styleguide#2426]
# Rule request

Python 3.9 introduced support for [PEP585](https://peps.python.org/pep-0585/) which discourages usage of the `typing.List`, `typing.Tuple`, etc. in favor of the built-in types.

## Thesis

The usage of the built-in generics should be encouraged. The usage of the generics from the `typing` module should be blocked by a rule, when using Python 3.9+ versions.

## Reasoning

I think that having two different ways to denote those types does not comply with the "There should be one -- and preferably only one -- obvious way to do it" rule.

**Comment by sobolevn** [comment]
Good idea. Does any other existing plugins support that?

**Comment by Waszker** [comment]
I looked at the `flake8` [ruleset](https://www.flake8rules.com/) and didn't find anything related to the issue.

**Comment by sobolevn** [comment]
After thinking for a while on this problem, I believe that this should be a separate plugin.

Why?
1. It might be usefull for a broader audience, wps is too strict for many people
2. It has my favourite "match by name" problem
3. It is quite complex. Typing rules are evolving quite fast, so it might be better to have it syncronized

**Comment by sobolevn** [comment]
@Waszker do you want to work on it? I am open for help!

**Comment by sobolevn** [comment]
Yesm new repo + optional dependency in wps (or even just a suggestion, some people do not use type hints at all, no need to slow them down)

**Comment by Waszker** [comment]
@sobolevn I've already prepared and released the first version of the plugin that takes care of the checks from this issue and https://github.com/wemake-services/wemake-python-styleguide/issues/2421

Link: https://github.com/Waszker/flake-type-annotations-plugin

The project is in its early stages but I was too excited to release it that I've forgot to ask for your review. :disappointed:  

Nevertheless feel free to take a look at it and I think that we can close this issue, the https://github.com/wemake-services/wemake-python-styleguide/issues/2421 one and its related PR. 

What do you think?

**Comment by sobolevn** [comment]
Great! Also check out https://github.com/python/typeshed/blob/master/tests/check_new_syntax.py
