### ISSUE TITLE
Recommend using a.removeprefix(b) instead of a[len(b):]

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#2437]
# Rule request

## Thesis

[PEP 616](https://peps.python.org/pep-0616/) (Python 3.9) introduce `str.removeprefix` and `str.removesuffix`, and this is great. We can try to detect some patterns when it can be used to simplify the existing code.

Pattern 1:

```python
if foo.startswith('bar'):
    foo = foo[3:]
```

Pattern 2:

```python
foo = foo[len('bar'):]
```

Pattern 3:

```python
if foo.startswith('bar'):
    foo = foo[len('bar'):]
```

A similar algorithm applies to `str.removesuffix`.

Note that the method is available only in Python 3.9+.

## Reasoning

1. Cleaner and shorter code
2. Less error-prone
3. Faster

See the PEP for more on motivation.

**Comment by jason0kenyon** [comment]
I agree. This is way cleaner. I can try to implement this!

**Comment by sobolevn** [comment]
In `foo[len('bar'):]` we don't know anything about `foo`.
It might be a list or some custom object.

So, I had to decline.

**Comment by orsinium** [comment]
"Will be implemented in typed-linter" 🙃 Maybe, we should integrate with mypy, like refurb.

**Comment by sobolevn** [comment]
https://docs.astral.sh/ruff/rules/slice-to-remove-prefix-or-suffix/
