### ISSUE TITLE
Forbid redundant if statements

### ISSUE THREAD

**Issue by SheldonNunes** [wemake-services/wemake-python-styleguide#244]
# Rule request
## Thesis

We should prevent if statements that use `True` or `False` without any comparison

e.g. `if True: ...` and `if False: ...`

## Reasoning

These statements don't make sense. They will either cause it to execute everytime or never. This is an error in the source code and should be forbidden

**Comment by SheldonNunes** [comment]
Happy to implement this one as it will be similar logic to #219 

:)

**Comment by sobolevn** [comment]
@SheldonNunes you are welcome. Thanks for the rule request. It is a very useful feature.
