### ISSUE TITLE
Site unavailable

### ISSUE THREAD

**Issue by vkurilin** [wemake-services/wemake-python-styleguide#2445]
### What's wrong

Not sure where exactly to put this, but  https://wemake-python-stylegui.de/ is unavailable

**Comment by sobolevn** [comment]
Yes, I cannot pay for it, because my cards are not accepted.
Another domain lost because of sactions.

There's nothing I can do about it.
I will change it at some point, sorry.

**Comment by vkurilin** [comment]
Maybe I can help with this problem :)

Wrote to mail@sobolevn.me. If mail is also unavailable, you can reach me in telegram (nickname is the same as on github)

**Comment by skarzi** [comment]
Hello,

You can always check the source code directly - https://github.com/wemake-services/wemake-python-styleguide/tree/master/wemake_python_styleguide/violations
There is also a few useful community tools e.g. [flake8.codes](https://flake8.codes) that allow you to preview flake8 codes.

**Comment by Day0Dreamer** [comment]
Can't find [D208] Docstring is over-indented

**Comment by skarzi** [comment]
@Day0Dreamer `D###` flake8 codes are produced by https://github.com/PyCQA/pydocstyle.
List of `pydocstyle` codes: http://www.pydocstyle.org/en/stable/error_codes.html.

**Comment by suharnikov** [comment]
@sobolevn how can the community help?

**Comment by sobolevn** [comment]
https://wemake-python-styleguide.rtfd.io 🎉

**Comment by sobolevn** [comment]
Thanks everyone for their help 🙂
