### ISSUE TITLE
Link to documentation website does not work

### ISSUE THREAD

**Issue by mpibpc-mroose** [wemake-services/wemake-python-styleguide#2451]
### What's wrong

When trying to access the given URL for the main documentation [https://wemake-python-stylegui.de]( https://wemake-python-stylegui.de) I get an DNS error. Trying to resolve via `dig` gives as NXDOMAIN

```
> dig wemake-python-stylegui.de

; <<>> DiG 9.11.3-1ubuntu1.17-Ubuntu <<>> wemake-python-stylegui.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9231
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;wemake-python-stylegui.de.     IN      A

;; AUTHORITY SECTION:
de.                     3548    IN      SOA     f.nic.de. dns-operations.denic.de. 1657778259 7200 7200 3600000 7200

;; Query time: 0 msec
;; SERVER: 178.254.16.141#53(178.254.16.141)
;; WHEN: Thu Jul 14 07:59:34 CEST 2022
;; MSG SIZE  rcvd: 117
```

### How it should be

DNS should resolve and website should be accessible

### Flake8 version and plugins

not relevant

### pip information

not relevant

### OS information

not relevant

**Comment by sobolevn** [comment]
Please, use https://wemake-python-styleguide.rtfd.io
See #2445
