### ISSUE TITLE
Bump flake8 to v5

### ISSUE THREAD

**Issue by sathieu** [wemake-services/wemake-python-styleguide#2483]
### What's wrong

Trying to bump flake8 [fails](https://gitlab.com/kubitus-project/kubitus-ingress-operator/-/jobs/2919005690#L1102) with:

```wemake-python-styleguide 0.16.1 depends on flake8<5 and >=3.7```

### How it should be

Please allow installation with flake v5.

### Flake8 version and plugins

{}

### pip information

...

### OS information

...

**Comment by sathieu** [comment]
This was done by #2254. @sobolevn Is there a planned release?

**Comment by witekio-kwe** [comment]
This isn't done, it just allows flake 4.x releases - but latest 5.0.4 will be still not installable
