### ISSUE TITLE
Offer built-in rules standalone

### ISSUE THREAD

**Issue by PeterJCLaw** [wemake-services/wemake-python-styleguide#2497]
This package of lints is great, however it adds quite a lot of dependencies into projects which may only want a small number of the rules available here. (Many of which aren't available elsewhere).

Would you be open to offering the core rules as their own package, separate from the dependencies? (I'm assuming that most of the dependencies aren't actually runtime requirements, but instead are dependencies so they're pulled in for convenience).

I can think of a number of ways this could be expressed, either as a separate package or by moving the dependencies to an "extras" requirement on this package. The latter would be sort-of breaking (users who want everything would need to install `wemake-python-styleguide[all]` or similar rather than just `wemake-python-styleguide`), but is likely to be simpler to maintain.

**Comment by sobolevn** [comment]
This would be a breaking change.
Moreover, we use some deps in our source code. 

However, I am 100% open to `wemake-python-styleguide[plain]` if that is going to work.

**Comment by PeterJCLaw** [comment]
> This would be a breaking change.

Yeah, if we went the `wemake-python-styleguide[all]` route it would be.

The alternative would be to hoist the rules to a separate package (even if in the same repo), which could even install to the same package location if desired. It should be possible to do that in a manner that's completely transparent to consumers.

> Moreover, we use some deps in our source code.

I'm not suggesting that code dependencies are moved out! This is just about the dependencies which purely present to pull the linters in for flake8 to auto-discover.
From a very quick search of the code it looks like the majority aren't directly imported -- the only one I can see being directly used is `flake8_quotes` (and `flake8` itself of course). Are there others I've missed?

> However, I am 100% open to `wemake-python-styleguide[plain]` if that is going to work.

I'll have a look, but unfortunately I don't think there's a way for an "extras" package to have _fewer_ dependencies than the core package.

**Comment by sobolevn** [comment]
I generally like this idea! If you have the time to send a PR I would be glad to review it :)

**Comment by PeterJCLaw** [comment]
I had a quick look at which packages are actually needed just now; noting down the results to save future me some time -- it's currently `pip install 'flake8<5' flake8-quotes attrs pep8-naming astor pygments`.

However flake8 v5 does also seem to work.

**Comment by sobolevn** [comment]
Yes, looks like it is very close to be true :)

**Comment by PeterJCLaw** [comment]
I've had a bit of a play with the options here and I've not found a combination which allows this change to be completely non-breaking, depending on where breakage is allowed or not.

The various spellings I can think of are:

1. Use package extras for the bonus dependencies
    This is breaking in the obvious sense that existing users will need to change how they install the package. However it is otherwise by far the simplest solution is probably the easiest from an ongoing maintenance perspective.
2. New meta-package
    This is approximately equal to 1. except that it's _maybe_ a tiny bit easier to tell people "use `wemake-styleguide` instead of `wemake-python-styleguide` now" (rather than `wemake-python-styleguide[all]` being the new spelling, where the `[all]` is easy to forget)
3. New rules sub-package with its own name
    Pulling out the rules to their own package would involve renaming them and the various entry points. Any consumer which uses the entry points or imports the code directly would need to make changes. This is also pretty simple as a change and has minimal ongoing maintenance overhead, though would involve a bunch of changes to put in place and likely also breaks in-flight PRs etc.
4. New rules sub-package which installs the current name (parent package installs nothing)
    This is the one I'd hoped would be achievable as it hints at less breakage. In theory I'd hoped to pull out a new `wemake-python-styleguide-rules` package which actually installed the `wemake_python_styleguide` files, along with the entry points for discovery by e.g: `flake8`, leaving the existing `wemake-python-styleguide` as a meta package which didn't install any actual python files.
    However I was unable to make this work. I'm not sure how much of this was my limited understanding of `pyproject.toml`/`poetry` as I had thought I'd seen other packages which behaved _like_ this elsewhere, though it's possible I imagined that and/or there are differences here which make it not work. I suspect that the presence of the entry points is a significant complication here, but I've not dug enough to be sure.
   I also suspect that this setup would be likely to have maintenance overhead in the future just by virtue of it being a bit contrived and counter to the usual way that python packages behave.

From what I can tell `wemake-python-styleguide[plain]` isn't a thing that can work -- package "extras" are always additive.

With all this in mind I think one of 1, 2 or 3 are the way to go here depending on how much and what kinds of breakage this project is willing to accept. As noted, while they're each technically breaking in the short term, I think they're better options in the long term than 4 anyway.

**Comment by sobolevn** [comment]
> New rules sub-package with its own name
> Pulling out the rules to their own package would involve renaming them and the various entry points. Any consumer which uses the entry points or imports the code directly would need to make changes.

I think it is good enough. We don't expect anyone to directly import anything from our code base.

And we even state that in `CHANGELOG.md`: we only care about CLI usage.

**Comment by PeterJCLaw** [comment]
For info: I'm not sure I'm likely to get to this in the immediate future. I'm still interested in this happening (and may eventually have time to work on it), but wanted to clarify in case others were interested in working on this.

**Comment by sobolevn** [comment]
they are now!
