### ISSUE TITLE
"remake-python-stylegui.de" domain no longer available

### ISSUE THREAD

**Issue by cyyc1** [wemake-services/wemake-python-styleguide#2503]
### What's wrong

Whenever we click the "https://pyflak.es/WPS***" link, we got redirected to http://remake-python-stylegui.de

And the webpage says the domain is no longer available.

Can someone change the redirection to the readthedocs.io domain?

### How it should be

N/A

### Flake8 version and plugins

N/A

### pip information

N/A

### OS information

N/A

**Comment by sobolevn** [comment]
There's nothing we can do on out side: [https://pyflak.es](https://pyflak.es/WPS) is a 3rd party project.

CC @notpushkin

**Comment by cyyc1** [comment]
Since you control the "show-violation-links" option, maybe you can temporarily show the readthedocs.io links instead of the pyflak.es links, until the domain name issue is fixed?

**Comment by cyyc1** [comment]
Otherwise first time users of WPS may get very confused.

**Comment by notpushkin** [comment]
No worries, I'll update the redirects in a couple hours. ✨

**Comment by sobolevn** [comment]
Thanks a lot! 👍

**Comment by notpushkin** [comment]
Okay, the links should work now: https://pyflak.es/WPS231

**Comment by sobolevn** [comment]
It works indeed! Thanks a lot for the quick fix.

**Comment by cyyc1** [comment]
Hi @sobolevn and @notpushkin , I found one link that doesn't point to the expected place: https://pyflak.es/WPS463

On my computer, it points to https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes rather than WPS's actual doc.

Could either one of you look into this? Thank you!

**Comment by notpushkin** [comment]
@cyyc1 Looks like I need to regenerate the list of redirects. Sadly, my script that did that is on a laptop in another country right now :') I'll see if I can quickly hack something together later today.

**Comment by notpushkin** [comment]
That was quick and [most certainly dirty](https://gist.github.com/notpushkin/f04466c3010973d8b99f2ce8d148dbaa). (I wonder if we can bring it up to the wemake standards :-)

https://pyflak.es/WPS463 works now, let me know if you see any other dead links!

**Comment by cyyc1** [comment]
Thanks @notpushkin !  I can confirm that https://pyflak.es/WPS463 works now.

I'll report to this issue if I see any other dead links.
