### ISSUE TITLE
Require one blank line after if/for/while blocks

### ISSUE THREAD

**Issue by cyyc1** [wemake-services/wemake-python-styleguide#2505]
# Rule request

Require one blank line after if/for/while blocks

## Thesis

Here is my proposal:

Wrong:
```python
some_list = []
child_list = []

for _ in range(2):
    for jj in range(3):
        child_list.append(jj)
    some_list.append(child_list)  # no blank line before this line
print(some_list)  # no blank line before this line
```

Recommended:
```python
some_list = []
child_list = []

for _ in range(2):
    for jj in range(3):
        child_list.append(jj)

    some_list.append(child_list)

print(some_list)
```

## Reasoning

Because Python uses  indentation to indicate code structure rather than `{}`, when we accidentally add or remove one level of indentation we could introduce some very nasty bugs that are difficult to find. Also the "wrong" example above is not that readable.

Therefore by requiring one blank line between levels, we not only improve readability and also reduce chances of errors.

**Comment by Patelrahul4884** [comment]
@cyyc1 in whole project we have to do this right?

**Comment by cyyc1** [comment]
Never mind. I implemented this request as a standalone tool here: https://github.com/cyyc1/flake8-clean-block

**Comment by sobolevn** [comment]
Awesome! Great work! 🎉
