### ISSUE TITLE
WPS420: "pass" keyword being used in custom exception

### ISSUE THREAD

**Issue by cyyc1** [wemake-services/wemake-python-styleguide#2507]
### What's wrong

When I define my custom exception such as 
```python
class MyException(Exception):
    pass
```
the linter throws WPS420.

This is exactly what I need from a custom exception. I don't need anything else so I put a `pass`.

### How it should be

Is it possible to ignore this checking when we are defining custom exceptions?

Or if there is indeed better practice, is it possible to put that into the doc?

### Flake8 version and plugins

N/A

### pip information

N/A

### OS information

N/A

**Comment by sobolevn** [comment]
It should be:

```python
class MyException(Exception):
    """Why do you need this exception? Where is it used?"""
```
