### ISSUE TITLE
Publish new vesrion with flake8 v5 support.

### ISSUE THREAD

**Issue by codeleta** [wemake-services/wemake-python-styleguide#2514]
# Rule request

Publish new vesrion with flake8 v5 support.

## Thesis

You made flake8 v5 support.
Can you make a tag and publish it?

## Reasoning

I want update flake8 and can't do this.

**Comment by codeleta** [comment]
Oh I see. Thanks for answer.

**Comment by okainov** [comment]
+1 would really love to have new version with flake8 5.x support...

**Comment by okainov** [comment]
Any update on this @sobolevn ? More than a month has already passed, when do you expect creation of new release?

**Comment by sobolevn** [comment]
It still does not work. flake5 is broken, sorry.

**Comment by okainov** [comment]
@sobolevn is there some open issue for the problem? Tried to briefly search, but didn't find anything really... Because from #2518 it looks like fully implemented and working (it wasn't reverted neither), could you please kindly point to what exactly is broken?

**Comment by sobolevn** [comment]
Here you go: https://github.com/PyCQA/flake8/issues?q=is%3Aissue+importlib+is%3Aclosed

**Comment by okainov** [comment]
Everything is closed there :) So I think everything is fixed?

**Comment by sobolevn** [comment]
Please, trying reading them: they are all closed as "won't fix".

**Comment by okainov** [comment]
Well, I did read them. The most discussed/making sense issue looks like this one https://github.com/PyCQA/flake8/issues/1701

And as maintainers indeed mentioned, submitter does use (very) out-of-date flake8 version. And that's indeed "won't fix", one cannot argue with that.

What I tried manually just to see what's happening is to run in clean Python 3.9 container `pip install importlib_metadata` (which installs 5.x) and then `pip install flake8` (which doesn't install any importlib_metadata and installs `flake8==5.0.4`). Then running `flake8` on some dummy files and it seemed fine, no crashes. And that's exactly why I'm asking - what is considered "broken" here? I'd be happy to submit (one more) issue to `flake8`, but I don't even see the issue, it looks working fine.

```
root@a7afcc18ba85:/# pip freeze
flake8==5.0.4
importlib-metadata==5.0.0
mccabe==0.7.0
pycodestyle==2.9.1
pyflakes==2.5.0
zipp==3.10.0
root@a7afcc18ba85:/# flake8 --version
5.0.4 (mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.9.15 on Linux
```

**Comment by okainov** [comment]
BTW `flake8` 6.x was recently released...

**Comment by dakotahorstman** [comment]
@okainov  I'm running into this as well. Seems like @sobolevn either had something come up or he's just decided to stop maintaining the codebase. Considering his vague and unhelpful responses to you, I can't help but think the latter.

**Comment by dreamflasher** [comment]
@sobolevn What if @okainov or someone else would make a PR with flake8 v6 that passes all tests, would you accept that PR?

**Comment by okainov** [comment]
Okay, looks like this is becoming the second `rapidjson` with the maintainer  @sobolevn being incredibly resistant to publish new releases for noone-knows-why reason. Seems like we need to find an alternative or just go away from using this tool as this problem explicitly blocks users of new versions.

**Comment by dreamflasher** [comment]
Idk what happened at rapidjson, but here it just looks like he's currently not working on the project anymore? I don't see any commits for the past 4 months. The big question is... will he ever be back?

**Comment by dreamflasher** [comment]
Welcome back @sobolevn :) Would you be open for a PR that passes all tests and provides Flake8 v6 compatability?

**Comment by positron96** [comment]
Just wanted to add that currently this project cannot be used with Flake8 VSCode plugin. The oldest version of plugin that can be installed (2022.6.0) requires flake8>=5.0.0

**Comment by Day0Dreamer** [comment]
@dreamflasher - Do you have a fork I can use? 

I'm afraid the noone-knows-why reason, @okainov mentioned, won't go away for the duration of 2023.

I'm looking forward to keep using the updated version of this great tool. Got to keep the wheel turning

**Comment by dreamflasher** [comment]
I stopped using wemake. As @sobolevn is back and working on PRs, but not responding here/not working on this issue, I also doubt this will be resolved any time soon. 
I'd appreciate a lot if you create a fork that works with current dependencies!

**Comment by Day0Dreamer** [comment]
@dreamflasher it would look like @sobolevn is plowing through the backlog. We've got to be patient. <3

**Comment by dolfinus** [comment]
Finally https://github.com/wemake-services/wemake-python-styleguide/releases/tag/0.18.0

**Comment by dreamflasher** [comment]
Thank you very much @sobolevn !
