### ISSUE TITLE
Docs: change the recommendation to use flakehell (not maintainable) -> flakeheaven

### ISSUE THREAD

**Issue by blablatdinov** [wemake-services/wemake-python-styleguide#2519]
### What's wrong

WPS recommend using `flakehell` for legacy codebase, but [flakehell](https://github.com/flakehell/flakehell) not supported. [Discussion](https://github.com/flakehell/flakehell/issues/30) about archiving the repository.

May be change recomendation to [flakeheaven](https://github.com/flakeheaven/flakeheaven)?

### How it should be

N/A

### Flake8 version and plugins

N/A

### pip information

N/A

### OS information

N/A

**Comment by sobolevn** [comment]
Yes, looks fine!
