### ISSUE TITLE
WPS226: Ignore use of ellipsis constant ('...')

### ISSUE THREAD

**Issue by hgylfason** [wemake-services/wemake-python-styleguide#2545]
# Rule request

## Thesis
It's very common to use ellipsis (`...`) to indicate a string output has been shortened.
I'm using the `textwrap` utility module from Python and you quickly break the rule WPS226
that prevents literal overuse.

Here is a contrived example:

```python
import textwrap

def __str__(self):
    return textwrap.shorten(
        text='{0}'.format(
            self.question.text,
        ),
        width=40,
        placeholder='...',
    )

```

## Reasoning
I think ellipsis '...' is a known concept and as a literal would not degrade the readability of the code.

**Comment by sobolevn** [comment]
Ok, seems reasonable. Please, send a PR

**Comment by hgylfason** [comment]
Will do 👍
