### ISSUE TITLE
Restrict the maximum number of base classes aka mixins

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#264]
# Rule request

## Thesis

There are use cases that promote putting too many bases classes for your class:

```python
class SnippetList(mixins.ListModelMixin,
                  mixins.CreateModelMixin,
                  mixins.DetailModelMixin,
                  mixins.DeleteModelMixin,
                  generics.GenericAPIView):
```

We need to restrict classes with too many base classes as too complex ones.
We also need to provide an option with reasonable default to make this rule configurable.

I guess `3` should be the default value. But I am open to any other suggestions.

## Reasoning

It is almost never possible to navigate to the desired method of a parent class when you need it with multiple mixins.

It is hard to understand `mro` and `super` calls. Do not overuse this technique.

**Comment by sobolevn** [comment]
@novikovfred will this issue be interesting to you?

**Comment by novikovfred** [comment]
@sobolevn ye, I'll do it
