### ISSUE TITLE
Restrict unicode names

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#267]
# Rule request

## Thesis

Currently we can do something like this:

```python
никита = 'sobolev'
```

We can use unicode to create variables!
We can even do bizarre things like `Ø: Set[str] = set()`.

## Reasoning

This should be forbidden for sanity and readability.

**Comment by riyasyash** [comment]
I can work on this :)

**Comment by sobolevn** [comment]
@riyasyash awesome!
