### ISSUE TITLE
Can't install both flakeheaven and wemake-python-styleguide with poetry

### ISSUE THREAD

**Issue by urtow** [wemake-services/wemake-python-styleguide#2708]
### What's wrong

poetry add --group=dev wemake-python-styleguide

Using version ^0.18.0 for wemake-python-styleguide

Updating dependencies
Resolving dependencies... (3.4s)

Because no versions of wemake-python-styleguide match >0.18.0,<0.19.0
 and wemake-python-styleguide (0.18.0) depends on flake8 (>5), wemake-python-styleguide (>=0.18.0,<0.19.0) requires flake8 (>5).
And because flakeheaven (3.3.0) depends on flake8 (>=4.0.1,<5.0.0)
 and no versions of flakeheaven match >3.3.0,<4.0.0, wemake-python-styleguide (>=0.18.0,<0.19.0) is incompatible with flakeheaven (>=3.3.0,<4.0.0).
So, because price-predictor-v3 depends on both flakeheaven (^3.3.0) and wemake-python-styleguide (^0.18.0), version solving failed.

### How it should be

Both installed

### Flake8 version and plugins

flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.1",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8_implicit_str_concat",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "pylint",
      "version": "0.0.0"
    }
  ],
  "version": "4.0.1"
}

### pip information

pip --version && pip freeze

aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
build==0.10.0
CacheControl==0.12.14
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cleo==2.0.1
crashtest==0.4.1
distlib==0.3.7
dulwich==0.21.5
exceptiongroup==1.1.3
filelock==3.12.2
frozenlist==1.4.0
html5lib==1.1
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
installer==0.7.0
jaraco.classes==3.3.0
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
keyring==23.13.1
lockfile==0.12.2
MarkupSafe==2.1.3
marshmallow==3.20.1
mccabe==0.6.1
more-itertools==10.1.0
msgpack==1.0.5
multidict==6.0.4
packageurl-python==0.11.2
packaging==23.1
pexpect==4.8.0
pkginfo==1.9.6
platformdirs==3.10.0
poetry==1.5.1
poetry-core==1.6.1
poetry-plugin-export==1.4.0
ptyprocess==0.7.0
pycparser==2.21
pyproject_hooks==1.0.0
rapidfuzz==2.15.1
referencing==0.30.2
requests==2.31.0
requests-toolbelt==1.0.0
rpds-py==0.9.2
shellingham==1.5.1
six==1.16.0
tomli==2.0.1
tomlkit==0.12.1
trove-classifiers==2023.8.7
urllib3==1.26.16
virtualenv==20.24.3
webencodings==0.5.1
xattr==0.10.1
zipp==3.16.2

### OS information

uname -a
Darwin dbirukov 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by urtow** [comment]
Oops there is no mainteiner for flakeheaven:

https://github.com/flakeheaven/flakeheaven/issues/132

**Comment by blablatdinov** [comment]
@urtow you're right flakeheaven is not supported. We replace `flakeheaven` recommendation to `ondivi`

ref: #2975
