### ISSUE TITLE
Restrict variable names with more than one consecutive underscore

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#271]
# Rule request

## Thesis

Currently it is possible to name your variables like: `some__value`. This should be forbidden.

Mind, that `__magic__` variables can still be used.

## Reasoning

This is done to gain extra readability. This naming rule already exist for module names.

**Comment by Roxe322** [comment]
Can I take it?

**Comment by sobolevn** [comment]
@Roxe322 sure!

**Comment by Roxe322** [comment]
@sobolevn Hello! I've created some tests in `test_variable_names.py` and added some logics to `/logics/variables.py` but now I have `Z202 Found too many module members` in both of files. How can I solve this and then where I should add my logics and tests if it is a part of naming rules?

**Comment by sobolevn** [comment]
Test can be created in a new filed named `test_protected_variable.py`.
And logic can be refactored like this:
1. create a package instead of a single module named `variables`
2. create required modules
3. place a new function in the appropriate module

**Comment by Roxe322** [comment]
Thank you, will work on this
