### ISSUE TITLE
Add flake8-noqa

### ISSUE THREAD

**Issue by urtow** [wemake-services/wemake-python-styleguide#2719]
# Rule request

As discussed in https://github.com/wemake-services/wemake-python-styleguide/issues/165#issue-365243023
May be add https://github.com/plinss/flake8-noqa?

## Thesis

Remove violation noqa after refractoring or old code

## Reasoning

Be strict also in noqa usage

**Comment by sobolevn** [comment]
It will be hard to do since we now also use ruff.
