### ISSUE TITLE
Forbid importing protected names

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#273]
# Rule request

## Thesis

We need to restrict import like:

```python
from test import _protected
from test._protected import run
```

This rule looks quite the same as #272 but it is a separate rule.

## Reasoning

We should not use protected modules and names. It is not guaranteed to work as we want it to work.

**Comment by janakrajchadha** [comment]
How would you describe a protected module?
Can you give a deeper picture here?

**Comment by sobolevn** [comment]
There are some use-cases when people create files like `_compat.py`.
This way they indicate that this module should not be touched by other developer.

And you have to be careful when using it. That's what I call "a protected module".

**Comment by ming060** [comment]
Hi, I would like to try on this.

**Comment by sobolevn** [comment]
@ming060 I would be happy to merge it!

**Comment by ming060** [comment]
@sobolevn I also forked to do this. And I already spent some time working on it and done.
Could I also create a PR and gain some feedback to see whether my works are right on this.
Because I saw @vsmaxim created the PR.

**Comment by sobolevn** [comment]
@ming060, sure! I will review your code as well. And will merge the better one. Sounds fair to me.

**Comment by ming060** [comment]
@sobolevn, Great, I will do that. I already saw lots difference between our changes. And I am not sure which one is better. I look forward to gaining the feedback. Thanks.
