### ISSUE TITLE
Feature: update poetry

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#274]
We now have a new shiny `poetry` release.

Update guide: https://poetry.eustace.io/blog/poetry-0-12-0-is-out.html

Special note:

```
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

What we need to do:
1. Replace old lock file with the new one
2. Add `[build-system]` section to `pyproject.toml`
3. Add `Project-URL` support to show two links (docs and github) on `pypi.org`, see [reference](https://github.com/sdispater/poetry/blob/master/pyproject.toml#L12-L14), 
 [tests](https://github.com/sdispater/poetry/blob/2f2cec03b6b14e882522f7f6042ecdafebda2ca5/tests/masonry/builders/test_sdist.py#L132) and result: https://pypi.org/project/poetry/
4. Remove `poetry develop` command from `travis.yml` and `CONTRIBUTING.md`, now `poetry install` does everything we need

**Comment by sobolevn** [comment]
Green light! https://github.com/dependabot/dependabot-core/pull/704/files

**Comment by sobolevn** [comment]
We still have to wait for https://github.com/dependabot/dependabot-core/pull/705

**Comment by VetoS88** [comment]
I will take it
