### ISSUE TITLE
Pydocstyle is no longer maintained

### ISSUE THREAD

**Issue by vnmabus** [wemake-services/wemake-python-styleguide#2773]
It appears that [pydocstyle](https://github.com/pycqa/pydocstyle), the tool underlying [flake8-docstrings](https://github.com/PyCQA/flake8-docstrings) has been deprecated in favor of [ruff](https://github.com/astral-sh/ruff) (https://github.com/PyCQA/pydocstyle/pull/658). Thus, this dependency should probably be changed in the future.

Also, maybe it would be interesting to explore if/how this project can be changed to use ruff in the future, as it seems to be gaining traction.

**Comment by notpushkin** [comment]
Tangential: I'm trying out [the following config](https://gist.github.com/notpushkin/9dba2cf93c800919d32a569e71d1c29a) for Ruff + wemake on a new project. I'll let you know how it goes!

**Comment by sobolevn** [comment]
It is now removed. Using `ruff` now.
