### ISSUE TITLE
WPS473 is counted lines containing concatenated strings as empty.

### ISSUE THREAD

**Issue by vnmabus** [wemake-services/wemake-python-styleguide#2787]
### What's wrong

The following code raises WPS473, even though there are no empty lines:
```python
def kk() -> None:
    raise ValueError(
        "This is "
        "a very "
        "long message "
        "but there are "
        "no empty lines.",
    )
```

This is because it is counting the lines containing part of the string as empty.

### How it should be

These lines should not be counted as empty at all.

### Flake8 version and plugins

{
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.11.5",
    "system": "Linux"
  },
  "plugins": [
    {
      "plugin": "darglint",
      "version": "1.8.1"
    },
    {
      "plugin": "flake8-bandit",
      "version": "4.1.1"
    },
    {
      "plugin": "flake8-broken-line",
      "version": "1.0.0"
    },
    {
      "plugin": "flake8-bugbear",
      "version": "23.9.16"
    },
    {
      "plugin": "flake8-commas",
      "version": "2.1.0"
    },
    {
      "plugin": "flake8-comprehensions",
      "version": "3.14.0"
    },
    {
      "plugin": "flake8-debugger",
      "version": "4.1.2"
    },
    {
      "plugin": "flake8-docstrings",
      "version": "1.7.0"
    },
    {
      "plugin": "flake8-eradicate",
      "version": "1.5.0"
    },
    {
      "plugin": "flake8-isort",
      "version": "6.1.0"
    },
    {
      "plugin": "flake8-quotes",
      "version": "3.3.2"
    },
    {
      "plugin": "flake8-rst-docstrings",
      "version": "0.3.0"
    },
    {
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "plugin": "mccabe",
      "version": "0.7.0"
    },
    {
      "plugin": "pep8-naming",
      "version": "0.13.3"
    },
    {
      "plugin": "pycodestyle",
      "version": "2.11.1"
    },
    {
      "plugin": "pyflakes",
      "version": "3.1.0"
    },
    {
      "plugin": "wemake-python-styleguide",
      "version": "0.18.0"
    }
  ],
  "version": "6.1.0"
}

### pip information

pip 23.2.1 from .../lib/python3.11/site-packages/pip (python 3.11)
accessible-pygments==0.0.4
alabaster==0.7.13
anyio==4.0.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array-api-compat==1.4
arrow==1.3.0
astor==0.8.1
asttokens==2.4.0
attrs==23.1.0
Babel==2.13.0
backcall==0.2.0
bandit==1.7.5
basemap-data==1.3.2
basemap-data-hires==1.3.2
beautifulsoup4==4.12.2
bleach==6.1.0
build==1.0.3
cairocffi==1.6.1
Cartopy==0.22.0
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.0
cloudpickle==3.0.0
comm==0.1.4
contourpy==1.2.0
coverage==7.3.2
cycler==0.12.1
Cython==3.0.5
darglint==1.8.1
dcor==0.6
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
docutils==0.20.1
doit==0.36.0
eradicate==2.3.0
executing==2.0.0
fastjsonschema==2.18.1
fdasrsf==2.4.3
findiff==0.10.0
flake8==6.1.0
flake8-bandit==4.1.1
flake8-broken-line==1.0.0
flake8-bugbear==23.9.16
flake8-commas==2.1.0
flake8-comprehensions==3.14.0
flake8-debugger==4.1.2
flake8-docstrings==1.7.0
flake8-eradicate==1.5.0
flake8-isort==6.1.0
flake8-quotes==3.3.2
flake8-rst-docstrings==0.3.0
flake8-string-format==0.3.0
fonttools==4.44.0
fqdn==1.5.1
gitdb==4.0.11
GitPython==3.1.40
idna==3.4
igraph==0.11.2
imagesize==1.4.1
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.25.2
ipython==8.16.1
ipywidgets==8.1.1
isoduration==20.11.0
isort==5.12.0
jedi==0.19.1
Jinja2==3.1.2
joblib==1.3.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
jupyter-events==0.8.0
jupyter-sphinx==0.4.0
jupyter_client==8.4.0
jupyter_core==5.4.0
jupyter_server==2.8.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0
jupyterlite-core==0.1.3
jupyterlite-pyodide-kernel==0.1.3
jupyterlite-sphinx==0.9.3
kiwisolver==1.4.5
latexcodec==2.0.1
lazy_loader==0.3
line-profiler==4.1.1
llvmlite==0.41.0
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.1
matplotlib-inline==0.1.6
mccabe==0.7.0
mdit-py-plugins==0.4.0
mdurl==0.1.2
mistune==3.0.2
mpmath==1.3.0
multimethod==1.10
mypy==1.7.1
mypy-extensions==1.0.0
myst-parser==2.0.0
nbclient==0.8.0
nbconvert==7.9.2
nbformat==5.9.2
nest-asyncio==1.5.8
networkx==3.2.1
numba==0.58.1
numpy==1.26.1
overrides==7.4.0
packaging==23.1
pandas==2.1.2
pandocfilters==1.5.0
parso==0.8.3
patsy==0.5.3
pbr==5.11.1
pep8-naming==0.13.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.1.0
pkginfo==1.9.6
platformdirs==3.11.0
pluggy==1.3.0
polytope==0.2.4
prometheus-client==0.17.1
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pybtex==0.24.0
pybtex-docutils==1.0.3
pycodestyle==2.11.1
pycparser==2.21
pydata-sphinx-theme==0.14.1
pydocstyle==6.3.0
pyflakes==3.1.0
Pygments==2.16.1
pyinstrument==4.5.3
pyparsing==3.1.1
pyproj==3.6.1
pyproject_hooks==1.0.0
pyshp==2.3.1
pytest==7.4.3
pytest-cov==4.1.0
pytest-env==1.1.1
pytest-subtests==0.11.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
-e git+https://github.com/vnmabus/rdata.git@4dd2ea5a0f0094cae7d4a869870129dab2d4b3e0#egg=rdata
referencing==0.30.2
requests==2.31.0
restructuredtext-lint==1.4.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.6.0
rpds-py==0.10.6
scikit-datasets==0.2.4
-e git+https://github.com/GAA-UAM/scikit-fda.git@45e594c142b8a6222fdd00fbd54b85b8b0743db6#egg=scikit_fda
scikit-learn==1.3.2
scipy==1.10.1
Send2Trash==1.8.2
shapely==2.0.2
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.6
sphinx-gallery==0.14.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-bibtex==2.6.1
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sphobjinv==2.3.1
stack-data==0.6.3
stevedore==5.1.0
sympy==1.12
terminado==0.17.1
texttable==1.7.0
threadpoolctl==3.2.0
tinycss2==1.2.1
tornado==6.3.3
tqdm==4.66.1
traitlets==5.11.2
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzdata==2023.3
uri-template==1.3.0
urllib3==2.0.6
wcwidth==0.2.8
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.4
wemake-python-styleguide==0.18.0
widgetsnbextension==4.0.9
xarray==2023.10.1
zipp==3.17.0

### OS information

Ubuntu 18.04.6 LTS

**Comment by blablatdinov** [comment]
@vnmabus Thank you for contribution! You're right it's invalid behaviour. I'd prefer concatenate strings via `join`:

```python
def kk() -> None:
    raise ValueError(" ".join([
        "This is",
        "a very",
        "long message",
        "but there are",
        "no empty lines.",
    ]))
```

I'll prepare a fix for your case.
