### ISSUE TITLE
Restrict too long module names

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#289]
# Rule request

## Thesis

We should forbid too long module names. This rule is an absolute opposite of `TooShortModuleName`.

Module names like `this_is_clearly_a_very_long_for_a_single_module_name_ist_it.py` should be restricted.

This rule must be configurable. I am not quite sure about the maximum length right now.
Maybe it should be `29`?

## Reasoning

The same as #288

**Comment by vsmaxim** [comment]
I would be glad to work on this
