### ISSUE TITLE
Flakehean not maintained

### ISSUE THREAD

**Issue by blablatdinov** [wemake-services/wemake-python-styleguide#2974]
# Rule request

Insert a recommendation in the documentation to use [ondivi](https://github.com/blablatdinov/ondivi) for legacy codebases

## Reasoning

Flakeheaven not supported https://github.com/flakeheaven/flakeheaven/issues/132

ref: https://github.com/wemake-services/wemake-python-styleguide/issues/2708

**Comment by sobolevn** [comment]
Ok, the second one dead :(
