### ISSUE TITLE
Version 0.0.2 can't be used with pip

### ISSUE THREAD

**Issue by vergeev** [wemake-services/wemake-python-styleguide#30]
In some cases on line
```
node_parent = getattr(node, 'parent')
```
of `WrongModuleMetadataVisitor` we get
```
AttributeError: 'Assign' object has no attribute 'parent'
```

The bug can be fixed by the correct usage of `getattr`: 
```
node_parent = getattr(node, 'parent', None)
```

The PR with the fix and a regression test will be ready in a day.

**Comment by vergeev** [comment]
Sorry, the issue turned out to be a little bit more complex. Will do in a week

**Comment by vergeev** [comment]
OK, this is going to take a while, some I'm sharing here what I found so far.

### The problem
The `AttributeError: 'Assign' object has no attribute 'parent'` arises  not due to the fact that the visitor expects every node to have a parent, it's that _all nodes_ don't have parents.

### Steps to reproduce
The only way to reproduce the problem seems to be installing the package with `pip`, not `poetry`.  Then `flake8 .` will raise the error.

**Comment by sobolevn** [comment]
Ok, I will try to figure this out on weekends.
