### ISSUE TITLE
[docs] say that both `i-control-code` and `i-dont-control-code` are both `True` by default

### ISSUE THREAD

**Issue by webknjaz** [wemake-services/wemake-python-styleguide#3059]
### What's wrong

$sbj is confusing. Which is it?

### How it should be

https://wemake-python-styleguide.rtfd.io/en/latest/pages/usage/configuration.html should not claim two opposite things being true.

### Flake8 version and plugins

N/A

### pip information

N/A

### OS information

N/A

**Comment by sobolevn** [comment]
Thanks!

@nifadyev, are you interested in working on this?

**Comment by sobolevn** [comment]
By default we assume that people control their code :)

**Comment by webknjaz** [comment]
But the explanation refers to the calling code, not the one being linted, eh?

**Comment by sobolevn** [comment]
Right, this also needs to be clarified. Thanks!

**Comment by sobolevn** [comment]
The idea is that you use `--i-control-code=False` when you write a library for others. That's why you can add some extra features that are not recommended in a regular setup, when there's just a single user: you.

**Comment by webknjaz** [comment]
Honestly, in the spirit of the implemented readability rules, that setting could've been called after what it does instead of a situation it's supposed to be set in. That would make it obvious why one would want to use it.

**Comment by nifadyev** [comment]
Hey @sobolevn , is it right that setting should be renamed to be more explicit? Should one of these settings be set to `False` by default?

**Comment by sobolevn** [comment]
@nifadyev I agree that every rule shoudl have its own setting. But, on the other hand, I don't want to affect users that already use this rule.

So, the plan is:
- Fix the docs
- Add new settings for individual rules
- Make sure that setting `--i-control-code` and `-i-dont-control-code` affects these new settings as they used to

**Comment by nifadyev** [comment]
Thanks for the plan, i will try to work on it in next weeks
