### ISSUE TITLE
Rework `WPS303`: it should only be possible to write `_` with 3 digits on the right

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#3120]
Right: `1_000` and `10_000` and `100_000` and `1_000_000`
Wrong: `1_00` and `10_00`

**Comment by EPoY74** [comment]
Hi!
I want to try solve this task.
Can I find out more?

**Comment by EPoY74** [comment]
Speaks Russian or English?

**Comment by sobolevn** [comment]
Hi, sure!

Here's the main code that executes this check: https://github.com/wemake-services/wemake-python-styleguide/blob/3d5fa4853962e82fb139fecb473a1f15696f019e/wemake_python_styleguide/visitors/tokenize/primitives.py#L78
Tests: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_visitors/test_tokenize/test_primitives/test_numbers/test_underscored_numbers.py

PR is very welcome!

**Comment by EPoY74** [comment]
> Right: `1_000` and `10_000` and `100_000` and `1_000_000` Wrong: `1_00` and `10_00`

Sorry, i have one question: we separate with underscops only zeros or different numbers too?

For example:
3_453_678 - is this correct or not correct

The example only has zeros, so I doubted it and decided to clarify

**Comment by EPoY74** [comment]
And one more questions:
I cant pass next test:

FAILED test_underscored_numbers.py::test_underscored_number[def function(some={0}): ...-async_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[some_sum = {0} + 123-async_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[some_name = {0}-async_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[print({0})-async_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[def function(some={0}): ...-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[print({0})-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[some_name = {0}-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[def function(some: int = {0}): ...-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[def function(some: int = {0}): ...-async_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[some_sum = {0} + 123-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[other_var + {0}-regular_wrapper--1_000.0] - AssertionError: assert 1 == 0
FAILED test_underscored_numbers.py::test_underscored_number[other_var + {0}-async_wrapper--1_000.0] - AssertionError: assert 1 == 0

Is this tests ok?

**Comment by EPoY74** [comment]
Please clarify in which case a warning should be issued?
Otherwise, we disagreed during the discussion.

**Comment by sobolevn** [comment]
please see tests: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_visitors/test_tokenize/test_primitives/test_numbers/test_underscored_numbers.py
