### ISSUE TITLE
Boolean arguments always should be keyword

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#341]
# Rule request

## Thesis

Boolean arguments always should be passed to function as keyword.

Bad:

```python
UsersRepository.update(True)
```

Good:

```python
UsersRepository.update(cache=True)
```

Exception: passing bool value from var:

```python
cache = True
UsersRepository.update(cache)
```

## Reasoning

Boolean parameter not self-described, so you always have to read function signature to realize what is going on here.

**Comment by sobolevn** [comment]
Agree. 👍

**Comment by orsinium** [comment]
:heart:
