### ISSUE TITLE
Forbid unnecessary `else` blocks

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#365]
# Rule request

## Thesis

There are cases when `else` block should not be used:

```python
def test():
     if some_call() is not None:
           return 1
     else:
           return 2     
```

This makes no sense. Since `else` only contains a `return` statement. This should be rewritten as:

```python
def test():
     if some_call() is not None:
           return 1
     return 2   
```

All other cases are considered ok. Feel free to suggest other examples in the comments.

## Reasoning

This is done for consistency reasons. It looks more readable this way.

**Comment by sobolevn** [comment]
The same should work for both `return` and `raise` keywords.

**Comment by kxepal** [comment]
Well, that's mostly about readability + `break` for loops may work in the way like `nothing found during iteration` which safes you from yet another if-not-return.

**Comment by sobolevn** [comment]
Closed with `fuck typo`: https://github.com/wemake-services/wemake-python-styleguide/commit/5686c25eb65bcfb3880a41dca3fdaf2ed7579fc5
