### ISSUE TITLE
Django specific things

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#4]
## Models

- [ ] no `signal`, because they are evil side effects
- [ ] no `BooleanField` with `null`, use `NullBooleanField`
- [ ] no `CharField` with `null`, use `blank=True` with possible `''` as default
- [ ] use `CIEmailField` instead of `EmailField`
- [ ] no `JSONField` other than `django.contrib.postgres.fields.JSONField`
- [ ] no `default={}` in`JSONField`, use `default=dict` instead
- [ ] no methods on models except magic ones

## Structure

- [ ] all applications should be named as `*_app`
- [ ] `apps.py` and `models.py` must be present
- [ ] check filenames in `*_app` folder, whitelist: `models`, `views`, `forms`, `admin`, `serializers`, `apps`, `urls`, `tasks`, `__init__`

**Comment by valignatev** [comment]
Why "all applications should be named as `*_app`? To not confuse them with non-django modules?
Can you provide an example dir structure where it's useful?

**Comment by valignatev** [comment]
Got it about logics, but why `_app`? In this example, it looks redundant. Why is it better than
```
server
- main
- orders
- users
- - logics
- - - some_module.py  # <- the logic goes here
```
Maybe it makes sense if `server` dir is cluttered with nondjango modules.

**Comment by sobolevn** [comment]
Because it is a preference mostly. And it clearly indicates that this is an app. 
There are no other arguments.
