### ISSUE TITLE
Enforce consistent octal, hex, and binary numbers

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#420]
# Rule request

## Thesis

We should write consistent numbers:
- `0b1` instead of `0b0001`, `0b001 == 0b1`
- `0x1` instead of `0x001`
- `0o5` instead of `0o05`

## Reasoning

Numbers should be consistent.

**Comment by kxepal** [comment]
That's doubt. Zero padding exists for readability, but not a mistake reasons.

**Comment by sobolevn** [comment]
@kxepal can you please provide an example where having multiple zeros improves readability?

**Comment by sobolevn** [comment]
@kxepal thanks for bringing this up. Indeed, sometimes inconsistent behaviour can be occasionally more readable.

But, this discussion motivated me to formulate the philosophy behind my decisions: https://wemake-python-styleguide.readthedocs.io/en/latest/pages/api.html#philosophy

So, we are interested in these two parts:

> Consistency over syntatic readability
> Consistent code is more readable than inconsistent

I strongly believe that it is easier to read numbers when there's only a one way to write them. 
As in math. Not multiple ways as in `python`.

But, you suggestion is perfectly reasonable and helpful. Much thanks, so awesome.

**Comment by kxepal** [comment]
You're welcome! :beers:

**Comment by astynax** [comment]
What do you thing about such rules?
- "binary literals should have 2, 4, 8 or 8n digits" (binary literals are very useful in hardware related, so readable bit order and positioning are very important!)
- "hexadecimal literals should have 2n digits" (colors in RGB(A) for example)

**Comment by sobolevn** [comment]
I really like the suggestion made by @astynax 
@AndreyErmilov please, take a look.

**Comment by AndreyErmilov** [comment]
@sobolevn Thanks for reviewing the PR!
I can't make a complete issue description with the @astynax suggestion. Help me please.

**Comment by sobolevn** [comment]
@AndreyErmilov what do you mean by "complete issue description"?

**Comment by sobolevn** [comment]
@AndreyErmilov now I get it. Here's the full description:

> - "binary literals should have 2, 4, 8 or 8n digits" (binary literals are very useful in hardware related, so readable bit order and positioning are very important!)
> "hexadecimal literals should have 2n digits" (colors in RGB(A) for example)
> octal number should have 2n digits

**Comment by sobolevn** [comment]
Ok, after reviewing two PRs, thinking hard, and playing around, I have made a decision about this rule.

We are not going to support any leading zeros. If someone wants formatting, switch off this rule for this file, line, etc.

We value consistency more.
