### ISSUE TITLE
Forbid to use multiple negations for numbers

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#435]
# Rule request

## Thesis

We can write things like `dt = ---6`. But, we need to force `-6` for numbers.
Related #434 

## Reasoning

Consistency.

**Comment by kxepal** [comment]
What about others duplicated operators? `~~~42` or  `not not bar`? Those are rare, but feels like on the same page.

**Comment by sobolevn** [comment]
Hmm, I have missed that. 
Feels like a plan.

What do you think?

**Comment by kxepal** [comment]
Looks good, except it's hard to find any cases for them. Original issue `+5` has own reality roots (for instance, readability by rewriting some constants from a reference guide where those numbers are explicitly signed), but multiple same operators feels quite synthetic.

**Comment by kxepal** [comment]
You may not believe me, but not not in real life: https://github.com/pypa/setuptools/blob/master/pkg_resources/_vendor/pyparsing.py#L458 - I guess it's int to bool casting. But why so hard?

**Comment by sobolevn** [comment]
That's why we should forbid it. This it not a javascript with `!!` operators.
