### ISSUE TITLE
Forbid `__del__` magic method

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#44]
You should not use `__del__`, as it is non-pythonic, more like cpp.

This method is not even called in several situations.
So, let's forbid it.

**Comment by malinoff** [comment]
While I generally agree that users should not define `__del__`, in rare occasions it is actually useful.
For example, take a look at https://github.com/malinoff/aionursery/blob/master/aionursery.py#L70-L71
This tiny assertion in `__del__` actually helped to catch a bug when `_children` were not collected properly.

**Comment by sobolevn** [comment]
For this case you can use `# noqa: ...`, and document why do you use this method.
