### ISSUE TITLE
Forbid `getattr(x, 'foobar') `

### ISSUE THREAD

**Issue by vergeev** [wemake-services/wemake-python-styleguide#46]
As per [the docs](https://docs.python.org/3/library/functions.html#getattr):
> `getattr(x, 'foobar')` is equivalent to `x.foobar`

This may lead a reader to believe that `getattr(obj, 'attribute')` will not throw an exception.

### Correct
```
x.foobar
getattr(x, 'foobar', None)
getattr(x, some_variable, None)
```

### Incorrect
```
getattr(x, 'foobar')
```

**Comment by sobolevn** [comment]
But what if we have the following function:

```python
def fetch_property(obj, key_name):
     return getattr(obj, key_name)
```

And I want to throw an exception here! Because I prefer an exception over `None`.
You solution implies that we will have to manually raise these exceptions:

```python
foobar = getattr(x, 'foobar', None)
if foobar is None:
    raise AttributeError()
```

**Comment by vergeev** [comment]
Good catch! What I actually meant is prohibit the case in which the second argument is a string literal (which is always something constant).

**Comment by sobolevn** [comment]
Anyway, this does not remove my consideration about consciously rising an exception here.
I use both versions with 50/50 rate.

@vergeev I guess that you are talking about beginners, who make this error and crush their programs. But, that's not the case here.

Thanks for your suggestion, but I am going to reject it.
Please, open new ones if you have any. I appreciate your attitude towards this project.

Cheers. 👍
