### ISSUE TITLE
Forbid to use `__dir__` and `__getattr__` module magic methods

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#461]
# Rule request

## Thesis

We need to be sure that this dark magic won't make it to our code bases.
https://www.python.org/dev/peps/pep-0562/

I guess it should be also controlled with `I_CONTROL_CODE` setting.

## Reasoning

It does not bring any features, only making it harder to understand what is going on.

**Comment by isidentical** [comment]
> It does not bring any features, only making it harder to understand what is going on.

It really simplifies depraction process over packages. It was used in the `collections` (to expose `collections.abc`) until 3.9  👎

**Comment by sobolevn** [comment]
@isidentical I agree, that's why we use `I_CONTROL_CODE` setting to disable it when dealing with packages.
