### ISSUE TITLE
Forbid `__future__` imports

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#48]
They are not a thing in `python3` anymore.
But, we should have a whitelist for things like `annotations` and some new features that might come.

I also feel like we should save some more error code for imports and move other errors up a bit.

**Comment by malinoff** [comment]
`__future__` imports are actually a thing in python 3.
According to https://docs.python.org/3/library/__future__.html, today we have two py3-specific `__future__` imports: 

feature | optional in | mandatory in | effect
-- | -- | -- | --
generator_stop | 3.5.0b1 | 3.7 | PEP 479: StopIteration handling inside generators
annotations | 3.7.0b1 | 4.0 | PEP 563: Postponed evaluation of annotations

I'm sure there can be more.

**Comment by sobolevn** [comment]
We already have a whitelist for `annotations`. 
I was not aware about `generator_stop`. It can also be added to the whitelist.
