### ISSUE TITLE
Problems with setting up the project (Win)

### ISSUE THREAD

**Issue by mikhail-akimov** [wemake-services/wemake-python-styleguide#499]
# Bug report

## What's wrong

I cloned the project, installed it using `potry install`, activated the virtual environment with `poetry shell` but when I try to run the tests, I get an import error: 

```
C:\Users\makimov\PycharmProjects\wemake\wemake-python-styleguide>poetry shell
Virtual environment already activated: C:\Users\makimov\AppData\Local\pypoetry\Cache\virtualenvs\wemake-python-styleguide-py3.6

C:\Users\makimov\PycharmProjects\wemake\wemake-python-styleguide>poetry run pytest
ImportError while loading conftest 'C:\Users\makimov\PycharmProjects\wemake\wemake-python-styleguide\tests\conftest.py'.
tests\conftest.py:10: in <module>
    from wemake_python_styleguide import violations
E   ModuleNotFoundError: No module named 'wemake_python_styleguide'
```

I understand that the problem is in my environment, but I can not figure out how to fix it.

## System information

Windows7, PyCharm

**Comment by sobolevn** [comment]
Can you please try to run `source $YOUR_VENV_PATH/bin/activate` and then try to run tests again?
Maybe that's an issue with `poetry shell`.

**Comment by sobolevn** [comment]
Windows might not have `source`. I am not familiar with Windows, sorry.

**Comment by mikhail-akimov** [comment]
My problem has been resolved in the same way: https://github.com/pytest-dev/pytest/issues/2287
