### ISSUE TITLE
[?] comparison to Black?

### ISSUE THREAD

**Issue by hangtwenty** [wemake-services/wemake-python-styleguide#518]
Doc request - similarities/differences vs Black? https://github.com/ambv/black

**Comment by kxepal** [comment]
They would be hard to compare since black is a code formatter while this project is a static analyzer. A bit more proper topic could be "How Black formatted code violates the style".

**Comment by sobolevn** [comment]
Clearly it is a bug in the docs. 

This project does not format or change your code at all. 
But, it enforces best practices and cares about design and complexity of your codebase, while `black` does not do that at all.

Moreover, `black` itself violates a lot of `flake8` rules that this linter respects. Like line length.

**Comment by hangtwenty** [comment]
👌 

Thanks!

**Comment by hangtwenty** [comment]
That's all the detail _I_ need at least haha. (Don't need a point-by-point, personally)

**Comment by sobolevn** [comment]
Docs were added in `0.9.0`.
