### ISSUE TITLE
Possibly disable ignore::PendingDeprecationWarning

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#534]
I am not sure about it.

**Comment by fullset** [comment]
What's wrong with it?

**Comment by sobolevn** [comment]
I don't want to use deprecated API, but for some reason we use these filters https://github.com/wemake-services/wemake-python-styleguide/blob/master/setup.cfg#L43-L44

And we need to figure out why. And possibly disable it.

**Comment by sobolevn** [comment]
Closed in `0.9.0`
