### ISSUE TITLE
The "Usage" section was not found.

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-python-styleguide#538]
# Bug report

## What's wrong

Currently, in the [docs](https://wemake-python-styleguide.readthedocs.io/en/latest/) in the next phrase "See “Usage” section in the docs for examples and integrations." the ["Usage link"](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage.html) is broken

## How is that should be
It should show the "usage" section instead, and not 404 :)

### flake8 information

Contents of `flake8 --bug-report`:

### pip information

Contents of `pip freeze`:

**Comment by DmytroLitvinov** [comment]
Also, in the phrase "But, you can [switch off](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage.html#ignoring-violations) any rules that you don’t like" also is not found.

**Comment by sobolevn** [comment]
Can you please fix it?  Usage should point to https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/setup.html

Thanks!
