### ISSUE TITLE
Fix links in web version of CONTRIBUTING doc

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#547]
Currently some docs generate broken links https://wemake-python-styleguide.readthedocs.io/en/latest/pages/contributing.html

Demo:
<img width="667" alt="Снимок экрана 2019-04-11 в 13 03 12" src="https://user-images.githubusercontent.com/4660275/55948933-30f9cc80-5c5a-11e9-8007-949df523b1c3.png">

**Comment by Chinmaygoyal** [comment]
Can I work on this?

**Comment by sobolevn** [comment]
@Chinmaygoyal sure! Feel free.

**Comment by Chinmaygoyal** [comment]
I am new to open source so can you help me by providing a start?

**Comment by sobolevn** [comment]
@Chinmaygoyal you can start with several things:
1. General tutorial about github: https://github.com/firstcontributions/first-contributions
2. The case here is too remove extra '`' chars from links
3. I am pretty sure, that you won't need it, but just in case. Here's our own technical doc: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/pull/549
