### ISSUE TITLE
Possible rules to restrict usage of several builtin modules, methods, etc

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#566]
If `datetime.now()` is called without `tz` argument, it returns the local time without timezone. This is mistake in most of cases. Right way not to break timezones is to use `datetime.utcnow()` or pass timezone into `datetime.now` call.

Sometimes you need local time and can ignore timezones, but this is rare cases that you can explicitly mark as noQA.

**Comment by orsinium** [comment]
> dt.datetime.utcnow(): preferred to .now(), which does local time
© [elements-of-python-style](https://github.com/amontalenti/elements-of-python-style/blob/master/README.md#the-standard-library)

**Comment by sobolevn** [comment]
I think that should be a part of another project. Since we do not make any choices about library usages.

One can use `bellybutton` for this per project bases. Or we can collect different rules in a separate project called something like `better-stdlib` or similar. What do you think?

**Comment by sobolevn** [comment]
Or it can be a part of our "Refactoring section" https://github.com/wemake-services/wemake-python-styleguide/issues/431

I am still more optimistic about the separate project.

**Comment by orsinium** [comment]
We can start collecting some rules in the separate tracker or this separate label and see, how many we will get.

**Comment by sobolevn** [comment]
Let's collect them here.

**Comment by sobolevn** [comment]
Related: https://www.python.org/dev/peps/pep-0594/

**Comment by orsinium** [comment]
I don't think PEP-594 is related. It's about modules that nobody uses. To migrate from them developers will get `PendingDeprecationWarning`, we don't need to do something here.

**Comment by ditansu** [comment]
what about a django timezone middleware and therefore `from django.utils import timezone`  could  we take it in account?

**Comment by sobolevn** [comment]
The hard thing about this rule is that we cannot be sure that `datetime` or `.now()` is what we expect it is.

So, I would say that it is better to write a `mypy` plugin for this. Since `mypy` knows everything about method calls.

**Comment by orsinium** [comment]
I don't think mypy team would accept this as a thing mypy should do. Mypy for types, not for this type of checks.

I like the idea to collect this kind of rules in some place. When we will have at least 10, we will be able to choose most suitable framework for implementation.

**Comment by sobolevn** [comment]
No, I meant by

> So, I would say that it is better to write a mypy plugin for this

is that we should do it in a separate project.
I can provide you an example on how to do it in `mypy`: https://github.com/dry-python/returns/blob/master/returns/contrib/mypy/decorator_plugin.py

Here we find calls of some functions and do some logic. But, instead we can run `.fail()` on places where some incorrect functions are called.

Easy!

**Comment by orsinium** [comment]
PyLint uses astroid that has static inference for objects, including inference of possible object types and definition lookup. So, it could be a plugin for PyLint, for example.
