### ISSUE TITLE
Forbid getting known key from kwargs

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#567]
Sometimes I see code like this:

```python
def f(**kwargs):
  name = kwargs.pop('name')
  name = kwargs.get('name')
  name = kwargs['name'] 
```

For all 3 cases 'name' should be regular argument in function:

```python
def f(*, name, **kwargs):
  ...
```

Related to #425

**Comment by sobolevn** [comment]
What if `name` is not provided? And we do not want to change the function's signature (we inherit something, use existing API)?

**Comment by orsinium** [comment]
> What if name is not provided? 

```python
# kwargs.get('name'):
def f(*, name=None):
  ...

# kwargs.pop('name') or kwargs['name']:
def f(*, name):
  ...

```

**Comment by sobolevn** [comment]
I will think about it after #425 is implemented

**Comment by sobolevn** [comment]
Closing, since we won't implement #425
