### ISSUE TITLE
Forbid mutable structures as constants

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#588]
In Python `UPPERCASE_VARIABLE` conventionally means constant. Let's forbid some known mutable structures to be used as constant.

1. `set` -> `frozenset`
2. `list` -> `tuple`
3. `dict` -> `types.MappingProxyType`

**Comment by sobolevn** [comment]
This is a good one! Like: really good one!
Thanks a lot.

**Comment by sobolevn** [comment]
I would say it also makes sense to disallow mutable class level constants aka class fields.

**Comment by orsinium** [comment]
It can be [registry](https://github.com/faif/python-patterns/blob/master/patterns/behavioral/registry__py3.py) pattern. One example by the link, more explicit example here:

```python
endpoints = []

def register(endpoint):
    endpoints.append(endpoint)
```

It's how `django.admin.register` works, for example.

**Comment by sobolevn** [comment]
Ok, let's leave classes alone for now.

**Comment by orsinium** [comment]
Why is it closed? Sorry, I've missed the point. In my example above `endpoints` variable is lowercase, it's ok. The original issue about forbidding it for UPPERCASE vars.

**Comment by sobolevn** [comment]
Hm, it also makes sense. Ok, I will refactor it.

**Comment by orsinium** [comment]
Thank you :)
