### ISSUE TITLE
Prefer `dict(a=1)` to `{'a': 1}`

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#589]
I've seen this check in the Pycharm, but not in any flake8 plugin. If it's possible, use `dict(a=1)` instead of `{'a': 1}`.

Preconditions: all keys must be valid Python identifiers.

Motivation: readability and consistency.

This is the rule I'm not sure about, comments are welcome.

**Comment by sobolevn** [comment]
I will just quote our old friend:
> Nope!

**Comment by sobolevn** [comment]
😆 

In reality, I really like `{}` in both `python` and `js`.
I will suffer without them.

**Comment by orsinium** [comment]
> Nope!

Ok, every project needs a little bit of Kenneth :)
