### ISSUE TITLE
No test for WPS125: TooShortAttributeNameViolation

### ISSUE THREAD

**Issue by vergeev** [wemake-services/wemake-python-styleguide#6]
As far as I can tell, no fixture triggers the `TooShortAttributeNameViolation` (see https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_checkers/test_wrong_variable.py#L20).

If this is an issue, feel free to assign it to me.

**Comment by sobolevn** [comment]
Yeap, this is an issue indeed.
