### ISSUE TITLE
Do not allow to yield too long tuples

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#601]
# Rule request

## Thesis

Expressions like `yield foo, bar, baz, fling, flung` should not be allowed.

## Reasoning

We should use lists of similar type or wrapper objects instead.
Related: https://github.com/troessner/reek/blob/master/docs/Long-Yield-List.md
Original: https://github.com/wemake-services/wemake-python-styleguide/issues/422

**Comment by fullset** [comment]
@sobolevn Can I work on this?

Is it necessary also to add param which will be manage the maximum length of yield-tuple to config?

**Comment by sobolevn** [comment]
@fullset you are welcome!

Nope, let's make it concrete. I would say that `5` is max. `6` should raise a violation.

**Comment by sobolevn** [comment]
`7+-2` is the important number for this project!
