### ISSUE TITLE
Consider using `in` instead of multiple `==`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#602]
# Rule request

## Thesis

When we have more than two `==` operators it is time to use `in` operator.
https://github.com/PyCQA/pylint/blob/5a86fddcb815ebd08fbc3ffcbaf7b11c2ba2e107/pylint/checkers/refactoring.py#L157

## Reasoning

It makes your code more readable and allows to increase the `in` container even more without much pain.

Original: https://github.com/wemake-services/wemake-python-styleguide/issues/431

**Comment by hemanthsavasere** [comment]
Hi @sobolevn,
I would love work on this issue.

Thanks and Regards,
Hemanth Savasere

**Comment by sobolevn** [comment]
Awesome! @hemanthsavasere please, feel free to ask any questions or to send WIP pull requests to check the direction. 👍

**Comment by sobolevn** [comment]
@hemanthsavasere how's your progress? I can take this over.
I am planning a release pretty soon. And I want to have all compare related stuff in there.
