### ISSUE TITLE
Add flake8-executable

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#608]
https://github.com/xuhdev/flake8-executable

See how plugins should be added here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md#adding-new-flake8-plugins

**Comment by sobolevn** [comment]
@xuhdev thanks for writing it!

**Comment by xuhdev** [comment]
Thanks!

**Comment by sobolevn** [comment]
@xuhdev btw, send a PR if you like 🙂
