### ISSUE TITLE
Forbid compares like `False == False in [False]`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#614]
# Rule request

## Thesis

This piece of code is truly unreadable.
We already have something similar for compare cases, but it does not work for this case.

The code to forbid is: `False == False in [False]`

I would say that the rule is:
- we allow multiple `==` calls
- we allow multiple `>`, `<`, `<=`, `>=` calls

Violations:
- we disallow any multiple cases with `in`
- we disallow to mix categories: you cannot write `==` and `>` in one case, like `a == b > 2`

**Comment by antauren** [comment]
`if access.is_protected(varname) or varname == UNUSED_VARIABLE:`
It's true code?

**Comment by sobolevn** [comment]
Yes, it is.

**Comment by aj7-ent** [comment]
Hey I am very sorry if this will seem stupid  but may you please describe in brief what this project is about? I am fresh to programming . I know all basics of Python and am fluent in basic OOP. I have also completed the Sololearn Python course. If I can help you with anything then I would really be delighted because I want to enhance my skills now onwards in  real projects.

**Comment by sobolevn** [comment]
@aj7-ent this project find bad patterns and inconsistencies in your codebase. That's what linters generally do.

Feel free to take any task that feels right for you. I can help you with the suggestions and reviews, but we only merge code that passes all the quality requirements.
I would recommend to start with #608 since it is the easiest one.

Ask any questions you have, I am here to help.

**Comment by aj7-ent** [comment]
hey! thanks for such generous feedback. I would love to contribute but it
seems like I need to learn more first. Can you suggest me what in python
should I learn so I can contribute in such and other OSSs. And a good
learning platform.
Thanks again!

**Comment by orsinium** [comment]
@aj7-ent, I'm sure, #608 is the best place to start. Just add [flake8-executable](https://github.com/xuhdev/flake8-executable) into `dependencies` section in `pyproject.toml` and update documentation. It's a good opportunity to have a look at [poetry](https://github.com/sdispater/poetry/) and [flake8](https://github.com/PyCQA/flake8). Use tutorials like [this](https://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/) for a guide on how to contribute in Open Source. Ask in comments to #608 if you have questions. Good look :)

**Comment by sobolevn** [comment]
Closed by https://github.com/wemake-services/wemake-python-styleguide/commit/d024a5d8d6ffa55a563be90bc81081129bf76970

Messed up issue numbers.
