### ISSUE TITLE
Consider choosing `a < x < b` or `b > x > a`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#628]
# Rule request

## Thesis

These two expressions are the same: `a < x < b` and `b > x > a`
It is way easier to read the first one. 

Let's enforce the consistency in this expression.

**Comment by dumbturtle** [comment]
Assign me this issue

**Comment by sobolevn** [comment]
@dumbturtle you are officially assigned! 🙂

**Comment by sobolevn** [comment]
@dumbturtle how's your progress? I can take this over.
I am planning a release pretty soon. And I want to have all compare related stuff in there.
