### ISSUE TITLE
Not working due pydocstyle error

### ISSUE THREAD

**Issue by Tishka17** [wemake-services/wemake-python-styleguide#636]
# Bug report

## What's wrong

Not running at all. Gor error:
```bash
$ flake8 dataclass_factory          
"flake8-docstrings" failed during execution due to "module 'pydocstyle' has no attribute 'tokenize_open'"
Run flake8 with greater verbosity to see more details
```

**Comment by sobolevn** [comment]
Original issue: https://gitlab.com/pycqa/flake8-docstrings/issues/36

You can pin `pydocstyle<4` as a work-around for now.

**Comment by Tishka17** [comment]
[flake.report.txt](https://github.com/wemake-services/wemake-python-styleguide/files/3372519/flake.report.txt)
[out.txt](https://github.com/wemake-services/wemake-python-styleguide/files/3372520/out.txt)
[pip.freeze.txt](https://github.com/wemake-services/wemake-python-styleguide/files/3372521/pip.freeze.txt)

**Comment by sobolevn** [comment]
Solution: fix `pydoctyle<4` in your requirements for now.
