### ISSUE TITLE
Running all intended tests should be possible by one shell command.

### ISSUE THREAD

**Issue by proofit404** [wemake-services/wemake-python-styleguide#640]
# Bug report

After I clone this repository, I want to be sure my local environment setup is correct. It is unbelievably hard without a single straightforward command to run all tests.

## What's wrong

To run tests on a local machine, we should open `.travis.yml` file and copy past 8 commands into a terminal. Each time I want to run tests.

## How is that should be

I should type as much as `tox`, `make` or `./ci.sh`.

Regards, 
Artem.

**Comment by sobolevn** [comment]
Well, I am not used to these tools. Because I like the full control on things I run. 
But, you can indeed setup a `Makefile` with the same commands as in `.travis.yml`
