### ISSUE TITLE
Incompatible attrs version

### ISSUE THREAD

**Issue by serhii73** [wemake-services/wemake-python-styleguide#680]
```
> $ pip freeze | xargs pip uninstall -y 
```
Ok, I remove all from my virtual environment.
And then I am installing `wemake-python-styleguide` 
```
> $ pip install wemake-python-styleguide
```
But after I see a red message
```
flake8-eradicate 0.2.0 has requirement attrs<19.0.0,>=18.2.0, but you'll have attrs 19.1.0 which is incompatible.
```

**Comment by sobolevn** [comment]
Ok, that's an issue with `flake8-eradicate`. Luckily, I am fixing it right now.
I will release new `flake8-eradicate` version in 30 minutes.

Sorry for that!
