### ISSUE TITLE
Why double quotes is bad?

### ISSUE THREAD

**Issue by serhii73** [wemake-services/wemake-python-styleguide#681]
```
> $ cat t.py
hi = "Hello, world!"
```
And
```
flake8 t.py
t.py:1:6: Q000 Remove bad quotes
```
Sorry, I don't understand, why double quotes are bad?
`black` for format my code use double quotes and then I want to use `wemake-python-styleguide`.
But why you think double quotes is not good?

**Comment by sobolevn** [comment]
And why do think that double quotes are good? 🙂 

The thing is: it is absolutely equally good or bad to use `'` or `"` in your project.
We just have to make a choice here. And use this type of quotes consistency. 

Several things here:
1. You can configure https://github.com/zheller/flake8-quotes the way you like (again, it does not really matter)
2. You can use `black -S` to force single quotes with `black` and `flake8-quotes`
3. `black` is not officially supported: https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/integrations.html#auto-formatters Use `autoflake8` which is better

**Comment by rubenflamshepherd** [comment]
Came across this while also trying to answer this question. For what it's worth `black` actually has some reasons for using double quotes. Find those [here](https://black.readthedocs.io/en/stable/the_black_code_style.html#:~:text=Why%20settle%20on%20double%20quotes,fonts%20and%20syntax%20highlighting%20used.)!

**Comment by sobolevn** [comment]
One more thing! Single quotes are easier to type, because you don't have to press shift.

**Comment by Pfeifenjoy** [comment]
Actually the typing depends on your keyboard layout and you can easily remap your keyboard.

I prefer double quotes since in many other programming languages like Java or C/C++
single quotes are associated with characters and not strings.
