### ISSUE TITLE
Forbid magic methods to be async

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#684]
# Rule request

## Thesis

Only several magic method can be `async`. Other method should be just functions.

## Reasoning

Having `async __lt__(self, ...) -> ...` is incorrect. It cannot be used like so.
The same applies to almost all other method including `__init__`, `__new__`, `__bool__`, etc.
Only `__aenter__`, `__aexit__` and possibly some other can be `async`.

We must have an explicit list of whitelisted async magic methods.

**Comment by sobolevn** [comment]
@bellum I guess this might be interesting to you 🙂

**Comment by bellum** [comment]
@sobolevn might be :) according to this link https://docs.python.org/3/reference/datamodel.html there are next async dunder methods:
- `__anext__`
- `__aenter__`
- `__aexit__`

Should this list be hardcoded in `wemake_python_styleguide/constants.py` under the name like `ASYNC_MAGIC_METHODS_WHITELIST`?

**Comment by sobolevn** [comment]
I think so 👍
