### ISSUE TITLE
Forbid to use `range(len(...))`, use `enumerate` instead

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#689]
# Rule request

## Thesis

We should forbid to use `range` as:
- `range(len(some))`
- `range(0, len(some))`

Related: https://github.com/PyCQA/pylint/search?q=consider-using-enumerate&unscoped_q=consider-using-enumerate

## Reasoning

It is unpythonic. `enumerate` is pythonic.
We should enforce `enumerate` usage where possible.
This is a refactoring rule.

**Comment by silvererudite** [comment]
Hi...I would like to work on this issue. can this be assigned to me? Also Can you please give me some directions as to how to go about implementing it?

**Comment by sobolevn** [comment]
@silvererudite awesome! Assigned it to you.

This is how it should be implemented:

0. Read the docs: https://wemake-python-stylegui.de/en/latest/pages/api.html
1. You create a new violation called `RangeOnLenCallViolation` here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/refactoring.py#L588 (at the end of this file)
2. Then you create a new visitor here (let's call it `WrongFunctionCallContextVisitor`, later we will add more checks to it, see #711): https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/refactoring.py#L588 
3. Write unit tests for your changes
4. Done!

Ask any questions you have.

**Comment by sobolevn** [comment]
@silvererudite Hi, how is it going? Do you need any help?

**Comment by silvererudite** [comment]
Hi @sobolevn, had my hands full past week for exam hence the delay. Hope it's ok. I've been trying to read the docs and yes I think I have an issue. I don't quite understand which base class while creating the violation. I see in : https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/refactoring.py#L588  that  ASTViolation class is used extensively. Can u pls tell me how do I identify which class to choose based on a specific problem?

**Comment by silvererudite** [comment]
I see that in each violation class there's a parameter called node? Can u pls clarify what kinda input goes in it?

**Comment by sobolevn** [comment]
You need this one for a violation: https://wemake-python-stylegui.de/en/latest/pages/api/violations.html#wemake_python_styleguide.violations.base.ASTViolation

You need this one for a visitor: https://wemake-python-stylegui.de/en/latest/pages/api/visitors.html#wemake_python_styleguide.visitors.base.BaseNodeVisitor

`node` is an `ast` node that is the source of the violation. Here's a clear example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/classes.py#L42-L63

**Comment by silvererudite** [comment]
hey @sobolevn ...so I have written the details of the violation following the docs but where do I get these criteria from the docs?

- Each violation must have “versionadded” policy
- If violation error template should have a parameter it should be the last part of the text: : {0}

**Comment by sobolevn** [comment]
@silvererudite add

- ``.. versionadded:: 0.12.0`` to the docs of your new violation
- Ignore it completely

**Comment by silvererudite** [comment]
>     3. Then you create a new visitor here (let's call it `WrongFunctionCallContextVisitor`, later we will add more checks to it, see #711): https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/refactoring.py#L588

why are we creating visitor in violations/refactoring.py ? Shouldn't it be in visitors/ast module ?

**Comment by sobolevn** [comment]
You are right, I have copied a wrong link. Fixed

**Comment by silvererudite** [comment]
hey..so creating the visitor is frying my brain. Let me just list the things as far as I understood and pls correct me and/or suggest better ways if possible

1.  we create the a visitor to check for the violation we wrote in violations.py and if it finds a case where the the rule was violated the violation would be raised (kind of like the try catch logic in simple terms) 

2. So I need to create a new class for ex: WrongFunctionCallContextVisitor in visitors/ast/functions.py

3. and that class will have a function for ex: check_rangelen which implements the logic to check in a piece of code parsed as tokens in the argument of this class if the violation occurred and raises the violation

**Comment by sobolevn** [comment]
Yes! I have already created this `visitor` to check `open()` and `type()` calls.
All you need to do is to detect `range(len())` calls.

Here's the visitor I am talking about: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/functions.py#L120

**Comment by silvererudite** [comment]
Oh I see..but why do I not get this visitor in my local repository even after updating it using 

`git pull origin master`

should I just copy paste the structure of this visitor and start writing code then ?

**Comment by sobolevn** [comment]
Nope, you need to rebase the original repo: https://help.github.com/en/articles/syncing-a-fork

**Comment by silvererudite** [comment]
Yeah fixed it now thanks btw

**Comment by silvererudite** [comment]
@sobolevn how do I run this linter in my local machine ? (for testing purposes)

**Comment by sobolevn** [comment]
Everything is described in depth inside https://wemake-python-stylegui.de/en/latest/pages/api/contributing.html

But, I would say that `poetry run pytest` is enough. `poetry run make test` to run everything before the PR.

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/commit/e6dd86df5a3763eae8a7c3e4b3824db8797ea549

Sorry, @silvererudite, but the release schedule is coming. And I don't have much time left.
