### ISSUE TITLE
Forbid compares with `0` and `''`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#702]
# Rule request

## Thesis

We can omit compare with `0` and `''`, because `not something` is enough.
We should forbid `is`, `not is`, `==`, `!=`

## Reasoning

This is a best practice from python world.

**Comment by DjaPy** [comment]
Cool rule. I'll take.
I'm surprised it hasn't been implemented yet.

**Comment by sobolevn** [comment]
Me too 😅

**Comment by sobolevn** [comment]
@DjaPy sorry, but I haven't mention `[]`, `()`, `{}` as constants. Also, make sure that `""`, `0.0`,  `0.` and `.0` are also covered. We have a lot of ugly stuff in python!

**Comment by DjaPy** [comment]
Ок!

**Comment by DjaPy** [comment]
I need clarification. 
Are we checking explicitly `0, '', [], {} ...`? Or should I check the variables for their contents of values?
Example:
```python
clear_list = []
if value is clear_list:
    print(no value)
```
Therefore, I need to check that the `clear_list` is an empty list.

**Comment by kxepal** [comment]
The `thing == 0` and `not thing` are different comparisons and cannot be counted as the same. First involves a) explicit type assumption and b) `__eq__` usage to get the answer. The former one just `__bool__` check and don't care what the `thing` is. 

Also, there is `numpy` thing where you may compare with `0` with easy and with legal result:
```
>>> a = numpy.arange(10)
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> a == 0
array([ True, False, False, False, False, False, False, False, False, False], dtype=bool)
```

While you'll have difficult times if you'll try to not the array:
```
>>> not numpy.arange(0)
True
>>> not numpy.arange(1)
True
>>> not numpy.arange(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

So this restriction and "best practice" is not the best at all to follow it blindly.

**Comment by sobolevn** [comment]
@kxepal This happens just because `numpy` does stupid things. What kind of an API is that?
`__eq__` should return bool, not new arrays.

It is always a best practice to:
1. Explicitly check for `is None` if a value is `Optional`
2. Check if `not value` if you need a false branch

For cases when we are working with wrong APIs this check can be turned off.

@DjaPy no, we check for values only. We do not typecheck things.

**Comment by kxepal** [comment]
> __eq__ should return bool, not new arrays.
Should return for whom? It's a DSL. It does what it does. Same happens for almost all ORM.

**Comment by sobolevn** [comment]
To python API 🙂

**Comment by kxepal** [comment]
What is Python API?
https://docs.python.org/3/reference/datamodel.html#object.__eq__
> By convention, False and True are returned for a successful comparison. However, these methods can return any value, so if the comparison operator is used in a Boolean context (e.g., in the condition of an if statement), Python will call bool() on the value to determine if the result is true or false.

So, it's all about `bool()` call on comparison result.

**Comment by kxepal** [comment]
Eventually, you can throw away some homemade pet projects with weird magic methods behaviour, but numpy and friends are eventually common standard to do math things. By denying their API you will leave users no chose but to drop your linter for good.

**Comment by kxepal** [comment]
Also, same things will happens on various ORM projects. I don't have any by a hand, but I did see a lot `thing == False` or `thing != 0` before. Any linters complains about that, but in terms of DSL it's the only (well, not true, some provides special methods for such comparisons) way to handle things. And you'll have to accept that.

**Comment by sobolevn** [comment]
That's totally reasonable! But, the point of this linter is not to accept that some classes have the wrong API, but to enforce all the best practices possible.

In case something does not work for you: like `numpy` with `== 0`, ORMs with `== False` (by the way a lot of them support `kwargs` based queries like `field=0` which is correct), or `stories` with expression based API; you have to switch off this rule. That's the only possible way.

**Comment by kxepal** [comment]
Feels like you would have to create some documentation page about how to work aound those stupid API's and stay on Pythonic land making all the linters happy. Without such this restriction could be harmful.

**Comment by sobolevn** [comment]
@kxepal sounds fair! Thanks! 👍

**Comment by kootenpv** [comment]
This is wrong! What if I can expect a `0` or `""`. There is then no way to distinguish between them anymore.

**Comment by kxepal** [comment]
That means you mix two different types with completely different behaviour within a single variable, what is already an issue.

**Comment by sobolevn** [comment]
I agree with @kxepal 

In case you work with `Optional[int]` - you need to check these cases:

```python
maybe_int: Optional[int]

if maybe_int is None:
    print(None)
elif not maybe_int:
    print(0)
else:
    print('!=', 0)
```

**Comment by sobolevn** [comment]
But, if you work with `Union[str, int]` and then explicitly check for `0` and `''` cases - then, you should:
1. fix you code
2. use `# noqa` comment to disable this check inline

**Comment by sobolevn** [comment]
@DjaPy friendly ping. How is that going? Do you need any help?

**Comment by sobolevn** [comment]
Ok, I agree that this rule is not a good one. I have analysed several projects that we use. Here are the results:

```
./wemake_python_styleguide/visitors/ast/compares.py

  48:29    WPS520 Found compare with falsy constant: 0
  if numeric_value == 0:
                      ^

./wemake_python_styleguide/visitors/ast/classes.py

  191:58   WPS520 Found compare with falsy constant: 0
  if statements_number > 2 or statements_number == 0:
                                                   ^

./wemake_python_styleguide/visitors/ast/statements.py

  199:69   WPS520 Found compare with falsy constant: 0
  self._check_expression(statement, is_first=index == 0)
                                                      ^

  276:25   WPS520 Found compare with falsy constant: 0
  if index == 0:
              ^

./wemake_python_styleguide/visitors/ast/operators.py

  93:25    WPS520 Found compare with falsy constant: 0
  number.n == 0
              ^

./wemake_python_styleguide/visitors/tokenize/statements.py

  115:25   WPS520 Found compare with falsy constant: 0
  if index == 0 or line != lines[index - 1] + 1:
              ^

  169:54   WPS520 Found compare with falsy constant: 0
  if annotated[_get_reverse_bracket(token)] == 0:
                                               ^

./wemake_python_styleguide/logic/arguments/super_args.py

  71:23    WPS520 Found compare with falsy constant: 0
  if args_number == 0:
                    ^

Full list of violations and explanations:
https://wemake-python-stylegui.de/en/0.11.1/pages/usage/violations/
```

So, let's concentrate on `[]`, `{}`, `()`. And allow simple types: `0`, `''`, `None|True|False`.
