### ISSUE TITLE
Forbid `is` compare with constants

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#703]
# Rule request

## Thesis

We need to forbid compares with `is` and `not is` with:
- numbers
- strings and bytes

And complex types empty or with constants only:
- lists, dicts, sets (and comprehensions)
- tuples and generator expressions

We still force `is` to compare with `False`, `True`, `None`.

## Reasoning

The best practice from python is to use `==` to compare with constants.
Link: https://stackoverflow.com/questions/2988017/string-comparison-in-python-is-vs

**Comment by Tranced** [comment]
Hey @sobolevn, was just wondering if you needed any help on this. I'd love to work on it!

**Comment by sobolevn** [comment]
Here you go! But, please keep in mind that the release date is coming: 1 Sep.

Ask for any help you need!
