### ISSUE TITLE
Forbid `open()` not inside `with`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#711]
# Rule request

## Thesis

We should forbid this way of calling `open()`:

```python
some = open(...)
```

Or:

```python
try:
     some = open(...)
finally:
     ...
```

Use:

```python
with open(...) as ...:
    ...
```

## Reasoning

This is a best practice in python.
This is a refactoring rule.

**Comment by dmitrymishanov** [comment]
Hello, Nikita! 
I would like to work on this issue.

**Comment by sobolevn** [comment]
Awesome! @dmitrymishanov you are officially assigned 👍 

Feel free to ask any questions you have or ask for any help you need.

**Comment by dmitrymishanov** [comment]
@sobolevn, I tried to understand how it works and how to solve this, but my knowledge level is apparently too low for contributing your project. Hope to return later and to help here. 
Sorry.

**Comment by sobolevn** [comment]
@dmitrymishanov no problems! If you have any feedback about the codebase, docs, or structure - feel free to share.

Hope that you will still use `wemake-python-styleguide` in your projects.

**Comment by sobolevn** [comment]
Hey, @dmitrymishanov! Check out my commit: https://github.com/wemake-services/wemake-python-styleguide/commit/eec9a14de916cb9051fa847e62d331d53fbcf914 where I solve this issue. Maybe you will learn something new! 👍
