### ISSUE TITLE
Forbid to use `*[]`, `*()`, and `**{}` in calls

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#715]
# Rule request

## Thesis

Using code like:

```python
print(*[], **{})
```

Does not make any sense. It should be forbidden.
There's no need in using explicit `*[]` or `*{}` or `*()` since call that expect `*args` will just receive empty tuple. There's also no point in using `**{}` in your code.

## Reasoning

This is a refactoring rule. This kind of calls is just pointless.

**Comment by ea-volkov** [comment]
Hello, Nikita! I would like to work on this issue.

**Comment by sobolevn** [comment]
Awesome, @ea-volkov! You are assigned. Please, feel free to ask any questions, show your progress with pull requests, and ask for help. 👍

**Comment by ea-volkov** [comment]
Hi, @sobolevn! I'm not sure of the chosen path of realization for the visitor. Can you comment current logic PR?
