### ISSUE TITLE
Find `sum` candidates

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#743]
# Rule request

## Thesis

```python
Finding candidates for replacement with sum:

$ astpath -A 1 "//For/body[AugAssign/op/Add and count(child::*)=1]" | head -6
./functools.py:374      >        for item in sorted_items:
./functools.py:375                   key += item
./statistics.py:177     >    for d, n in sorted(partials.items()):
./statistics.py:178              total += Fraction(n, d)
./pstats.py:512 >    for calls in callers.values():
./pstats.py:513          nc += calls
```

Quote from: https://github.com/hchasestevens/astpath

Instead use `sum(call for call in callers.values())`, etc

## Reasoning

No need to write an extra `for` loop. 
This is a refactoring rule.

**Comment by r19m89s** [comment]
I can pick this up if no one else is currently working on this.

**Comment by kxepal** [comment]
Assume:
```
acc: List[int] = []
items: List[List[int]] = [[1], [2], [3]]
```

Then would this rule suggest to rewrite this code:
```
for item in items:
  acc += item
# acc = [1, 2, 3]
```
into this:
```
acc = sum(items)  # TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

while correct form would be:
```
acc = sum(items, [])
# acc = [1, 2, 3]
```
?

This example shows that initial value is important and suggestion to use just `sum(...)` may be wrong.

**Comment by sobolevn** [comment]
Ok, @r19m89s you are assigned! Feel free to ask any questions and ask for help.

@kxepal agree. This should be listed in the violation docs. Also, link to the official python docs is required.
