### ISSUE TITLE
Create optional dependencies

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#764]
I see several groups:

- django: with `flake8-django`
- pytest: with `flake8-pytest` and `flake8-pytest-style`

Requires extra configuration, won't be included:
- config: with `nitpick`
- legacy: with `flakehell`

**Comment by orsinium** [comment]
I think, only zero-config flake8 plugins can be dependencies. In this example, `flake8-django`, `flake8-pytest`, and `flake8-pytest-style`. Tools like `nitpick` and `flakehell` require additional configs and knowledge. It's better to recommend them, not depend.

**Comment by orsinium** [comment]
Because when you're directly working with some tool (writing a special config for it), it's already not a dependency of wemake, but a dependency of the project.

**Comment by sobolevn** [comment]
Agree. Updated.

**Comment by sobolevn** [comment]
On the other hand: how many tools can we put in these optional sections? What is the difference with `pip install wemake-python-styleguide flake8-django`?

I am closing it, since the value is not clear to me.
