### ISSUE TITLE
Respect `@overload` decorator

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#766]
Currently I have to ignore all `@overload` cases from block-overlap manually:

```python
@overload  # noqa: WPS430
def pipeline(
    function: _AsyncReturnsResultType,
) -> _AsyncReturnsResultType:
    """Case for async functions."""


@overload  # noqa: WPS430
def pipeline(function: _ReturnsResultType) -> _ReturnsResultType:
    """Case for regular functions."""


def pipeline(function):
    ...
```

I guess, that this should be applied automatically. And functions with `@overload` (or `@typing.overload`) decorator should be allowed.

**Comment by ea-volkov** [comment]
Hello, @sobolevn 
I would like to work on this issue.

**Comment by sobolevn** [comment]
Please, feel free! I really want this to be solved! 👍

**Comment by sobolevn** [comment]
Closed via https://github.com/wemake-services/wemake-python-styleguide/pull/804
