### ISSUE TITLE
Add `reveal_type` to forbidden functions

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#771]
Now it is not recognised as invalid.
However, there's no reason to use it in production.

**Comment by serhii73** [comment]
Hello, @sobolevn. I can do it.
But I'm a newbie in python world and can you tell me more about this task?
Thank you =)

**Comment by sobolevn** [comment]
@serhii73 add this function here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/constants.py#L15

That's all.

**Comment by serhii73** [comment]
plz assign this issue to me on the GitHub UI. Thanks =)
