### ISSUE TITLE
Forbid `.readlines()` in `for`

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#781]
There is an issue in PyLint, but it's 4 years old. However, it sounds easy. So, let's do it here.
https://github.com/PyCQA/pylint/issues/696

**Comment by sobolevn** [comment]
Sounds like a very hard task to implement.
See pylint's cases.

**Comment by orsinium** [comment]
As always, I think, it's OK to cover only some really simple cases for the beginning.

**Comment by lensvol** [comment]
Can I take this one?

**Comment by sobolevn** [comment]
I have tried to implement it. That's too complex. 

We also have to assume type of this `.readlines()` call. Which is not what we want.
This issue will be implemented in `typed-linter` later.
