### ISSUE TITLE
Forbid to unpack values like `**{'@': 1}` 

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#782]
# Rule request

## Thesis

Related to #767

This should be forbidden: 

```
>>> print(**{'@': 2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '@' is an invalid keyword argument for print()
```

To validate this we need to use `str.is_identifier`

## Reasoning

This is simply wrong.

**Comment by ea-volkov** [comment]
Hello, Nikita! I would like to work on this issue.
