### ISSUE TITLE
Forbid approximate constants

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#787]
# Rule request

## Thesis

We should disallow code like `my_pi = 3.14` because this constant is already defined: https://docs.python.org/3/library/math.html#constants

See the whole list of defined values.

There might be other constants and modules we should check.
https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant

## Reasoning

No need to write them again, use existing values.

**Comment by Roxe322** [comment]
Hello, can I take this one?

**Comment by kxepal** [comment]
What if I need `pi` with specific precision? And it's 3.14 no more, no less, because otherwise my school teacher will not accept my homework?

Or what if my constant looks like some predefined math constant (like pi), but it means something completely different? Causing collision on some precision is not a crime.

**Comment by Roxe322** [comment]
@kxepal, I think first case is rare. If you need math constant - you should use math constant, in any specific reason - just turn off linter rule :) 

About second case - I think, we should check not only value of constant but also its name, something like "if name contains pi and it equals 3.14 then forbid".

**Comment by sobolevn** [comment]
@kxepal Good question! You can use `round(ANY_CONSTANT, PRECISION)` in case you need some specific precisions. For now we will only work with three constants: `pi`, `e`, `tau`. But, this list is opened for any other additions!

@Roxe322 thanks! Assigned.
