### ISSUE TITLE
Add wemake-python-styleguide to awesome-python

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#805]
We are ready for the first public release.
To make sure we cover everything, we need to add this project to https://github.com/vinta/awesome-python

To achieve this, we need to upvote this PR to 20 👍 https://github.com/vinta/awesome-python/pull/1348

I am sure that regular contributors are interested in this as much as I am.
So, I make a decision to ping you guys.

**Comment by sobolevn** [comment]
@novikovfred @thesimanjan @lk-geimfari @AndreyErmilov @bellum @ea-volkov @SizovIgor @valignatev @TyVik @Roxe322 @AlexArcPy @AlwxSin 

After this is merged, I will closed this issue and limit the conversation - so no new notifications will be created. 👍

**Comment by lk-geimfari** [comment]
Well, almost done!

**Comment by sobolevn** [comment]
Done!
