### ISSUE TITLE
Forbid lambdas that return initial type values

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#807]
# Rule request

## Thesis

Forbid `lambda: ''`, `lambda: 0`, `lambda: []`, `lambda: 0.0`, etc.
These all can be replaced with `int`, `list`, `str`, and other simple type calls.

That's the original code I saw using this: https://github.com/numpy/numpy-stubs/blob/master/tests/test_stubs.py#L54

What we need to check:
- `lambda` has 0 args
- `lambda` returns default type value

## Reasoning

This is a refactoring rule.

**Comment by kxepal** [comment]
How about to forbid `lambda: fun()` as  well as it redundant?

**Comment by sobolevn** [comment]
We already forbid it, see `UselessLambdaViolation`

**Comment by kxepal** [comment]
Great!

**Comment by kyleseto2** [comment]
I wanna work on this!

**Comment by sobolevn** [comment]
@kyleseto2 you are on it! Thanks!

**Comment by kyleseto2** [comment]
I didn't find any instances of lambda returning type values

**Comment by sobolevn** [comment]
That's correct! We don't have any of them in the source code.

**Comment by kyleseto2** [comment]
Sorry I'm new to this. I dont think I fully understand the task

**Comment by sobolevn** [comment]
@kyleseto2 no problem. Thanks for your effort!
