### ISSUE TITLE
WPS431 Found nested class: allow define additional allowed classes

### ISSUE THREAD

**Issue by lapshin1988** [wemake-services/wemake-python-styleguide#808]
Hi! We are using `graphene-python` package. This library introduces a definition of additional nested classes (for example, `Arguments`, `Input `,..). For now, rule WPS431 prevent these nested classes. I think, that it will be cool to allow to modify `NESTED_CLASSES_WHITELIST` for adding such classes (and any other custom nested classes). Thank you for the linter!

**Comment by lapshin1988** [comment]
Sorry for the delay: I was on vacation. I have implemented the feature. Please allow me to create a branch in the repo (or I should fork the repo?)

**Comment by sobolevn** [comment]
@lapshin1988 please, create a fork - then create a PR. Thanks! 👍
