### ISSUE TITLE
Make `OveruseOfNoqaCommentViolation` configurable

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#820]
Some people just use `noqa` for all the things. They write wrong code for no reason and later just put `noqa` to ignore it.

We need to be strict here: some projects totally require that `noqa` limit should be lower.
So, I guess we should make this configurable in the `[0, 10]` space.

**Comment by AvianAnalyst** [comment]
Hey! I'd be interested in looking at this, but I might need some guidance. Is this related to #821?

**Comment by sobolevn** [comment]
Sort of. It is not directly related, but just works with the same problem.

Let's start with #821 since it is easier. And come back to this one later.

**Comment by AvianAnalyst** [comment]
Ok, sounds good!

**Comment by lensvol** [comment]
I can take this one if there are no objections.

**Comment by sobolevn** [comment]
Done! 👍
