### ISSUE TITLE
Contribution link in README.md is broken

### ISSUE THREAD

**Issue by alisher-matkurbanov** [wemake-services/wemake-python-styleguide#822]
# Bug report
[This link](https://wemake-python-stylegui.de/en/latest/pages/contributing.html) that is appeared in README.md is broken and no longer points to the contribution guide.

As I can see you created guide in [CONTRIBUTION.md](https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md) file and changed this guide in [docs](https://wemake-python-stylegui.de/en/latest/pages/api/index.html#contributing)

It would be better to change it in readme.
I could create a pull request. Which link is better to refer?

**Comment by sobolevn** [comment]
@alisher-matkurbanov please, refer to the documentation. Thanks for the report!
