### ISSUE TITLE
Forbid to use `Literal[None]`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#829]
# Rule request

## Thesis

`Literal[None]` is just the same as `None`. There's no need to use the first version.
It is not type related, it is a consistency rule.

**Comment by sobolevn** [comment]
Related to #792

**Comment by lensvol** [comment]
I can take this.

**Comment by sobolevn** [comment]
@lensvol glad to see you again! Assigned.
