### ISSUE TITLE
Forbid nested `typing.Literal` and `typing.Union`

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#837]
# Rule request

## Thesis

From PEP-586:

> Literal[Literal[Literal[1, 2, 3], "foo"], 5, None]
> This should be exactly equivalent to the following type:
> Literal[1, 2, 3, "foo", 5, None]

Let's follow the last one.

The same applies for:

- `Annotated`
- `Union`

## Reasoning

Consistency :upside_down_face:  Heavily related to #829

**Comment by hhsdev** [comment]
Can I work on this?

**Comment by sobolevn** [comment]
Sure, @hhsdev! Thanks a lot!
