### ISSUE TITLE
Prefer `float` over `Union[int, float]`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#838]
# Rule request

## Thesis

We should use `float` and not `Union[int, float]`. Because it is the same thing.
Taken from: https://github.com/psf/black#typing-stub-files

I guess we even need the special violation group for types!

**Comment by maikefischer** [comment]
Can I pick this up?

**Comment by sobolevn** [comment]
Sure! Thanks a lot!

**Comment by sobolevn** [comment]
@maikefischer hey, how's it going? Do you need any help?

**Comment by maikefischer** [comment]
Sorry I didnt have time, I want to pick it up this week! Can you give me a proper issues description? Where exactly do you want to replace Union?

**Comment by sobolevn** [comment]
We want to write a linting rule that raises a violation when it finds `Union[float, int]`, the solution to the problem would be just `float`

**Comment by maikefischer** [comment]
Okay I will look at this tonight and tomorrow!

**Comment by sobolevn** [comment]
Hi @maikefischer, how's it going? Do you need any help?
