### ISSUE TITLE
Test that violations with `previous_code` field have `.. versionchanged` directive

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#853]
Some violations do change their codes once in a while. When this happens we do two things:
1. We set `previous_codes` class attribute with the value of the previous codes inside (might contain multiple values), so it would be easier for users to search the docs: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/oop.py#L91
2. We set `.. versionchanged::` doc attribute inside the docstring: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/violations/oop.py#L85

But, we can forget to do the  the second step.
We need to test it!

For all violations that have `previous_codes` attribute we need to be sure that the docstring contains the same or greater amount of `.. versionchanged::` marker

Here are the tests for violation docs: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_violations/test_docs.py

**Comment by bwdrebing** [comment]
I'll take a look into this issue!

**Comment by sobolevn** [comment]
Awesome!
