### ISSUE TITLE
I_CONTROL_CODE setting is not respected for BadMagicModuleFunctionViolation

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#858]
# Bug report

## What's wrong

We need to ensure that `I_CONTROL_CODE` setting is respected for the `BadMagicModuleFunctionViolation`. It happens here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/modules.py#L88

Related #461 

## How is that should be

It should not raise this violation when `I_CONTROL_CODE` is set to false.
All we need to do is to check for `self.options.i_control_code` in this method.

**Comment by raghav-ys** [comment]
@sobolevn Hello, I would like to  work on this issue. 

Based on my understanding changing the if condition at https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/ast/modules.py#L88 to

 if node.name in constants.MAGIC_MODULE_NAMES_BLACKLIST **and self.options.i_control_code**:

please suggest

**Comment by sobolevn** [comment]
Yeap, that's right! The only thing: I would prefer to have two separate `if`s. Firstly we check for settings, then for the value. 

We also require to test it here: https://github.com/wemake-services/wemake-python-styleguide/blob/master/tests/test_visitors/test_ast/test_modules/test_magic_module_functions.py

See how we work with settings: https://github.com/wemake-services/wemake-python-styleguide/blob/a8eea7e1243cef5bc88ee7e6e4c66f71175656d2/tests/test_visitors/test_ast/test_modules/test_empty_init.py#L97

**Comment by raghav-ys** [comment]
@sobolevn - I have made the change based on your inputs. When i ran "pytest" in my local, code coverage came to 99%. Coverage report shows issues in couple of other files which I haven't touched. Attaching the report. Please help.
[htmlcov.zip](https://github.com/wemake-services/wemake-python-styleguide/files/3705644/htmlcov.zip)

**Comment by sobolevn** [comment]
Sorry, @raghav-ys I am not sure about what happened. Locally everything works fine. 
The CI is also green: https://travis-ci.org/wemake-services/wemake-python-styleguide/jobs/595353375#L1030

Can you please send a PR as is and we will go from there?

**Comment by raghav-ys** [comment]
@sobolevn Hello, I have submitted the PR. It failed in CI.

**Comment by sobolevn** [comment]
Closed in https://github.com/wemake-services/wemake-python-styleguide/pull/878

**Comment by sobolevn** [comment]
Related: https://github.com/wemake-services/wemake-python-styleguide/pull/868
