### ISSUE TITLE
dead link in contributing.md

### ISSUE THREAD

**Issue by raghav-ys** [wemake-services/wemake-python-styleguide#859]
# Bug report

## What's wrong

Developer's documentation link at
https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md#developers-documentation doesn't exists.

Incorrect url is https://wemake-python-stylegui.de/en/latest/pages/api.html .

### flake8 information

Contents of `flake8 --bug-report`:

### pip information

Contents of `pip freeze`:

**Comment by sobolevn** [comment]
@raghav-ys can you please fix it? The correct link is https://wemake-python-stylegui.de/en/latest/pages/api/index.html

**Comment by raghav-ys** [comment]
@sobolevn - Sure, will do.
