### ISSUE TITLE
Forbid a[len(a)-1]

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#862]
# Rule request

## Thesis

That's a common mistake of gophers. Golang has no negative index ([yet?](https://github.com/golang/go/issues/33359)), but Python has.

Bad:

```python
a[len(a) - 1]
a[len(a) + 1]  # IndexError
```

Good:

```python
a[-1]
a[1]
a[len(a) // 2]
```

The floor division is ok. Plus len and minus len isn't

## Reasoning

`a[len(a)-1]` is slow, `a[len(a)+1]` is IndexError.

**Comment by sobolevn** [comment]
Awesome!

**Comment by sobolevn** [comment]
@kxepal do you have any comments on this?

**Comment by abyss143** [comment]
Can I take this?

**Comment by sobolevn** [comment]
Let's start with #861 
Later you can take as many as you want 🙂

**Comment by lensvol** [comment]
Can I take this one?

**Comment by sobolevn** [comment]
Done! Thanks! 👍

**Comment by kxepal** [comment]
> do you have any comments on this?

LFGM, except this case is quite rare one and mostly relates to migration from some Golang to Python. I can't find any similar issues in real Python code.

**Comment by sobolevn** [comment]
Hi @lensvol, how's it going? Do you need any help?

**Comment by lensvol** [comment]
Hi @sobolevn, everything is on track, got distracted by real-life issues sadly :/ Hope I will close it this week.
