### ISSUE TITLE
Forbid to start lines with `.`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#866]
# Rule request

## Thesis

Currently there's an inconsistency between how people might split complex expressions into separate line.

There are basically three ways:

1. The one with `\` 
  ```python
  MyModel.objects.filter(...) \
      .exclude(...) \
      .annotate(...)
  ``` 
  which is forbidden by `flake8-broken-line`

2. The one which should be used:
  ```python
  MyModel.objects.filter(
      ...,
  ).exclude(
      ...,
  ).annotate(
      ...,
  )
  ```
3. And the one that can be currently used and should be forbidden by this new rule.
  ```python
   some = (
       MyModel.objects.filter(...)
           .exclude()
           .annotate()
   )
  ```

We need to have a one way of doing things. We chose the second one. The third one should be forbidden. 

We wild guess is that the easiest way of doing it is checking the tokens after `tokenize.NL` and `tokenize.NEWLINE`

## Reasoning

This is a consistency rule.

**Comment by CUBERLEON** [comment]
Hi, please assign it to me. Thanks.

**Comment by sobolevn** [comment]
Awesome! Please, feel free to ask for help.

**Comment by sobolevn** [comment]
Hi @CUBERLEON, how's it going? Do you need any help?
