### ISSUE TITLE
Reading from a closed stdin buffer error

### ISSUE THREAD

**Issue by nndii** [wemake-services/wemake-python-styleguide#871]
# Bug report

## What's wrong

Opening a file in emacs+flycheck just raises `ValueError: I/O operation on closed file`.
Though it's not an issue with WPS, but with some flake8 plugins, I want this to get off from the ground somehow.

Plugins that are responsible for that:

- [x] flake8-bandit (I already had made a [PR](https://github.com/tylerwince/flake8-bandit/pull/14) and it was merged)
- [x] flake8-print (https://github.com/JBKahn/flake8-print/pull/36)
- [x] flake8-debugger (https://github.com/JBKahn/flake8-debugger/issues/18)
- [x] flake8-rst-docstrings (There are no issues or pr regarding that yet.)

You can dive deeper into the topic by reading flake8-print PR. 
To be able to use WPS now -- I should firstly uninstall those plugins, that's a pain.

## How is that should be

It should work without errors :)

**Comment by sobolevn** [comment]
Thanks a lot for reporting this! I will have to wait until it is resolved. We update dependencies as soon as they are released.

**Comment by sobolevn** [comment]
Opened: https://github.com/peterjc/flake8-rst-docstrings/issues/19

**Comment by peterjc** [comment]
The ``RST900 Failed to load file: I/O operation on closed file`` problem in https://github.com/peterjc/flake8-rst-docstrings/issues/19 looks to have been triggered by either of the other plugins - once they are updated the error goes away.

**Comment by sobolevn** [comment]
Thanks a lot, @peterjc!

P.S. `flake8-rst-docstrings` is awesome! 👍
