### ISSUE TITLE
Forbid `Optional[Union[A, B]]`, use `Union[A, B, None]` instead

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#875]
# Rule request

## Thesis

These two types are equal: `Optional[Union[A, B]] == Union[A, B, None]`

For consistency reasons we need to enforce the second form over the first one.
Related to #792

**Comment by ko3luhbka** [comment]
Hi, I'd like to try to implement this.

**Comment by sobolevn** [comment]
Thanks, @ko3luhbka! You are on it.

**Comment by ko3luhbka** [comment]
I'm working on it, just have some stupid issues with my environment.

**Comment by sobolevn** [comment]
@ko3luhbka thanks! Do you need any help?

**Comment by ko3luhbka** [comment]
@sobolevn well, yes, I actually think that it's time to ask for help :).
I'm sure that it's very simple issue.
So, I just want to make some tracking of what's happening in ../visitors/ast/annotations.py and other modules, by now is just adding ``print`` statements here and there. I've created 'ex.py' file in the project's root dir with code violating a lot of WPS rules (like short variable names, f-string using and some others), and run 'flake8 ex.py' expecting to see WPS violations there. But I see all violations exept WPS. At first I thought that it's maybe a dependency issue and 'wemake-python-styleguide' plugin haven't been installed. But there's a message at the bottom of output : 
``Full list of violations and explanations:
https://wemake-python-stylegui.de/en/0.12.4/pages/usage/violations/,`` 
so plugin is enabled, I guess. 'flake8 --version' outputs 'wemake-python-styleguide: 0.12.4' among others as well.
At the same time, if I run 'flake8 .' from project's root directory, there are WPS errors complaining about some code I started to write to solve the actual issue (#875). 
I didn't change anything in project's 'setup.cfg' and I don't have any global flake8 config files.
I use MacOS Mojave 10.14.6, pyenv virtualenv with Python 3.7.4.
Do you have any ideas what I'm doing wrong?

**Comment by ko3luhbka** [comment]
@sobolevn I finally found what causes this.
My ``ex.py`` test file contains syntax error:
`def invalid_func()`
i.e. function without body and colon after brackets. In this case ``wemake-python-styleguide`` doesn't work while others do.
Isn't it a bug? I know it's hardly a usecase and flake8 actually complained about that ("E999  SyntaxError: invalid syntax").

**Comment by sobolevn** [comment]
No, it is not a bug. That's how it should be. We cannot work with syntax errors. That's what `flake8` does for us. I am glad that your problem is fixed now.

Sorry that I was not able to help you earlier.

**Comment by ko3luhbka** [comment]
@sobolevn thank you for your patience, and actually it was a good lesson for me.
