### ISSUE TITLE
Rule forbidding ``Literal[None]`` doesn't work if ``typing.Literal[None]`` is used.

### ISSUE THREAD

**Issue by hhsdev** [wemake-services/wemake-python-styleguide#876]
# Bug report

## What's wrong

Usage of `Literal[None]` annotation is forbidden (as per #841) but if `typing.Literal[None]` is used, no violations will be raised. 

## How is that should be

A violation should be raised for both `Literal[None]` and `typing.Literal[None]`.

## System information
Ubuntu 18.04 64-bit

I would like to take up on this one if possible.

**Comment by sobolevn** [comment]
@hhsdev are you willing to take this one? If this is the case, then please sync with #874

**Comment by hhsdev** [comment]
Will do so. Thanks.

**Comment by sobolevn** [comment]
Fixed in https://github.com/wemake-services/wemake-python-styleguide/commit/861308aac67083412b2fd350d9afb0ba2396b5c4
