### ISSUE TITLE
Just a couple of typo errors in official documentation...

### ISSUE THREAD

**Issue by ManishAradwad** [wemake-services/wemake-python-styleguide#879]
While going through the docs for ["Creating a new rule tutorial"](https://wemake-python-stylegui.de/en/latest/pages/api/tutorial.html), I found a couple of typo errors.

- 2nd point under "Writing a new plug-in"
- Another one in "Writing a new visitor"

**Comment by ManishAradwad** [comment]
I'll start working on this one right away if its ok..

**Comment by sobolevn** [comment]
Thanks a lot, @ManishAradwad!
