### ISSUE TITLE
Forbid functions with undefined / unknown result order

### ISSUE THREAD

**Issue by kxepal** [wemake-services/wemake-python-styleguide#888]
# Rule request

Forbid or annoy on iteration over the functions which returns result with unknown order.  First line candidates are about file listing functions like `glob.glob` or `os.listdir` and the simiar onces.

## Thesis

Relay on filenames ordering on FS caused a critical bug, which could be easily prevented. Linter must known such edge cases and at least warn user about them.

## Reasoning

https://www.vice.com/en_us/article/zmjwda/a-code-glitch-may-have-caused-errors-in-more-than-100-published-studies

**Comment by sobolevn** [comment]
What solution should we suggest?

**Comment by kxepal** [comment]
I only could imagine the one about list of such functions which has documented warnings about unstable result and then: 1) warn about unstable result 2) force to wrap their calls into sorted or apply sort function in other way.

**Comment by sobolevn** [comment]
Ok, using explicit sorting sounds fine.

**Comment by sobolevn** [comment]
This will be implemented in `typed-linter`.
