### ISSUE TITLE
Forbid incorrect exception order

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#892]
# Rule request

## Thesis

Currently we are allowed to write this code:

```python
    try:
        ...
    except Exception:
        ...
    except ValueError:
        ...
```

What happens here? `except ValueError` will never be reached, because all exception will be covered by `except Exception`.

But, we have a limitation here. Since, we don't know and cannot know any other exception types except the builtin ones, we only check builtin exceptions for now.

## Reasoning

This is a best practice, because this can lead to different bugs.

Original idea: https://github.com/thg-consulting/inspectortiger/blob/6b9736b22528493cd41d0bf92f9fdcdd6c7cd129/inspectortiger/plugins/misc.py#L98

**Comment by Amyth07** [comment]
Can I take this?

**Comment by sobolevn** [comment]
Yes, sure, @Amyth07! Thanks a lot

**Comment by cmppoon** [comment]
Hi, 

Can you assign this to me?

**Comment by sobolevn** [comment]
Done! Thanks a lot!
