### ISSUE TITLE
Enforce consistent `yield from` syntax

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#893]
# Rule request

## Thesis

This code is bad:

```python
def test():
    for x in y:
        yield x
```

Because we can rewrite it like so:

```python
def test():
    yield from y
```

## Reasoning

This is a consistency rule.
Original idea: https://github.com/thg-consulting/inspectortiger/blob/6b9736b22528493cd41d0bf92f9fdcdd6c7cd129/inspectortiger/plugins/upgradeable.py#L25

**Comment by Ben-Drebing** [comment]
Hey @sobolevn, I'm happy to try this one out.

**Comment by sobolevn** [comment]
@Ben-Drebing please, see the updated description.

**Comment by sobolevn** [comment]
@Ben-Drebing sorry, I will take this one. Because I will work on both #953 and this one
