### ISSUE TITLE
Create configuration

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#9]
Currently our linter is full of magic constants like: 
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/high_complexity.py#L44
- https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/high_complexity.py#L58
- and others marked with `TODO: config` in the source code

What we need is:
0. create a file with default configuration values
1. allow users to override these values with `setup.cfg` or any other standard `flake8` tools
2. test that when configuration is applied linter respects it

**Comment by mcproger** [comment]
How about that all the configs will be placed in `setup.cfg`, and there will be some parser that will put the settings in the specific visitor?

**Comment by sobolevn** [comment]
Yes, that's exactly how I see this feature.

@mcproger are you interested in implementing this feature?

**Comment by mcproger** [comment]
Yes, I will try to implement this.

**Comment by sobolevn** [comment]
Great! 

Please, ask any questions you have.

Things to keep in mind:
- [ ] we will need to test config parsing is correct
- [ ] we will need to test that config values take effect on actual checks
- [ ] we will need to provide some basic docs, like: there are values `a`, `b`, and `c`, they must be placed in `setup.cfg` under `[..]` section

**Comment by mcproger** [comment]
OK, I'll try to present my first PR as soon as possible.

**Comment by mcproger** [comment]
@sobolevn Why are these constants a sum of integers? 

https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/high_complexity.py#L51

https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/visitors/high_complexity.py#L58

**Comment by sobolevn** [comment]
I have no idea, that was other me: the bad one 😆

**Comment by sobolevn** [comment]
offtop: the idea seams familiar https://github.com/wemake-shit

**Comment by mcproger** [comment]
We were inspired by this https://github.com/sobolevn/python-code-disasters 😆

**Comment by vergeev** [comment]
@sobolevn Well, we've got plans. Pleeease don't take it as an insult. 

The idea is to store the projects we didn't want to write, but absolutely had to.

**Comment by sobolevn** [comment]
No worries! We all have these projects. 

</offtop>
