### ISSUE TITLE
Forbid positional-only arguments

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#904]
# Rule request

## Thesis

They don't make any sense to me. I haven't seen a need for them in all my python life.

## Reasoning

Good linter should decrease an amount of features and syntax sugar that you are allowed to use. This is a best practice rule.

**Comment by isidentical** [comment]
>  I haven't seen a need for them in all my python life.

PEP 570 explains why developers should use positional arguments when needed, of course this feature can be abused but that counts for every other feature. 

https://www.python.org/dev/peps/pep-0570/#challenges-for-library-authors

**Comment by sobolevn** [comment]
Yes, thanks for the link! 

I have seen this PEP already, and I still don't see much value in this feature. It might be a good idea in one case in a thousand. But, it is surely a bad idea for all other cases.

**Comment by andcmps** [comment]
Hello, I'd like to contribute to this project by taking on this issue!

**Comment by sobolevn** [comment]
You are more than welcome, @andcmps! Assigned.
Thanks a lot! 👍
