### ISSUE TITLE
Typos in Docstrings

### ISSUE THREAD

**Issue by hhsdev** [wemake-services/wemake-python-styleguide#915]
Probably not super important but there is a fair bit of typos accumulated in the docstrings of various violations. Here is all the typos and word misuses I gathered from *one* file:

(Misspelled words are *italicized*. Words that should be added
are __bolden__. Words that should be removed are ~~crossed out~~.)

### Misspellings
* Line 426: Forbids *comparision* ...
* Line 494: Forbids *comparision* ...
* Line 1075: Forbids to use implicit string *contacatenation*
* Line 1312: ... that you *migth* have to ...
* Line 1413: ... to write long *stirngs* that does not ...
* Line 1513: ... hex, and *expanentional* numbers.
* Line 1661: ... throw *``ZeroDivisoionError``*
* Line 1667: Use *``ZeroDivisoionError``* ...
* Line 1688: ... math *opeartions*
* Line 1695: ... is also *redundunt*.
* Line 1698: ... zero *operaionts*.

### Wrong Grammer
* Line 467: should be written __in__ lowercase.
* Line 882: Use lowercase modifiers ~~should be written in lowercase~~.
* Line 1076: ... since you can ~~possible~~ __possibly__ miss a comma.
* Line 1514: There are ~ ~~infinitive~~ __infinite__ ways to ...
* Line 1520: ... numbers in ~~a~~ __an__ infinite ways?

### Less-than-ideal Grammer?
* Line 796: ... ~~when~~ __in case of__ a single ...
* Line 797: ... ~~when~~ __in case of__ a multi-line...
* Line 1145: ... might ~~be~~ also __be__ an overuse ...
* Line 1148: ... make sure it makes ~~any~~ sense.
* Line 1176: ... make sure it makes ~~any~~ sense.
* Line 1487: ... (we discourage ~~to use~~ __using__ them)
* Line 1574: Forbids __to__ use ~~lower-case~~ lowercase letters as ...
* Line 1581: Use ~~upper-case~~ uppercase  
* Line 1758: Forbids imports that ~~outside of the module~~ may cause confusion __outside of the module__.

Instead of fixing them piecemeal, I think it would be nice to just open an issue and let one guy get an easy PR, now being Hacktoberfest and all.

If nobody would take it, I can work on it.

**Comment by sobolevn** [comment]
Wow 😢 

Can you please fix them?

**Comment by hhsdev** [comment]
Alright, leave it to me!

**Comment by themayurkumbhar** [comment]
Hi @hhsdev i will take this

**Comment by hhsdev** [comment]
Lol, that was fast. Guess I gotta find new issues now.

**Comment by sobolevn** [comment]
Closed by https://github.com/wemake-services/wemake-python-styleguide/pull/916
