### ISSUE TITLE
Update mypy version

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#917]
We need to update the `mypy` version. 

Here's the related PR: https://github.com/wemake-services/wemake-python-styleguide/pull/910

But, when updated `mypy` finds new problem:

```
mypy wemake_python_styleguide
wemake_python_styleguide/logic/safe_eval.py:84: error: On Python 3 '{}'.format(b'abc') produces "b'abc'"; use !r if this is a desired behavior
Found 1 error in 1 file (checked 102 source files)
```

Link to the CI: https://travis-ci.org/wemake-services/wemake-python-styleguide/jobs/599096909

So, what do we need to do?
1. Bump `mypy` version
2. Fix the warning in the source code

This is an entry-level task for beginners.

**Comment by ammarnajjar** [comment]
I would like to give this a shot, if it's ok 😄

**Comment by sobolevn** [comment]
Closed by https://github.com/wemake-services/wemake-python-styleguide/pull/919
