### ISSUE TITLE
Force using tuples in frozenset constructor

### ISSUE THREAD

**Issue by slapshin** [wemake-services/wemake-python-styleguide#920]
# Rule request

## Thesis

Force using tuples in frozenset constructor. For example,

```python
a = frozenset([2])
```
should be rewritten as

```python
a = frozenset((2,))
```

## Reasoning
Immutable types in constructors are more consistent then mutable

**Comment by sobolevn** [comment]
What else except `frozentuple` can we check?

**Comment by slapshin** [comment]
Sorry, can't give an example from built-in functions

**Comment by sobolevn** [comment]
@slapshin would you take this one? Let's make it a refactoring rule.

**Comment by slapshin** [comment]
Ok, cool! I suggest adding `ForceTupleArgumentViolation`
