### ISSUE TITLE
Add separate test for violations controlled by `i_control_code` option

### ISSUE THREAD

**Issue by ko3luhbka** [wemake-services/wemake-python-styleguide#957]
Some violations are ignored when `i_control_code` options is set to `True` (like WPS113). Thus, we have to disable them in `SHOULD_BE_RAISED` list because e2e tests run with `i_control_code = True`. So these violations are actually not completely tested.
Why not to have a separate list of violations which only raise when `i_control_code = False`? And run separate test(s) with `--i_control_code=False`.

**Comment by sobolevn** [comment]
Thanks for the report 👍

**Comment by ko3luhbka** [comment]
May I work on this?

**Comment by sobolevn** [comment]
Sure! Thanks!

**Comment by ko3luhbka** [comment]
I faced with a problem of disabling `i_control_code` in end-to-end tests.
Since the option is enabled by default and we can't tell flake8 to disable it somehow (because this option is just a flag without a value) I can't make WPS113 appear when checking bad code. Are there any possibility to workaround this? Change `setup.cfg` at runtime doesn't look like a good idea.
If default value for this option was `False` then everything would work fine: I just add `--i-control-code` to flake8 options and it's done.

**Comment by sobolevn** [comment]
Have you tried `--i-control-code=false`?

**Comment by ko3luhbka** [comment]
Yes, flake8 complains:
> flake8: error: --i-control-code option does not take a value
I also tried "False", "0", "no" values and all of this but with a space instead of the equal sign. It doesn't work this way.

**Comment by sobolevn** [comment]
Oh, wow. It should! That's a new bug you found! 👍

**Comment by ko3luhbka** [comment]
Oh, feel a bit stupid that I didn' t understand it earlier :)

**Comment by sobolevn** [comment]
Done, now #966 is fixes, you can continue to work on this one! 👍
