### ISSUE TITLE
`i-control-code` cannot be disabled using flake8 command option

### ISSUE THREAD

**Issue by ko3luhbka** [wemake-services/wemake-python-styleguide#966]
# Bug report

## What's wrong
`i-control-code=True` by default. If I have a code which violates some rules controlled by `i-control-code` (for example, WPS113) and I want to ingnore these rules, I can't just pass `--i-control-code=false` to flake8 because it won't accept it:
> flake8 --i-control-code=no --select WPS module.py
Usage: flake8 [options] file file ...

flake8: error: --i-control-code option does not take a value

The only way to ignore the violation is to set `i-control-code = False` in flake8 configuration file (setup.cfg, for example). And it's very inconvenient sometimes (see #957).
But, if `i-control-code = False` in config file, I actually can enable it from command line just passing `--i-control-code` to flake8 arguments without value.
## How is that should be
`i-control-code` should be fully configurable from both configuration file and command line.  Command line option should have precedence.

## System information
MacOS Mojave 10.14.6
### flake8 information

Contents of `flake8 --bug-report`:
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.5",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-annotations-complexity",
      "version": "0.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "2.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 4.0.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.2.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-executable",
      "version": "2.0.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "3.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-pytest",
      "version": "1.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-return",
      "version": "0.1.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_builtins",
      "version": "1.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_coding",
      "version": "1.3.2"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_pep3101",
      "version": "1.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "logging-format",
      "version": "0.6.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.8.2"
    },
    {
      "is_local": false,
      "plugin": "nitpick",
      "version": "0.21.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    },
    {
      "is_local": false,
      "plugin": "radon",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.11"
    },
    {
      "is_local": false,
      "plugin": "wemake-python-styleguide",
      "version": "0.12.5"
    }
  ],
  "version": "3.7.8"
}

### pip information

Contents of `pip freeze`:
added-value==0.14.2
alabaster==0.7.12
appnope==0.1.0
astor==0.8.0
atomicwrites==1.3.0
attrs==19.2.0
autopep8==1.4.4
Babel==2.7.0
backcall==0.1.0
bandit==1.6.2
certifi==2019.9.11
chardet==3.0.4
Click==7.0
colorama==0.3.9
coverage==4.5.4
decorator==4.4.0
dictdiffer==0.8.0
doc8==0.8.0
docutils==0.13.1
dparse==0.4.1
entrypoints==0.3
eradicate==1.0
fastdiff==0.2.0
flake8==3.7.8
flake8-annotations-complexity==0.0.2
flake8-bandit==2.1.2
flake8-broken-line==0.1.1
flake8-bugbear==19.8.0
flake8-builtins==1.4.1
flake8-coding==1.3.2
flake8-commas==2.0.0
flake8-comprehensions==2.2.0
flake8-debugger==3.1.0
flake8-docstrings==1.5.0
flake8-eradicate==0.2.2
flake8-executable==2.0.3
flake8-isort==2.7.0
flake8-logging-format==0.6.0
flake8-pep3101==1.2.1
flake8-plugin-utils==1.0.0
flake8-polyfill==1.0.2
flake8-print==3.1.0
flake8-pytest==1.3
flake8-pytest-style==0.1.3
flake8-quotes==2.1.0
flake8-rst-docstrings==0.0.11
flake8-string-format==0.2.3
gitdb2==2.0.6
GitPython==3.0.2
grimp==1.0b13
idna==2.8
imagesize==1.1.0
import-linter==1.0b5
importlib-metadata==0.23
ipdb==0.12.2
ipython==7.8.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.1
jmespath==0.9.4
m2r==0.2.1
mando==0.6.4
MarkupSafe==1.1.1
marshmallow==3.2.1
marshmallow-polyfield==5.7
mccabe==0.6.1
mistune==0.8.4
more-itertools==7.2.0
mypy==0.730
mypy-extensions==0.4.1
natsort==6.0.0
networkx==2.3
nitpick==0.21.1
packaging==19.2
parso==0.5.1
pbr==5.4.3
pep8-naming==0.8.2
pexpect==4.7.0
pickleshare==0.7.5
pluggy==0.13.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.5.0
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.4.2
pyparsing==2.4.2
pytest==5.2.1
pytest-cov==2.8.1
pytest-randomly==3.1.0
python-slugify==3.0.4
pytz==2019.2
PyYAML==4.2b4
radon==2.4.0
requests==2.22.0
restructuredtext-lint==1.3.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
safety==1.8.5
six==1.12.0
smmap2==2.0.5
snapshottest==0.5.1
snowballstemmer==1.9.1
sortedcontainers==2.1.0
Sphinx==2.2.0
sphinx-autodoc-typehints==1.8.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-mermaid==0.3.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
stevedore==1.31.0
termcolor==1.1.0
testfixtures==6.10.0
text-unidecode==1.3
toml==0.10.0
tomlkit==0.5.7
traitlets==4.3.2
typed-ast==1.4.0
typing==3.7.4.1
typing-extensions==3.7.4
urllib3==1.25.6
wasmer==0.3.0
wcwidth==0.1.7
xenon==0.5.5
zipp==0.6.0

**Comment by ko3luhbka** [comment]
@sobolevn, how would you implement this? Still as one options with True/False value or as separate options-flags, like `--i-control-code` and `--i-dont-control-code`? 
As far as I understood there's no `boolean` type in optparse out of the box, so you have to either write a class for it or (if I got it right) write a callback function which performs conversion from `str` to `bool`.

**Comment by sobolevn** [comment]
I am actually working on it right now 🙂 
I will push this fix in 10 minutes.
