### ISSUE TITLE
Problem with BooleanPositionalArgumentViolation

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#999]
# Bug report

## What's wrong
Some libraries (query builder in my case) have an api like that
```python
query = Query(table)
query.set(field_name, True)
```
Which raises BooleanPositionalArgumentViolation, because there is a comma, not equal sign.

## How is that should be
Not sure. It's definitely not the best api I've seen. But I can't remove it. And settings `noqa: 
WPS425` on every line is ugly.

**Comment by sobolevn** [comment]
Is it possible to use `query.set(field_name, value=True)`?

**Comment by AlwxSin** [comment]
I guess I can. Ok, thanks.
